### PR TITLE
build: switch all builds systems and CI/ID to go 1.16, update min go version, add support for compiling M1 binaries

### PR DESCRIPTION
**Pull request by Roasbeef**
Creating this early so we can feel out if there're any changes in Go 1.16 that affect `lnd` itself. 

I have an M1 laptop now, and I've been using `go1.16beta` up until now. I didn't notice any thing out of the ordinary, other than certain tests being extremely slow to the point they don't pass as they timeout with the default settings. An example of such a test is: `htclswitch/TestChannelLinkCancelFullCommitment`. Our "async payment benchmark" tests pass, but advertise "2 TPS" (to be taken with a grain of salt ofc). My early analysis leads me to beleive there's a concurrency interaction in the switch's mailbox code that ends up soft live locking on the M1.

### CODE REVIEW

**Review by guggero — APPROVED** [review]
Nice, LGTM :tada:

**Comment by Roasbeef** [comment]
Build seems to be ok, which points to possible issues with some of our concurrency logic w/ the M1 arch itself.

**Comment by Roasbeef** [comment]
Added a new commit that retracts version `v0.0.2`: https://github.com/lightningnetwork/lnd/pull/5034/commits/ee8f1a811e7acf23f930e57ebc787b548976764f

**Comment by Roasbeef** [comment]
Restarted the build on this...seeing on async payment benchmark timeouts which matches up w/ wha tI've seen locally on my M1 (concurrency issue somewhere in the switch).

**Comment by Roasbeef** [comment]
Moving ahead w/ this as 1.16 appears to be fine, but there's still some lingering M1 issue (in the context of the tests at least, I've been running a node locally w/ no problems).

**Pull request merged**
