### PR TITLE
lnwire: Support upfront shutdown script feature

### PR DESCRIPTION
**Pull request by stevenroose**
I noticed that this was part of the RFC, but not yet implemented here.

### CODE REVIEW

**Comment by Roasbeef** [comment]
As is, this PR is complete as it doesn't actually implement the logic to use the option if supported by the other party, or ensure that both sides commit to the same delivery script.

**Comment by stevenroose** [comment]
I suppose you mean s/complete/incomplete? I know, it's an lnwire update, though. It doesn't make lnd use the feature flag yet, so it just makes it understand peers using the feature flag.

**Comment by Roasbeef** [comment]
Needs a rebase!

**Comment by stevenroose** [comment]
I tried rebasing, but I forgot about the original logic so I can't reliably review my own work :) So I trust your reviewing judgement!

**Comment by carlaKC** [comment]
Replaced with 3655, this commit is included in the new PR 😄

**Pull request closed without merging**
