### PR TITLE
lnwallet+docs: minrelayfee always above fee floor

### LINKED ISSUE #6072: lnd is using 250 sat/kw instead of 253 sat/kw for estimation
### Background

I'm testing the remote signer lnd setup with a watch-only node following the directions in remote-signer.md. I followed the instructions using a watch-only node and remote-signer node both pointed to the same testnet bitcoind instance. I created an address on the watch-only node and deposited to that address. The funds show up on both nodes, however the watch-only mode (which has autopilot enabled to open channels) attempts to create a channel but fails. 

### Your environment

* v0.14.1-beta
* Linux  5.10.0-1051-oem - Ubuntu 20.04
* Bitcoin Core version v22.0.0

### Steps to reproduce

Follow the instructions in remote-signer.md for testnet nodes. Enable autopilot on the watch only node. Create an address on the watch only node. Deposit funds to the address.

### Expected behaviour

Autopilot successfully creates channels automatically.

### Actual behaviour

Autopilot attempts to create channels automatically on the watch-only node but fails. A pending channel is created but no opening tx is broadcast and the funds disappear from the watch-only node, whereas the remote-signing node shows the full original balance and no pending channels.

```
$ lncli pendingchannels
{
    "total_limbo_balance": "0",
    "pending_open_channels": [
        {
            "channel": {
                "remote_node_pub": "03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431",
                "channel_point": "43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0",
                "capacity": "16777063",
                "local_balance": "16776122",
                "remote_balance": "0",
                "local_chan_reserve_sat": "167770",
                "remote_chan_reserve_sat": "167770",
                "initiator": "INITIATOR_LOCAL",
                "commitment_type": "ANCHORS",
                "num_forwarding_packages": "0"
            },
            "confirmation_height": 0,
            "commit_fee": "281",
            "commit_weight": "772",
            "fee_per_kw": "250"
        }
    ],
    "pending_closing_channels": [
    ],
    "pending_force_closing_channels": [
    ],
    "waiting_close_channels": [
    ]
}

```

#### Watch-only node logs

```
2021-12-08 00:06:09.190 [INF] FNDG: Initiating fundingRequest(local_amt=0.16777215 BTC (subtract_fees=true), push_amt=0 mSAT, chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, peer=03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431, min_confs=1)
2021-12-08 00:06:09.190 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): requesting new chans from height=0 and 2106558 blocks after
2021-12-08 00:06:09.191 [INF] CHFD: Performing funding tx coin selection using 250 sat/kw as fee rate
2021-12-08 00:06:09.200 [WRN] CHFD: Unable to find funding output for shim intent: unable to create witness script, no funding keys
2021-12-08 00:06:09.210 [INF] PEER: Negotiated chan series queries with 020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8
2021-12-08 00:06:09.210 [INF] DISC: Creating new GossipSyncer for peer=020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8
2021-12-08 00:06:09.210 [INF] NTFN: New block epoch subscription
2021-12-08 00:06:09.212 [INF] SRVR: Established connection to: 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78@178.128.228.41:29735
2021-12-08 00:06:09.212 [INF] SRVR: Finalizing connection to 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78@178.128.228.41:29735, inbound=false
2021-12-08 00:06:09.260 [INF] NTFN: New block epoch subscription
2021-12-08 00:06:09.260 [INF] PEER: Negotiated chan series queries with 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78
2021-12-08 00:06:09.260 [INF] DISC: Creating new GossipSyncer for peer=0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78
2021-12-08 00:06:09.272 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): buffering chan range reply of size=6590
2021-12-08 00:06:09.272 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): filtering through 6590 chans
2021-12-08 00:06:09.275 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): starting query for 32 new chans
2021-12-08 00:06:09.275 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): querying for 32 new channels
2021-12-08 00:06:09.276 [INF] FNDG: Target commit tx sat/kw for pendingID(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d): 250
2021-12-08 00:06:09.276 [INF] FNDG: Dust limit for pendingID(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d): 0.00000354 BTC
2021-12-08 00:06:09.276 [INF] FNDG: Starting funding workflow with 34.192.102.161:9735 for pending_id(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d), committype=anchors-zero-fee-second-level
2021-12-08 00:06:09.276 [INF] FNDG: Initiating fundingRequest(local_amt=0.16777215 BTC (subtract_fees=true), push_amt=0 mSAT, chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, peer=020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8, min_confs=1)
2021-12-08 00:06:09.277 [INF] CHFD: Performing funding tx coin selection using 250 sat/kw as fee rate
2021-12-08 00:06:09.277 [INF] FNDG: Initiating fundingRequest(local_amt=0.16777215 BTC (subtract_fees=true), push_amt=0 mSAT, chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, peer=0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78, min_confs=1)
2021-12-08 00:06:09.277 [WRN] ATPL: Unable to open channel to 020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8 of 0.16777215 BTC: not enough witness outputs to create funding transaction, need 0.16777215 BTC only have 0 BTC  available
2021-12-08 00:06:09.277 [INF] SRVR: Disconnecting from 020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8@3.19.96.177:9735
2021-12-08 00:06:09.277 [INF] PEER: disconnecting 020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8@3.19.96.177:9735, reason: server: disconnecting peer 020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8@3.19.96.177:9735
2021-12-08 00:06:09.277 [INF] PEER: unable to read message from 020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8@3.19.96.177:9735: read tcp 192.168.1.187:46800->3.19.96.177:9735: use of closed network connection
2021-12-08 00:06:09.278 [INF] CHFD: Performing funding tx coin selection using 250 sat/kw as fee rate
2021-12-08 00:06:09.278 [WRN] ATPL: Unable to open channel to 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78 of 0.16777215 BTC: not enough witness outputs to create funding transaction, need 0.16777215 BTC only have 0 BTC  available
2021-12-08 00:06:09.278 [INF] SRVR: Disconnecting from 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78@178.128.228.41:29735
2021-12-08 00:06:09.278 [INF] PEER: disconnecting 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78@178.128.228.41:29735, reason: server: disconnecting peer 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78@178.128.228.41:29735
2021-12-08 00:06:09.278 [INF] PEER: unable to read message from 0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78@178.128.228.41:29735: read tcp 192.168.1.187:58388->178.128.228.41:29735: use of closed network connection
2021-12-08 00:06:09.329 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): no more chans to query
2021-12-08 00:06:09.329 [INF] DISC: GossipSyncer(03bae2db4b57738c1ec1ffa1c5e5a4423968cc592b3b39cddf7d495e72919d6431): applying gossipFilter(start=2021-12-08 00:06:09.329147575 -0500 EST m=+53.412366547, end=2158-01-14 06:34:24.329147575 -0500 EST)
2021-12-08 00:06:09.329 [INF] DISC: GossipSyncer(020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8): applying gossipFilter(start=2021-12-08 00:06:09.329199431 -0500 EST m=+53.412418402, end=2158-01-14 06:34:24.329199431 -0500 EST)
2021-12-08 00:06:09.329 [INF] DISC: GossipSyncer(0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78): applying gossipFilter(start=2021-12-08 00:06:09.32928303 -0500 EST m=+53.412502002, end=2158-01-14 06:34:24.32928303 -0500 EST)
2021-12-08 00:06:09.342 [INF] SRVR: Established connection to: 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08@163.172.47.240:9735
2021-12-08 00:06:09.342 [INF] SRVR: Finalizing connection to 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08@163.172.47.240:9735, inbound=false
2021-12-08 00:06:09.344 [INF] FNDG: Recv'd fundingResponse for pending_id(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d)
2021-12-08 00:06:09.378 [INF] DISC: Removing GossipSyncer for peer=020ec0c6a0c4fe5d8a79928ead294c36234a76f6e0dca896c35413612a3fd8dbf8
2021-12-08 00:06:09.378 [INF] DISC: Removing GossipSyncer for peer=0274fa8311c650e76a1897db1cca2fb20d598ded5b62d72f452fd2debea3499d78
2021-12-08 00:06:09.378 [INF] SRVR: Established connection to: 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f@217.173.236.77:29735
2021-12-08 00:06:09.379 [INF] SRVR: Finalizing connection to 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f@217.173.236.77:29735, inbound=false
2021-12-08 00:06:09.435 [INF] SRVR: Established connection to: 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2@176.9.89.217:2000
2021-12-08 00:06:09.435 [INF] SRVR: Finalizing connection to 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2@176.9.89.217:2000, inbound=false
2021-12-08 00:06:09.438 [INF] NTFN: New block epoch subscription
2021-12-08 00:06:09.438 [INF] PEER: Negotiated chan series queries with 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08
2021-12-08 00:06:09.439 [INF] DISC: Creating new GossipSyncer for peer=031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08
2021-12-08 00:06:09.439 [INF] DISC: GossipSyncer(031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08): applying gossipFilter(start=2021-12-08 00:06:09.43907987 -0500 EST m=+53.522298877, end=2158-01-14 06:34:24.43907987 -0500 EST)
2021-12-08 00:06:09.481 [INF] FNDG: pendingChan(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d): remote party proposes num_confs=5, csv_delay=2015
2021-12-08 00:06:09.481 [INF] FNDG: Generated ChannelPoint(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0) for pending_id(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d)
2021-12-08 00:06:09.481 [INF] FNDG: Initiating fundingRequest(local_amt=0.16113925 BTC (subtract_fees=true), push_amt=0 mSAT, chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, peer=031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08, min_confs=1)
2021-12-08 00:06:09.482 [INF] CHFD: Performing funding tx coin selection using 250 sat/kw as fee rate
2021-12-08 00:06:09.482 [WRN] ATPL: Unable to open channel to 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08 of 0.16113925 BTC: not enough witness outputs to create funding transaction, need 0.16113925 BTC only have 0 BTC  available
2021-12-08 00:06:09.482 [INF] SRVR: Disconnecting from 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08@163.172.47.240:9735
2021-12-08 00:06:09.482 [INF] PEER: disconnecting 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08@163.172.47.240:9735, reason: server: disconnecting peer 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08@163.172.47.240:9735
2021-12-08 00:06:09.482 [INF] PEER: unable to read message from 031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08@163.172.47.240:9735: read tcp 192.168.1.187:42690->163.172.47.240:9735: use of closed network connection
2021-12-08 00:06:09.483 [INF] DISC: Obtained 3 addrs to bootstrap network with
2021-12-08 00:06:09.506 [INF] PEER: Negotiated chan series queries with 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f
2021-12-08 00:06:09.506 [INF] NTFN: New block epoch subscription
2021-12-08 00:06:09.506 [INF] DISC: Creating new GossipSyncer for peer=0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f
2021-12-08 00:06:09.506 [INF] FNDG: Initiating fundingRequest(local_amt=0.16777215 BTC (subtract_fees=true), push_amt=0 mSAT, chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, peer=0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f, min_confs=1)
2021-12-08 00:06:09.506 [INF] DISC: GossipSyncer(0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f): applying gossipFilter(start=2021-12-08 00:06:09.506374401 -0500 EST m=+53.589593376, end=2158-01-14 06:34:24.506374401 -0500 EST)
2021-12-08 00:06:09.507 [INF] CHFD: Performing funding tx coin selection using 250 sat/kw as fee rate
2021-12-08 00:06:09.507 [WRN] ATPL: Unable to open channel to 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f of 0.16777215 BTC: not enough witness outputs to create funding transaction, need 0.16777215 BTC only have 0 BTC  available
2021-12-08 00:06:09.507 [INF] SRVR: Disconnecting from 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f@217.173.236.77:29735
2021-12-08 00:06:09.507 [INF] PEER: disconnecting 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f@217.173.236.77:29735, reason: server: disconnecting peer 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f@217.173.236.77:29735
2021-12-08 00:06:09.507 [INF] PEER: unable to read message from 0241bc65c496503b1dd27bc80379cb959fb82ad26673d237b3c8f59289fb99742f@217.173.236.77:29735: read tcp 192.168.1.187:53464->217.173.236.77:29735: use of closed network connection
2021-12-08 00:06:09.517 [INF] FNDG: Broadcasting funding tx for ChannelPoint(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0): 020000000001015e3e161d077ed932f6959524068afa1ca77845355f7f3193e276b658f3b3ee040100000000000000000267ffff0000000000220020b3cc9065e0dbe9184b54dc71c290b6216cd04507c7a07792e97f87567a2af1a501e1f50400000000160014d70e810d47c55bf5713fa8160d66761e5eb81e1b02483045022100a926e17028235c5f2fd95774c773af3ac3120cfaf5af9f376e40dac9b527a4cf022015156f5f94cb6ed6c6f27f138198d2674a418713326f967a620db4bb846fe934012103222bcd1e6e959b745602c1dbd40aed9875e14f88ab232f29e6445648fd61fe6700000000
2021-12-08 00:06:09.518 [INF] LNWL: Inserting unconfirmed transaction 43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a
2021-12-08 00:06:09.552 [INF] LNWL: Removed invalid transaction: (*wire.MsgTx)(0xc001f3b800)({
 Version: (int32) 2,
 TxIn: ([]*wire.TxIn) (len=1 cap=15) {
  (*wire.TxIn)(0xc0017c7ec0)({
   PreviousOutPoint: (wire.OutPoint) 04eeb3f358b676e293317f5f354578a71cfa8a06249595f632d97e071d163e5e:1,
   SignatureScript: ([]uint8) <nil>,
   Witness: (wire.TxWitness) (len=2 cap=2) {
    ([]uint8) (len=72 cap=80) {
     00000000  30 45 02 21 00 a9 26 e1  70 28 23 5c 5f 2f d9 57  |0E.!..&.p(#\_/.W|
     00000010  74 c7 73 af 3a c3 12 0c  fa f5 af 9f 37 6e 40 da  |t.s.:.......7n@.|
     00000020  c9 b5 27 a4 cf 02 20 15  15 6f 5f 94 cb 6e d6 c6  |..'... ..o_..n..|
     00000030  f2 7f 13 81 98 d2 67 4a  41 87 13 32 6f 96 7a 62  |......gJA..2o.zb|
     00000040  0d b4 bb 84 6f e9 34 01                           |....o.4.|
    },
    ([]uint8) (len=33 cap=48) {
     00000000  03 22 2b cd 1e 6e 95 9b  74 56 02 c1 db d4 0a ed  |."+..n..tV......|
     00000010  98 75 e1 4f 88 ab 23 2f  29 e6 44 56 48 fd 61 fe  |.u.O..#/).DVH.a.|
     00000020  67                                                |g|
    }
   },
   Sequence: (uint32) 0
  })
 },
 TxOut: ([]*wire.TxOut) (len=2 cap=15) {
  (*wire.TxOut)(0xc00084c740)({
   Value: (int64) 16777063,
   PkScript: ([]uint8) (len=34 cap=500) {
    00000000  00 20 b3 cc 90 65 e0 db  e9 18 4b 54 dc 71 c2 90  |. ...e....KT.q..|
    00000010  b6 21 6c d0 45 07 c7 a0  77 92 e9 7f 87 56 7a 2a  |.!l.E...w....Vz*|
    00000020  f1 a5                                             |..|
   }
  }),
  (*wire.TxOut)(0xc000d286a0)({
   Value: (int64) 83222785,
   PkScript: ([]uint8) (len=22 cap=500) {
    00000000  00 14 d7 0e 81 0d 47 c5  5b f5 71 3f a8 16 0d 66  |......G.[.q?...f|
    00000010  76 1e 5e b8 1e 1b                                 |v.^...|
   }
  })
 },
 LockTime: (uint32) 0
})

2021-12-08 00:06:09.552 [ERR] FNDG: Unable to broadcast funding tx 020000000001015e3e161d077ed932f6959524068afa1ca77845355f7f3193e276b658f3b3ee040100000000000000000267ffff0000000000220020b3cc9065e0dbe9184b54dc71c290b6216cd04507c7a07792e97f87567a2af1a501e1f50400000000160014d70e810d47c55bf5713fa8160d66761e5eb81e1b02483045022100a926e17028235c5f2fd95774c773af3ac3120cfaf5af9f376e40dac9b527a4cf022015156f5f94cb6ed6c6f27f138198d2674a418713326f967a620db4bb846fe934012103222bcd1e6e959b745602c1dbd40aed9875e14f88ab232f29e6445648fd61fe6700000000 for ChannelPoint(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0): unmatched backend error: -26: min relay fee not met, 152 < 153
2021-12-08 00:06:09.552 [INF] CNCT: Creating new ChannelArbitrator for ChannelPoint(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0)
2021-12-08 00:06:09.554 [INF] CNCT: ChannelArbitrator(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0): starting state=StateDefault, trigger=chainTrigger, triggerHeight=2106558
2021-12-08 00:06:09.554 [INF] NTFN: New spend subscription: spend_id=1, outpoint=43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0, script=0 b3cc9065e0dbe9184b54dc71c290b6216cd04507c7a07792e97f87567a2af1a5, height_hint=2106558
2021-12-08 00:06:09.554 [INF] NTFN: Dispatching historical spend rescan for outpoint=43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0, script=0 b3cc9065e0dbe9184b54dc71c290b6216cd04507c7a07792e97f87567a2af1a5, start=2106558, end=2106558
2021-12-08 00:06:09.555 [INF] FNDG: Finalizing pending_id(a22b5ecb85ea68aa40c4aa566ae29e2e63d72c2c5d76fe1e8f62b3ecd5e9750d) over ChannelPoint(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0), waiting for channel open on-chain
2021-12-08 00:06:09.555 [INF] CNCT: Close observer for ChannelPoint(43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0) active
2021-12-08 00:06:09.555 [INF] NTFN: New confirmation subscription: conf_id=1, txid=43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a, num_confs=5 height_hint=2106558
2021-12-08 00:06:09.556 [INF] FNDG: Waiting for funding tx (43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a) to reach 5 confirmations
2021-12-08 00:06:09.556 [INF] CHBU: Updating on-disk multi SCB backup: num_old_chans=0, num_new_chans=1
2021-12-08 00:06:09.557 [INF] PEER: Negotiated chan series queries with 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2
2021-12-08 00:06:09.557 [INF] NTFN: New block epoch subscription
2021-12-08 00:06:09.557 [INF] FNDG: Initiating fundingRequest(local_amt=0.16777215 BTC (subtract_fees=true), push_amt=0 mSAT, chain_hash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, peer=0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2, min_confs=1)
2021-12-08 00:06:09.557 [INF] DISC: Creating new GossipSyncer for peer=0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2
2021-12-08 00:06:09.557 [INF] NTFN: Historical spend dispatch finished for request outpoint=43fae67a46ac7693a3d3758fa88b26dbf9298af481c115ad2722628175a2834a:0, script=0 b3cc9065e0dbe9184b54dc71c290b6216cd04507c7a07792e97f87567a2af1a5 (start=2106558 end=2106558) with details: <nil>
2021-12-08 00:06:09.558 [INF] CHFD: Performing funding tx coin selection using 250 sat/kw as fee rate
2021-12-08 00:06:09.558 [WRN] ATPL: Unable to open channel to 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2 of 0.16777215 BTC: not enough witness outputs to create funding transaction, need 0.16777215 BTC only have 0 BTC  available
2021-12-08 00:06:09.558 [INF] SRVR: Disconnecting from 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2@176.9.89.217:2000
2021-12-08 00:06:09.558 [INF] PEER: disconnecting 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2@176.9.89.217:2000, reason: server: disconnecting peer 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2@176.9.89.217:2000
2021-12-08 00:06:09.558 [INF] PEER: unable to read message from 0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2@176.9.89.217:2000: read tcp 192.168.1.187:44692->176.9.89.217:2000: use of closed network connection
2021-12-08 00:06:09.567 [INF] CHBU: Updating backup file at /home/danielmcnally/.lnd-watch/data/chain/bitcoin/testnet/channel.backup
2021-12-08 00:06:09.571 [INF] CHBU: Swapping old multi backup file from /home/danielmcnally/.lnd-watch/data/chain/bitcoin/testnet/temp-dont-use.backup to /home/danielmcnally/.lnd-watch/data/chain/bitcoin/testnet/channel.backup
2021-12-08 00:06:09.581 [INF] SRVR: Established connection to: 03430676be33c112279097929f25f6f585c0fc71bc692d77d04975029ffb01e8b3@34.139.91.33:9735
2021-12-08 00:06:09.581 [INF] SRVR: Finalizing connection to 03430676be33c112279097929f25f6f585c0fc71bc692d77d04975029ffb01e8b3@34.139.91.33:9735, inbound=false
2021-12-08 00:06:09.583 [INF] DISC: Removing GossipSyncer for peer=031e276436d65a08be1fb0fab1cdb32c11c176737b2653b96ad437fa39da25af08
2021-12-08 00:06:09.583 [INF] DISC: GossipSyncer(0230d84c21cb2be5a00e64d2704ebe2ff80602523480d8625d9532ba78302debe2): applying gossipFilter(start=2021-12-08 00:06:09.583153703 -0500 EST m=+53.666372673, end=2158-01-14 06:34:24.583153703 -0500 EST)
```

There appear to be no relevant logs on the remote-signer node.

### PR DESCRIPTION
**Pull request by ellemouton**
The minimum relay fee is always ensured to be above our fee floor except
in the very first min relay fee query to bitcoind. This commit ensures
that the fee floor is respected in this first query.

Fixes #6072

### CODE REVIEW

**Comment by sangaman** [comment]
Thank you! I tested this branch to open a channel on my node that was previously stuck on 250 sat/kw which was insufficient for channel broadcasts on testnet.

The channel funding tx broadcast worked, but interestingly I got a higher fee rate than expected of 3 sat/byte, see below

`[INF] CHFD: Performing funding tx coin selection using 747 sat/kw as fee rate`

https://blockstream.info/testnet/tx/8d21ecf648fd99a7781f16ef99e90d52d120f42b7c53dcc49c38f5a00f7cc64f

This was during a flurry of blocks on testnet (multiple within a minute) and near empty mempools and 1 sat/byte recommended by mempool.space. So I found this a bit odd, but I'll try a channel open again when testnet is under more normal conditions with blocks spaced a few minutes apart.

**Comment by Crypt-iQ** [comment]
> Thank you! I tested this branch to open a channel on my node that was previously stuck on 250 sat/kw which was insufficient for channel broadcasts on testnet.
> 
> The channel funding tx broadcast worked, but interestingly I got a higher fee rate than expected of 3 sat/byte, see below
> 
> `[INF] CHFD: Performing funding tx coin selection using 747 sat/kw as fee rate`
> 
> https://blockstream.info/testnet/tx/8d21ecf648fd99a7781f16ef99e90d52d120f42b7c53dcc49c38f5a00f7cc64f
> 
> This was during a flurry of blocks on testnet (multiple within a minute) and near empty mempools and 1 sat/byte recommended by mempool.space. So I found this a bit odd, but I'll try a channel open again when testnet is under more normal conditions with blocks spaced a few minutes apart.

747 sat/kw is roughly 3 sat/byte

**Comment by Roasbeef** [comment]
> This was during a flurry of blocks on testnet (multiple within a minute) and near empty mempools and 1 sat/byte recommended by mempool.space.

`lnd` will just use w/e is returned by the fee estimator. Testnet is weird at times, and you'll see transactions over paying routinely as there're no economic constraints, so I wouldn't take too much stock in estimate returned on testnet.

**Review by Roasbeef — APPROVED** [review]
LGTM ☄️

**Pull request merged**
