### PR TITLE
update the version of ltcd

### PR DESCRIPTION
**Pull request by wangxinxi**

### CODE REVIEW

**Comment by wangxinxi** [comment]
@Roasbeef Done!

**Comment by windsok** [comment]
fixes https://github.com/lightningnetwork/lnd/issues/1397

Relevant change from ltcd - https://github.com/ltcsuite/ltcd/pull/8

**Comment by cfromknecht** [comment]
@wangxinxi sorry i missed this, thanks for updating. can you rebase on master?

**Comment by wangxinxi** [comment]
@cfromknecht Let me know if this is good enough or not.

**Comment by cfromknecht** [comment]
@wangxinxi on second thought, can you squash this down into a single commit that modifies both `Gopkg.lock` and `Gopkg.toml`?

**Comment by cfromknecht** [comment]
The commit message should look something like `buid: point to latest ltcd`, you can check out the history of past commits on those files for examples: https://github.com/lightningnetwork/lnd/commits/master/Gopkg.toml

**Comment by Roasbeef** [comment]
Thanks for this PR! Committed as 8baf1726141e9ca36c1ea9fb8e6ffb5930346ed5.

**Pull request closed without merging**
