### PR TITLE
multi: create v0.15.1 rc1 release branch

### PR DESCRIPTION
**Pull request by Roasbeef**

### CODE REVIEW

**Comment by guggero** [comment]
https://github.com/lightningnetwork/lnd/pull/6510 was targeted for 0.15.1 as well. Should we add it to the branch or re-write the release notes to 0.16?

**Comment by Roasbeef** [comment]
@guggero I can add it on (in the future we should make sure something has a clear milestone attached once we commit to review/testing).

**Comment by guggero** [comment]
Okay, thanks! Yeah, my fault with the missing milestone...

**Comment by Roasbeef** [comment]
The release notes are failing (it's a release branch), and also the commit check (rebase conflict in a prior commit _just_ modifying the release notes -- have an idea to resolve this a bit more in the future). Other than that, I think this is g2g. Will push the tag once this is merged.

**Pull request merged**
