### PR TITLE
docs:fix markdown issues in docker/README.md

### PR DESCRIPTION
**Pull request by tailnode**
there are two markdown issues in docker/README.md, so i fixed them.

### CODE REVIEW

**Comment by tailnode** [comment]
I only modified docker/README.md, i don't know why the ci is failed.
Are there some errors in the master branch?
```
--- FAIL: TestLightningNetworkDaemon (116.82s)
	lnd_test.go:12159: Running 47 integration tests
    --- PASS: TestLightningNetworkDaemon/onchain_fund_recovery (39.51s)
    --- PASS: TestLightningNetworkDaemon/basic_funding_flow (0.53s)
    --- PASS: TestLightningNetworkDaemon/unconfirmed_channel_funding (6.47s)
    --- PASS: TestLightningNetworkDaemon/update_channel_policy (8.57s)
    --- PASS: TestLightningNetworkDaemon/open_channel_reorg_test (3.69s)
    --- PASS: TestLightningNetworkDaemon/disconnecting_target_peer (2.84s)
    --- PASS: TestLightningNetworkDaemon/graph_topology_notifications (7.13s)
    --- PASS: TestLightningNetworkDaemon/funding_flow_persistence (19.98s)
    --- FAIL: TestLightningNetworkDaemon/channel_force_closure (16.67s)
    	lnd_test.go:74: Failed: (channel force closure): exited with error: 
    		*errors.errorString expected 0 funds in limbo, found 4378050
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:2428 (0xbe8177)
    			testChannelForceClosure: t.Fatalf("expected 0 funds in limbo, found %d",
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:99 (0xbd846b)
    			(*harnessTest).RunTestCase: testCase.test(net, h)
    		/home/travis/gopath/src/github.com/lightningnetwork/lnd/lnd_test.go:12180 (0xc3646a)
    			TestLightningNetworkDaemon.func3: ht.RunTestCase(testCase, lndHarness)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/testing/testing.go:746 (0x4f6aa0)
    			tRunner: fn(t)
    		/home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337 (0x45ecf1)
    			goexit: BYTE	$0x90	// NOP
FAIL
exit status 1
FAIL	github.com/lightningnetwork/lnd	116.860s
make: *** [itest] Error 1
```

**Comment by halseth** [comment]
@tailnode There are some known flakes on master currently, so don't worry about that for a doc change like this :)

**Comment by tailnode** [comment]
@halseth thank you : )

**Comment by tailnode** [comment]
@halseth Hi, sorry to bother you, looks like the pr need one more review. Should I find someone to review the pr?
Thanks again.

**Comment by halseth** [comment]
@tailnode Hi, no worries, I'm on it! :)

**Pull request merged**
