### PR TITLE
lnwallet: skip `testmempoolaccept` when the backend version is too low

### PR DESCRIPTION
**Pull request by yyforyongyu**
Depends on:
- https://github.com/btcsuite/btcd/pull/2125
- https://github.com/btcsuite/btcwallet/pull/910

### CODE REVIEW

**Review by Roasbeef — COMMENTED** [review]
Looks good, can land after the `btcd` and `btcwallet` deps are meged.

**Review by saubyk — APPROVED** [review]
Ack

**Comment by guggero** [comment]
Need to remove the replace directives in `go.mod`.

**Review by Roasbeef — APPROVED** [review]
LGTM 🧚🏽

**Pull request merged**
