### PR TITLE
Alphabetize lnd and lncli --help output

### PR DESCRIPTION
**Pull request by murrayn**
Current `--help` output for `lnd `and `lncli ` is seemingly random. This change organizes the output alphabetically.

### CODE REVIEW

**Comment by halseth** [comment]
Thanks for the PR! However, the fields are _kinda_ logically sorted already, or by a significantly biased random generator 😛 

So this is not needed IMO.

**Comment by murrayn** [comment]
Just to make it easier to visualize these changes, here are the `lncli --help` [before](https://0bin.net/paste/-MOSQaQUIOabBrPv#hS8EJeXOJS82UEaOm6IeAjjT31bLTv31IcrRXx+g1G2) and [after](https://0bin.net/paste/y7y3j1LhH61-htEp#Tb1+qfTo+5aNYH4GZJP2rnFmsrPA2-iIwi2TS6+zvcA), and the `lnd --help` [before](https://0bin.net/paste/Tr79cbFcNpAFLMFL#NdKBVpeYaISb2lgh0jZgtdoc7uXa4bdCtqfbYjcCldd) and [after](https://0bin.net/paste/tQ+yZadvU2fMR9cd#LBUhYaQDkIK64uvZXYcw1ajeoxtTblYmR9juX++oMyY).

**Comment by guggero** [comment]
Needs a rebase!
I'm personally against reordering the config flags because in the code they're grouped somewhat logically and that would be lost by sorting. I'd be okay with the `lncli` part though.

**Comment by Roasbeef** [comment]
Closing due to inactivity.

**Pull request closed without merging**
