### PR TITLE
lnd: adds NOT_FOUND status code for LookupInvoice

### PR DESCRIPTION
**Pull request by priyanshiiit**
**Fixes** #5510 

#### Pull Request Checklist

- [x] All changes are Go version 1.15 compliant
- [ ] Your PR passes all CI checks. If a check cannot be passed for a justifiable reason, that reason must be stated in the commit message and PR description.
- [x] If this is your first time contributing, we recommend you read the [Code Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
   - [x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
   - [x] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
- [ ] For new code: Code is accompanied by tests which exercise both the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: If possible, code is accompanied by new tests which trigger the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and logging level
- [ ] For code and documentation: lines are wrapped at 80 characters (the tab character should be counted as 8 characters, not 4, as some IDEs do per default)
- [x] A description of your changes [should be added to running the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes) for the milestone your change will land in.

### CODE REVIEW

**Review by guggero — COMMENTED** [review]
Nice, thanks for the PR!

Just a small nit: because the package is the root package, you might use `rpcserver: ` as the commit message's prefix.
Also you should add an entry (and your name) to the 0.14.0 release notes.

Other than that this looks good to me :tada:

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Review by yyforyongyu — APPROVED** [review]
LGTM⚡️

**Comment by guggero** [comment]
Needs a rebase.

**Comment by guggero** [comment]
You should do a [rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) instead of merging to preserve a clean git history.

**Pull request merged**
