### PR TITLE
kvdb: embedded postgres upgrade to allow setting a custom `max_connections` config value

### PR DESCRIPTION
**Pull request by bhandras**
## Change Description
This PR updates the embedded postgres dependency in the `kvdb` package to the latest tagged version (v1.25.0). This new version allows for setting the `max_connection` config value when starting the underlying Postgres instance. We parallelize some DB tests in https://github.com/lightningnetwork/lnd/pull/8100 which exhausts the connection limits so this PR is a pre-requirement for that.

### CODE REVIEW

**Review by positiveblue — APPROVED** [review]
LGTM

Will we hit the limit any time soon? If I am not confused embedded Postgres runs each test in its own database inside the same Postgres. 

I guess the assumption here is that we will never run >200 tests using the DB concurrently?

**Comment by bhandras** [comment]
> LGTM
> 
> Will we hit the limit any time soon? If I am not confused embedded Postgres runs each test in its own database inside the same Postgres.
> 
> I guess the assumption here is that we will never run >200 tests using the DB concurrently?

Thanks for the review Jordi! :)

I think we'll probably just go lower from here as we migrate away from `kvdb`. The default limits used to work as we didn't have as much concurrency before moving out the invoice update tests from `channeldb` to the `invoices` package. Over time as more and more db code migrates to `sqldb` we'll rely on the embedded Postgres less and less.

**Review by yyforyongyu — APPROVED** [review]
LGTM 🐦

**Review by saubyk — APPROVED** [review]
Ack

**Pull request merged**
