### PR TITLE
docs: fix typo in watchtower document and code comment

### PR DESCRIPTION
**Pull request by nayuta-ueno**
## Change Description
fix document / comment typo

## Steps to Test
N/A

### Testing
N/A

### Code Style and Documentation
N/A

### CODE REVIEW

**Review by guggero — COMMENTED** [review]
Thanks for the fixes. Can you please update the commit message according to the contribution guidelines?

**Comment by nayuta-ueno** [comment]
Thank you for your review.
I update commit comment.

**Review by guggero — APPROVED** [review]

**Review by yyforyongyu — APPROVED** [review]
LGTM👍 You may also want to add a `[skip ci]` to the end of your commit message.

**Comment by nayuta-ueno** [comment]
Thank you for your review!

> There is a change description in the release note, or [skip ci] in the commit message for small changes.

I had not read this...
comment updated.

**Pull request merged**
