### PR TITLE
build: update to latest version of neutrino

### LINKED ISSUE #5130: Lnd with Neutrino is not broadcasting on-chain transaction to the bitcoin network
### Background

Hi, I'm not sure if this issue should be opened in the neutrino project or here.

I am having some trouble sending on-chain transactions, seemingly they're never published/relayed.  
This is with lnd 0.12.1 using Neutrino and connecting to a bitcoind 0.21.0 node serving compact filters.

Both `SendCoins` and `OpenChannel` seems to be affected by this.

On the bitcoind side I tried putting mempool debug logging on, but no transaction is ever received.

On the lnd side I see nothing unusual:
```
2021-03-20 19:13:08.043 [INF] RPCS: [sendcoins] addr=tb1qyvugphjf6wfuzuqvwf2sl20gtxpa46k9af0zcx, amt=0.0005 BTC, sat/kw=12500, min_confs=1, send_all=false
2021-03-20 19:13:08.086 [INF] LNWL: Inserting unconfirmed transaction 516e19659f516dc830ab45da3c8e31fe2c056509a56039906d2ef115c907733d
2021-03-20 19:13:08.632 [INF] RPCS: [sendcoins] spend generated txid: 516e19659f516dc830ab45da3c8e31fe2c056509a56039906d2ef115c907733d
```

The configuration is nothing unusual AFAICT, on the bitcoind side (omitted comments etc to keep it small):

```
txindex=1

zmqpubrawblock=tcp://127.0.0.1:28334
zmqpubrawtx=tcp://127.0.0.1:29335

blockfilterindex=1
peerblockfilters=1

loglevel=debug
category=mempool
debug=mempool

testnet=1

listen=1

rpcuser=[redacted]
rpcpassword=[redacted]

rpcport=8332

[test]
port=18333
rpcport=18332
rpcbind=[redacted]
```

On the lnd side, [see here](https://github.com/hsjoberg/blixt-wallet/blob/master/src/state/index.ts#L263).

### Your environment

* lnd 0.12.1 with Neutrino
* bitcoind 0.21.0 as the Compact Filter server
* Mostly tested on my mobile wallet (Gomobile Android/iOS), but I confirmed it's happening on normal desktop MacOS as well, which is why I am choosing to open the issue

### Steps to reproduce

* Set up a bitcoind 0.21.0 node serving compact filters.
* Hook up lnd+neutrino with `neutrino.connect=<bitcoind node>`
* Send coins to lnd's internal wallet
* Spend these coins
* The transaction generated from lnd/btcwallet is seemingly never published (doesn't appear on block explorers etc). This applies to both mainnet and testnet. On mainnet I double-checked `bitcoin-cli testmempoolaccept ...` on the bitcoind peer to make sure the transaction valid and has enough fees.

### Expected behaviour

On-chain transactions created by lnd/btcwallet should relayed to the Neutrino peer. 

### Actual behaviour

Lnd/btcwallet seemingly never relays on-chain transactions to the Neutrino peer.

---

EDIT: Fixed lnd 0.20.1 -> 0.12.1...

### PR DESCRIPTION
**Pull request by hsjoberg**
This PR updates neutrino to the latest version.
This is to deal with on-chain transaction issues, where in certain
situations the transaction wouldn't be broadcasted #5130.

Fixes #5130.

### CODE REVIEW

**Review by wpaulino — APPROVED** [review]

**Review by halseth — APPROVED** [review]

**Comment by halseth** [comment]
Looks like itests are failing reliably no? Possible some timing issue becase of the change.

**Comment by hsjoberg** [comment]
@halseth Yeah it seems to be constantly failing (on 22-of-75/neutrino/single-hop_send_to_route/regular_main_stream)...

**Comment by wpaulino** [comment]
@hsjoberg would you like to try addressing it? I can take a closer look otherwise.

**Comment by hsjoberg** [comment]
@wpaulino I would greatly appreciate any help here. I don't feel confident (yet) to look at these things.

**Comment by Roasbeef** [comment]
@wpaulino we can also use the PR as an opportunity to include this and add a config option for the new value: https://github.com/lightninglabs/neutrino/pull/194

**Comment by wpaulino** [comment]
Closing in favor of https://github.com/lightningnetwork/lnd/pull/5257. Thanks for getting this started @hsjoberg!

**Pull request closed without merging**
