### PR TITLE
replace freenode with libera

### PR DESCRIPTION
**Pull request by ndalliard**

### CODE REVIEW

**Comment by Roasbeef** [comment]
Thanks for this PR! I don't actually have op/mod or anything on that IRC channel (I didn't create it), will hold off on merging this till we sort out the ownership of the channel.

**Comment by crabbedhaloablution** [comment]
If you're in need of a pointer, the process is described here:
https://libera.chat/chanreg

**Comment by Roasbeef** [comment]
Ok, sent them an email to claim the channel, waiting for a response now.

**Comment by Roasbeef** [comment]
No response from their admins yet, but we're fully moved over at this point (GH IRC bot included!).

**Pull request merged**
