### PR TITLE
lnrpc: deprecate route hop channel capacity field

### PR DESCRIPTION
**Pull request by joostjager**
This field requires database queries for every message in the payment update stream. It was only present for backwards compatibility. By deprecating it now, the option is created to remove it in 0.14.

### CODE REVIEW

**Review by guggero — APPROVED** [review]
LGTM :heavy_check_mark:

**Review by yyforyongyu — APPROVED** [review]
LGTM

**Comment by joostjager** [comment]
@guggero @yyforyongyu don't you want to merge this for 0.13?

**Comment by guggero** [comment]
@Roasbeef, @cfromknecht should we include this for RC3?

**Pull request merged**
