### PR TITLE
Create separate go module for proto files

### LINKED ISSUE #5402: Create separate go module for proto files
Currently the proto files are part of the main lnd module. That means that if an application just needs to reference the proto files, it will inherit all the lnd dependencies such as etcd. This can sometimes cause difficult to resolve conflicts if the application uses the same dependencies but different versions.

One option may be to put the proto files in their own module, so that linking against it can remain very light.

### PR DESCRIPTION
**Pull request by l0k18**
Redoing this due to eventual merge conflict after branch got way out of date.

resolves #5402

Proceeding carefully with one server at a time per commit.

### CODE REVIEW

**Comment by guggero** [comment]
Thanks for picking this up again. Could you perhaps run some of the checks (like `make lint` and `make build` and `make unit pkg=... case=_NONE_` [compile unit tests only, without running them]) locally to not flood our GitHub Actions with tasks? Every push triggers a full run of the CI/CD pipeline.

**Comment by guggero** [comment]
I mean you can create commit by commit, just not push every time you create a new commit. But instead only push everything once you have the full list of commits ready.

**Comment by l0k18** [comment]
@guggero by the time I finished it there was another 5 commits and another merge conflict I had to fix. This current change set passes the basic things you specified, running full `make check` but really there should be no issues, it was just moving things around and fixing references.

**Comment by Roasbeef** [comment]
What's the goal here? Each sub-server was _already_ in its own folder? Or did you run into issues with the prior attempt with the compiled protos living in the same folder?

**Comment by l0k18** [comment]
> What's the goal here? Each sub-server was _already_ in its own folder? Or did you run into issues with the prior attempt with the compiled protos living in the same folder?

The point of the issue was to allow import of the protobuf generated code without pulling in and compiling anything from the rest of LND.

I forgot to add the `go.mod` in `lnrpc` as was discussed previously by @guggero, though I don't think it's necessary for the goal of avoiding unnecessary compilation by consuming modules.

The layout of this lnrpc and the protobufs is not as per recommended for use with protobuf generated code. In fact, usually the protos go in one place, the generated code goes in separate modules each, and consuming code is separate. So for my 2 cents it's not ideal yet either.

What do you think?

**Comment by Roasbeef** [comment]
So if all these new packages _don't_ have a `go.mod` (making it a _module_) then it won't address the dependnacy/compilation issue. AFAICT, in order to address this, both the RPC sub-servers and the generated code need to live in either the same (per sub-server), or distinct modules. 

As an example check out this module: https://github.com/lightningnetwork/lnd/blob/master/queue/go.mod. It has no deps, so someone can import it and not bring it all of lnd. If it didn't have a `go.mod`, then they'd also depend on everything that lnd depended on.

**Comment by l0k18** [comment]
> So if all these new packages _don't_ have a `go.mod` (making it a _module_) then it won't address the dependnacy/compilation issue. AFAICT, in order to address this, both the RPC sub-servers and the generated code need to live in either the same (per sub-server), or distinct modules.
> 
> As an example check out this module: https://github.com/lightningnetwork/lnd/blob/master/queue/go.mod. It has no deps, so someone can import it and not bring it all of lnd. If it didn't have a `go.mod`, then they'd also depend on everything that lnd depended on.

As the code stands prior to this change, if you import `lnrpc/whateverrpc` it will include everything in, for example https://github.com/lightningnetwork/lnd/blob/master/lnrpc/chainrpc/chainnotifier_server.go#L16 

ie:

```go
	"github.com/lightningnetwork/lnd/chainntnfs"
	"github.com/lightningnetwork/lnd/lnrpc"
	"github.com/lightningnetwork/lnd/macaroons"
```

But chainnotifier.pb.go https://github.com/lightningnetwork/lnd/blob/master/lnrpc/chainrpc/chainnotifier.pb.go#L9 does not import anything from lnd

https://github.com/lightningnetwork/lnd/pull/6835/commits/ef2150d1b2f007b4d77e08067a21f5992a21c835#diff-e3cd5381b1670fcfc2607787f24e9ff9bdc88f4e3f34cb985bab655480303322

I forgot to add the module. You can see now it does not induce the import of anything from lnd that is not local to the module path:

```go
module github.com/lightningnetwork/lnd/lnrpc

go 1.18

require (
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.11.2
	google.golang.org/grpc v1.48.0
	google.golang.org/protobuf v1.28.1
)

require (
	github.com/golang/protobuf v1.5.2 // indirect
	golang.org/x/net v0.0.0-20220624214902-1bab6f366d9e // indirect
	golang.org/x/sys v0.0.0-20220610221304-9f5ed59c137d // indirect
	golang.org/x/text v0.3.7 // indirect
	google.golang.org/genproto v0.0.0-20220805133916-01dd62135a58 // indirect
)
```

**Comment by l0k18** [comment]
There needs to be a replace directive in the root go.mod to account for this.

**Comment by l0k18** [comment]
Further, due to differences between 1.16 and 1.17 there is another update to the root go.mod and go.sum to account for this.

**Comment by l0k18** [comment]
Sorry for the confusion. I already did all this before in the previous PR but ten tons of PRs got merged up and it caused a merge conflict. Thus I replayed this all today to fix the problem. Everything should be correct now, unless yet more merge conflicts have occurred due to changes in the RPC servers in the last 9 hours.

**Comment by l0k18** [comment]
I've been trying to get this merged now almost going on a month. I'm about to give up.

**Comment by l0k18** [comment]
I give up.

**Pull request closed without merging**
