### PR TITLE
logging: unify logging of `lnwire.ShortChannelID`

### PR DESCRIPTION
**Pull request by maurycy**
I've decided to use `String()` because it's more descriptive, flexible, and `ToUint64()` is used as a key.

Simple `grep` for `ToUint64()`, with each file manually reviewed, indicates that `ToUint64()` is not used for logging now.

ref #1252

### CODE REVIEW

**Comment by Roasbeef** [comment]
We may also want to update `getchaninfo` to accept and parse the new default format.

**Comment by maurycy** [comment]
@Roasbeef Both? Or only the new format?

**Comment by halseth** [comment]
@maurycy Ideally both should be supported :)

**Comment by halseth** [comment]
Must be rebased and squashed to one commit.

**Comment by halseth** [comment]
Needs a rebase and squash to a single commit! :)

**Comment by halseth** [comment]
Could go together with the change to display as `123x456x99`

**Comment by Roasbeef** [comment]
Superseded by #2432

**Pull request closed without merging**
