### PR TITLE
contractcourt+utxonursery: create stray output pool to be incrementally emptied

### PR DESCRIPTION
**Pull request by vapopov**
### Original Description:

Currently, within the daemon, due to varying output sizes, and the dynamic fee climate on the main chain, it may be the case that we're unable to sweep an output at the desired fee rate. This can happen when sweeping various outputs in the contractcourt package, breached outputs by the breachArbiter, and also time-locked outputs handled by the utxoNursery. At this point, these will be left on the chain as sort of "dust" output. Ideally, we should attempt to either drop the fee rate, or pool these outputs into a set, to be later spent.

Closes: https://github.com/lightningnetwork/lnd/issues/1184

### CODE REVIEW

**Comment by Roasbeef** [comment]
Ping!

**Comment by vapopov** [comment]
@Roasbeef hi, I'm working on it now

**Comment by wpaulino** [comment]
Any progress on this?

**Comment by vapopov** [comment]
@cfromknecht Could you please take a look on current PR, to verify that I'm on right path. I decided a bit change steps to complete from original ticket

**Comment by vapopov** [comment]
cc @Roasbeef

**Comment by Roasbeef** [comment]
It won't be making our next release, so in the short term this PR is de-prioritized a bit in favor of focusing review on the PR's that are blocking 0.5. Once we ship that though we can re-prio this and see which release it can land in. Thanks for all the work on this!

**Comment by vapopov** [comment]
@Roasbeef @cfromknecht let me know when you have time to validate this implementation until it has no merge conflicts and I able to finish it

**Pull request closed without merging**
