### PR TITLE
GitHub: update vendored release script

### PR DESCRIPTION
**Pull request by guggero**
Depends on https://github.com/lightninglabs/gh-actions/pull/2.

This fixes the problem where releases wouldn't be created anymore due to the GitHub Action for creating the draft release being out of date.

I've confirmed this works with the following run in my fork of the repository: https://github.com/guggero/lnd/actions/runs/10058716669/job/27802410976

### CODE REVIEW

**Review by yyforyongyu — APPROVED** [review]
nice🦾

**Comment by guggero** [comment]
@ProofOfKeags I also pushed a tag `fn/v1.2.0` and added a commit to bump. I assume that version is safe to use, right?

This will fix the Goveralls run, for example: https://github.com/lightningnetwork/lnd/actions/runs/10062995488/job/27816765240?pr=8892 (a file was deleted in the `fn` directory but the Go module that's being pulled in still has it, which confuses Goveralls)

**Review by Roasbeef — APPROVED** [review]
LGTM 🍁

**Review by ProofOfKeags — APPROVED** [review]
🫡

**Comment by Roasbeef** [comment]
Merged the dep update here (see ref'd commit hash): https://github.com/lightninglabs/gh-actions/pull/2

**Review by Webbdlee74 — APPROVED** [review]

**Pull request merged**
