### PR TITLE
build: update to version of btcd with wire parsing bug fix

### PR DESCRIPTION
**Pull request by Roasbeef**
Fixes https://github.com/lightningnetwork/lnd/issues/7002

### CODE REVIEW

**Review by sangaman — APPROVED** [review]
Just pulled this branch and compiled off of it and tried running lnd on testnet, my `synced_to_chain` went from `false` to `true` and I'm able to send on-chain transactions.

**Comment by Roasbeef** [comment]
@sangaman thanks for testing things out! This PR can be applied for those already on `master`. For those that are running 0.15.0 or 0.15.1, we'll be cherry picking this PR onto a new 0.15.2 release (branched off from 0.15.1) which'll backport the fix.

**Comment by kaloudis** [comment]
tACK

my node is back up

**Comment by pinheadmz** [comment]
tACK, working here as well on arm with bitcoind full node backend

**Comment by Roasbeef** [comment]
Ok, the btcd version bump PR has landed, with a corresponding release there: https://github.com/btcsuite/btcd/releases/tag/v0.23.2

Now I can update this PR to point to that release rather than my fork.

**Review by kajoseph — APPROVED** [review]
tACK with:
- testnet on `Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- mainnet on `Ubuntu 20.04 LTS on Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- mainnet on `Linux 5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022 aarch64 GNU/Linux`

**Comment by pcharest** [comment]
tACK on windows 10

**Comment by seth586** [comment]
tACK `FreeBSD 13.1-RELEASE-p1 amd64`

**Comment by okeygo** [comment]
Patch applied, working fine now.
```
2022-10-10 09:03:32.280 [INF] UTXN: Attempting to graduate height=757997: num_kids=0, num_babies=0
2022-10-10 09:03:32.749 [INF] CRTR: Block 00000000000000000004d70d2fb15f406887046220cea70f69225c451251d998 (height=758000) closed 1 channels
2022-10-10 09:03:32.749 [INF] CRTR: Pruning channel graph using block 000000000000000000076b936c0265aa70ba1d9aca08e41f833ce15e8a129f09 (height=758001)
2022-10-10 09:03:32.805 [INF] NTFN: New block: height=757998, sha=000000000000000000058c270b8230d767869edc757ba964be8a7456123aab20
2022-10-10 09:03:32.805 [INF] UTXN: Attempting to graduate height=757998: num_kids=0, num_babies=0
2022-10-10 09:03:33.200 [INF] CRTR: Block 000000000000000000076b936c0265aa70ba1d9aca08e41f833ce15e8a129f09 (height=758001) closed 1 channels
2022-10-10 09:03:33.272 [INF] NTFN: New block: height=757999, sha=00000000000000000002189e962a78e1cdbfc70bdb7282615413bc499b605078
2022-10-10 09:03:33.273 [INF] UTXN: Attempting to graduate height=757999: num_kids=0, num_babies=0
2022-10-10 09:03:33.630 [INF] NTFN: New block: height=758000, sha=00000000000000000004d70d2fb15f406887046220cea70f69225c451251d998
2022-10-10 09:03:33.630 [INF] UTXN: Attempting to graduate height=758000: num_kids=0, num_babies=0
2022-10-10 09:03:34.022 [INF] NTFN: New block: height=758001, sha=000000000000000000076b936c0265aa70ba1d9aca08e41f833ce15e8a129f09
2022-10-10 09:03:34.022 [INF] UTXN: Attempting to graduate height=758001: num_kids=0, num_babies=0

```

**Comment by matiasSXchange** [comment]
Hi, I'm having problem with the new version and litecoin:

Log:
Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to subscribe for zmq block events: read tcp xxx.xxx.xxx.xxx:41508->xxx.xxx.xxx.xxx:28432: i/o timeout

getzmqnotifications on litecoin wallet (Version 1801100):
[
  {
    "type": "pubrawblock",
    "address": "tcp://*:28432",
    "hwm": 1000
  },
  {
    "type": "pubrawtx",
    "address": "tcp://*:28433",
    "hwm": 1000
  }
]

Any suggestions? Thanx in advance.

**Pull request merged**
