### PR TITLE
Makefile: move linter v2

### PR DESCRIPTION
**Pull request by cfromknecht**
Reported that old linter didn't behave the consistently on different machines, v2 seems to be more stable.

### CODE REVIEW

**Comment by halseth** [comment]
Getting 
```
 Fetching gometalinter.v1
go get -u gopkg.in/alecthomas/gometalinter.v2
go install -v gopkg.in/alecthomas/gometalinter.v2
 Linting source.
/Users/johan/golang/bin/gometalinter.v2 --install 1> /dev/null
can't load package: package 4d63.com/gochecknoinits: cannot find package "4d63.com/gochecknoinits" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/4d63.com/gochecknoinits (from $GOROOT)
	/Users/johan/golang/src/github.com/alecthomas/gometalinter/_linters/src/4d63.com/gochecknoinits (from $GOPATH)
can't load package: package 4d63.com/gochecknoglobals: cannot find package "4d63.com/gochecknoglobals" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/4d63.com/gochecknoglobals (from $GOROOT)
	/Users/johan/golang/src/github.com/alecthomas/gometalinter/_linters/src/4d63.com/gochecknoglobals (from $GOPATH)
WARNING: failed to install one or more linters: exit status 1 (installing individually)
can't load package: package 4d63.com/gochecknoinits: cannot find package "4d63.com/gochecknoinits" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/4d63.com/gochecknoinits (from $GOROOT)
	/Users/johan/golang/src/github.com/alecthomas/gometalinter/_linters/src/4d63.com/gochecknoinits (from $GOPATH)
WARNING: failed to install 4d63.com/gochecknoinits: exit status 1
can't load package: package 4d63.com/gochecknoglobals: cannot find package "4d63.com/gochecknoglobals" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/4d63.com/gochecknoglobals (from $GOROOT)
	/Users/johan/golang/src/github.com/alecthomas/gometalinter/_linters/src/4d63.com/gochecknoglobals (from $GOPATH)
WARNING: failed to install 4d63.com/gochecknoglobals: exit status 1
gometalinter.v2: error: failed to install the following linters: 4d63.com/gochecknoinits, 4d63.com/gochecknoglobals
make: *** [lint] Error 1
```
when running `make lint`

**Comment by cfromknecht** [comment]
That's weird, seemed to work fine for me when updating. Wondering if I should try pinning it to a specific commit? Or if the issue is deeper

**Comment by wpaulino** [comment]
@halseth I think I've seen this before due to `vim-go` also installing and setting up `gometalinter`. I'd recommend wiping `gometalinter` from your `$GOPATH` before running `make lint` again.

**Comment by halseth** [comment]
Got it working by variations of reinstalling go, wiping `gometalinter` and `_linters`. 

No changes after running `make lint` 👍

**Comment by cfromknecht** [comment]
changed order of `dep` and `lint` in travis builds, as the linter requires the deps to be be present. should be gtg, waiting on travis

**Pull request merged**
