### PR TITLE
sample-lnd.conf: remove duplicate setting and clean up section separators

### PR DESCRIPTION
**Pull request by xanoni**
973e87b remove extra whitespace and harmonizes the separators between config sections

2c92958 deletes a duplicate "nolisten=true" line + comment

### CODE REVIEW

**Comment by yyforyongyu** [comment]
Thanks for the PR! The commit messages need to be modified a bit, similar to what you've done in this [one](https://github.com/lightningnetwork/lnd/commit/dc7d79abc2beb89c5a3f35ea55a963cdec8dbb30).

**Comment by xanoni** [comment]
> Thanks for the PR! The commit messages need to be modified a bit, similar to what you've done in this [one](https://github.com/lightningnetwork/lnd/commit/dc7d79abc2beb89c5a3f35ea55a963cdec8dbb30).

Hi! Do you mean the "doc/sample-lnd.conf: " prefix before the message? I think someone did that for me, because in my local repo I don't see it. Sure, I can add that.

However, I see the `sample-lnd.conf` in the repo `root` folder, not in a `doc` subfolder. I see a `doc**s**` folder, though. Should my commit move the file to "docs", or keep it in the root?

**Comment by xanoni** [comment]
@yyforyongyu I created 2 versions of this PR. In this version here I don't move the file to `docs`. In https://github.com/lightningnetwork/lnd/pull/5451 I do move the file. Pick one of the 2 :)

**Review by guggero — APPROVED** [review]
LGTM, thanks!

I prefer this version over #5451. Makes it easier for people to find the example config.

**Review by yyforyongyu — APPROVED** [review]
LGTM👍 
Like @guggero mentioned I think this version is better. Thanks for the PRs!

**Pull request merged**
