### PR TITLE
fuzz/tlv: harnesses to test equality, encoding+decoding

### PR DESCRIPTION
**Pull request by Crypt-iQ**
Uncovered one OOM a while ago. They were up on my local github though.

Testing:
```
make fuzz-build pkg=tlv
make fuzz-run pkg=tlv
```

Commits:
- fix a false positive with the way the fuzzer would handle pubkeys.
- add fuzz tests that test decoding + encoding, assert equality, don't panic / oom
- modify Makefile and make/fuzz_flags.mk

### CODE REVIEW

**Comment by Roasbeef** [comment]
No movement on this in a few months, do we still want this for 0.12?

**Comment by Crypt-iQ** [comment]
@Roasbeef Ideally yeah, I removed it since the board was getting cluttered. I can clean up this PR.

**Comment by cfromknecht** [comment]
@Crypt-iQ change look good, needs a squash tho!

**Comment by Crypt-iQ** [comment]
Rebased+squashed. Updated the PR body with instructions how to test.  Would be curious to see if other folks can build/fuzz seamlessly @cfromknecht

**Comment by morehouse** [comment]
Sure, I'll add it to my list.

**Pull request closed without merging**
