### PR TITLE
rpc: Fix typo in OpenChannelRequest

### PR DESCRIPTION
**Pull request by stevenroose**
Discussed here: https://github.com/lightningnetwork/lnd/issues/687#issuecomment-373400452

### CODE REVIEW

**Comment by stevenroose** [comment]
@halseth Oh, that's a good point! Didn't think about that. If you checkout this branch and generate, is the output different?

Perhaps makes sense to have the gen file check version.
```
$ protoc --version
libprotoc 3.5.1
```

**Comment by halseth** [comment]
Hm, when I generate your branch, most of the changes are reverted. I have the same version of `protoc` as you, and just tried updating the other tools. Did you run the `gen_protos.sh` script?

**Comment by stevenroose** [comment]
Yes I did. That's weird. I guess protoc is not the important version, but `proto-gen-go` and the gRPC plugin (which I couldn't). I'm pretty sure I updated all of the generating dependencies (following the gRPC tutorial :p).

lnd is using the latest gPRC version, right?

**Comment by Roasbeef** [comment]
What version are you using? As it's just a doc typo, you shouldn't have needed to recompile the protos.

**Comment by stevenroose** [comment]
@Roasbeef well, the proto doc appears in the Swagger docs and Go docs as well.

As I said above, I'm using libprotoc 3.5.1 and both grpc plugins latest master.

**Comment by wilmerpaulino** [comment]
We actually don't use the latest master for gRPC when generating the proto definitions. See [here](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#Protobuf).

**Comment by stevenroose** [comment]
@wilmerpaulino  That documentation is really useful! However, when installing the exact same dependencies, I still get a tiny diff on master (see below). I'll update my PR anyway.

```diff
diff --git a/lnrpc/rpc.pb.go b/lnrpc/rpc.pb.go
index 5ed38eb4..1571654a 100644
--- a/lnrpc/rpc.pb.go
+++ b/lnrpc/rpc.pb.go
@@ -519,9 +519,7 @@ func (m *ChannelPoint) String() string            { return proto.CompactTextStri
 func (*ChannelPoint) ProtoMessage()               {}
 func (*ChannelPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }
 
-type isChannelPoint_FundingTxid interface {
-	isChannelPoint_FundingTxid()
-}
+type isChannelPoint_FundingTxid interface{ isChannelPoint_FundingTxid() }
 
 type ChannelPoint_FundingTxidBytes struct {
 	FundingTxidBytes []byte `protobuf:"bytes,1,opt,name=funding_txid_bytes,proto3,oneof"`
@@ -1558,9 +1556,7 @@ func (m *CloseStatusUpdate) String() string            { return proto.CompactTex
 func (*CloseStatusUpdate) ProtoMessage()               {}
 func (*CloseStatusUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }
 
-type isCloseStatusUpdate_Update interface {
-	isCloseStatusUpdate_Update()
-}
+type isCloseStatusUpdate_Update interface{ isCloseStatusUpdate_Update() }
 
 type CloseStatusUpdate_ClosePending struct {
 	ClosePending *PendingUpdate `protobuf:"bytes,1,opt,name=close_pending,oneof"`
@@ -1814,9 +1810,7 @@ func (m *OpenStatusUpdate) String() string            { return proto.CompactText
 func (*OpenStatusUpdate) ProtoMessage()               {}
 func (*OpenStatusUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }
 
-type isOpenStatusUpdate_Update interface {
-	isOpenStatusUpdate_Update()
-}
+type isOpenStatusUpdate_Update interface{ isOpenStatusUpdate_Update() }
 
 type OpenStatusUpdate_ChanPending struct {
 	ChanPending *PendingUpdate `protobuf:"bytes,1,opt,name=chan_pending,oneof"`
@@ -3714,9 +3708,7 @@ func (m *PolicyUpdateRequest) String() string            { return proto.CompactT
 func (*PolicyUpdateRequest) ProtoMessage()               {}
 func (*PolicyUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{92} }
 
-type isPolicyUpdateRequest_Scope interface {
-	isPolicyUpdateRequest_Scope()
-}
+type isPolicyUpdateRequest_Scope interface{ isPolicyUpdateRequest_Scope() }
 
 type PolicyUpdateRequest_Global struct {
 	Global bool `protobuf:"varint,1,opt,name=global,oneof"`
```

**Comment by stevenroose** [comment]
(Also, it's a tiny change, someone else can put a PR with the correct protobuf setup. Even though I would like to have the exact environment replicated for future use.)

**Comment by stevenroose** [comment]
Updated PR is a lot smaller.

**Pull request merged**
