### PR TITLE
[wip]: add get transaction rpc

### LINKED ISSUE #7323: [feature]: add get transaction rpc
**Is your feature request related to a problem? Please describe.**

There should be a get transaction rpc instead of having to use the get transactions rpc and find the specific transaction you want. 

My node has done over 1k transactions and it would be nice to not have to load it all into memory and find something myself when lnd could easily do it.

### PR DESCRIPTION
**Pull request by gnapoli23**
Fixes #7323 

Adds `get transaction` rpc call to get info about a specific transaction related to the wallet.
This is a draft (I'm a newcomer), I would like to know if I'm on the right track or not.

### CODE REVIEW

**Comment by positiveblue** [comment]
Hello @gnapoli23, I'm glad you are taking a look into this :tada: 


I see you are creating a new rpc endpoint + cmd just for this. I wonder if we could rather extend what we already have. It can be worth to discuss what possibilities we have here and their trade off before committing to one of them

There are two things to take into account:

a) The rpc interface and server implementation
b) cli command that calls that rpc endpoint

For a) we could could reuse the current [GetTransactionsRequest](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.proto#L723) used in `listchaintxns`. We could add a new field `repeat string tx_hash_list=4`. The [`GetTransactions`](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.proto#L45) methods should then be updated to ensure that:

- If `tx_hash_list` is empty we behave like always. Using the [same logic](https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L5711) that is used right now.
- If `tx_hash_list` is not empty: we need to call our bitcoin backend to get info about each tx using its hash. The good news is that there is an RPC endpoint for that: [`GetTransaction`](https://developer.bitcoin.org/reference/rpc/gettransaction.html). If the other filters are set we should fetch them by hash but ensure that they are filtered out if do not match them.


For b) we use `urfave` so we can add a `cli.StringSliceFlag` so we can repeat the argument with multiple values and we would be able to set the list in the rpc.

```
lncli listchaintxns --tx_hash="hash_1" --tx_hash="hash_2" ...
```

If we follow this route, we would not only solve this issue, but give an rpc interface to fetch multiple txs in one call, with multiple filters and even be able to fetch txs that are not ours.
    
**NOTE**: The `GetTransactionRequest` is also used in the [SubscribeTransactions](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/lightning.proto#L80) method. We would have to update its logic too or at least check that `tx_hash_list` is empty.

**NOTE 2**: To use the `GetTransaction` endpoint the bitcoin backend needs to be [compiled with wallet support](https://developer.bitcoin.org/reference/rpc/#wallet-rpcs), but if we are using it for LND I think it HAS to have it anyway.

**NOTE 3**: I guess `--txindex` is advised here.

**Comment by ErikEk** [comment]
@gnapoli23, @positiveblue This is my code so far (https://github.com/lightningnetwork/lnd/pull/7381). Please go ahead copy whatever you need. There are still things to be done. Fix the hash conversion, calculate the correct transaction amount and list our inputs. Maybe add tests.

**Comment by ErikEk** [comment]
@gnapoli23 Take a look at this pr. https://github.com/btcsuite/btcwallet/pull/779/commits/f6b5524fb88273179a3ca3104b247beb694bd5e8
Might give you some insights of the btcwallet package.

**Comment by gnapoli23** [comment]
@ErikEk Thanks sir for sharing your code and for your willingness to help, really appreciate it.
@positiveblue Thanks for the explanation and the starting guidance, I reverted the draft commit and will work as suggested.
Btw, I was thinking also another thing. Can this kind of setting be useful?
```
message GetTransactionsByRangeRequest {
    int32 start_height = 1;
    int32 end_height = 2;
}

message GetTransactionsByHashesRequest {
    repeated string tx_hash_list = 1;
}

message GetTransactionsRequest {

    oneof search_criteria {
        GetTransactionsByHashesRequest tx_height_range = 1;
        GetTransactionsByHashesRequest tx_hashes = 2;
    }

    string account = 3;

}
```
This is just something i was thinking during looking again at protobuf definition, thought it could be another way to separate the search criteria. If not needed, I will go straight as suggested! Thanks.

**Comment by ErikEk** [comment]
> @ErikEk Thanks sir for sharing your code and for your willingness to help, really appreciate it. @positiveblue Thanks for the explanation and the starting guidance, I reverted the draft commit and will work as suggested. Btw, I was thinking also another thing. Can this kind of setting be useful?
> 
> ```
> message GetTransactionsByRangeRequest {
>     int32 start_height = 1;
>     int32 end_height = 2;
> }
> 
> message GetTransactionsByHashesRequest {
>     repeated string tx_hash_list = 1;
> }
> 
> message GetTransactionsRequest {
> 
>     oneof search_criteria {
>         GetTransactionsByHashesRequest tx_height_range = 1;
>         GetTransactionsByHashesRequest tx_hashes = 2;
>     }
> 
>     string account = 3;
> 
> }
> ```
> 
> This is just something i was thinking during looking again at protobuf definition, thought it could be another way to separate the search criteria. If not needed, I will go straight as suggested! Thanks.

@gnapoli23 That would break the api since we assume the message index 1 and 2 to be start and end height. And I think GetTransactions shouldn't require any parameters to be set.

**Comment by gnapoli23** [comment]
@ErikEk yes I guess so.
@positiveblue I updated the code as suggested by adding `tx_hash` as a string slice in `lncli listchaintxns` cmd and relative refs to `GetTransactions`/`ListTransactionDetails`. In the btcwallet implementation I left a `// TODO` comment to update the logic: how should we handle it? Which parameter has highest priority? I guess the height limits, so I would like to understand if `tx_hash_list` should match somehow with them or should follow a separate logic.

**Comment by ErikEk** [comment]
@gnapoli23 How is going? Do you need help finishing this. I don't mind completing it if you want.

**Comment by gnapoli23** [comment]
> @gnapoli23 How is going? Do you need help finishing this. I don't mind completing it if you have a busy schedule.

Hi @ErikEk and thanks for contacting me, I have been OOO in previous weeks so I couldn't work on it. I just rebased on top of latest commit, and I'll check where I was before being unavailable. I will try to move forward and if I run into any problems I will ping you. Thanks a lot for you support, really appreciate 🙏🏻

**Comment by guggero** [comment]
Replaced by https://github.com/lightningnetwork/lnd/pull/7654.

**Pull request closed without merging**
