### PR TITLE
Delay link capacity check vs htlc.Amount to the link level.

### PR DESCRIPTION
**Pull request by offerm**

### CODE REVIEW

**Comment by Roasbeef** [comment]
As is now, this'll provide even _less_ information to _locally_ sourced payments that before. The reported case can only arise when users attempt to send over _most_ of their available bandwidth, not accounting for pending HTLCs. 

The logic here will also favor _always_ sending to the link with the most available bandwidth, which is a change from the prior non-deterministic selection.

**Comment by offerm** [comment]
@Roasbeef Agree with both comments. My suggestion is to remove the capacity check from here and let it be done at the link level **assuming that the error message there will be enhanced** (for a locally sourced payments). I will check to see if I can do it.

For the selection of the link - the PR selects the link having the **maximum bandwidth**. Before the PR it was selecting the last link having enough bandwidth.  I can restore the selection as it was, however, I'm not sure why we shouldn't select the link with highest probability of success. 
Actually, we should prefer the link having the maximum local_capacity. Don't you agree?

**Comment by Roasbeef** [comment]
> My suggestion is to remove the capacity check from here and let it be done at the link level assuming that the error message there will be enhanced (for a locally sourced payments).

This has performance implications, as we need to be able to reliably forward these _potential_ payments to the link. Rather than just cancel things quickly in the switch, we'll end up with more forwarding packages on disk, and also more unnecessary circuits. 

I don't think you're targeting the correct change here. The new title of the initial issue is just to _improve_ the error message for _locally_ sourced payments. Fundamentally, there _will_ be some slippage, but that's fine as long as we can give the user a better error to adjust their strategy. 

> Actually, we should prefer the link having the maximum local_capacity. Don't you agree?

Why's this better? Before we would pseudorandomly select a link with enough bandwidth (map iteration in Go is randomized), with this we'd target the same link repeatedly. The former introduces a degree of load balancing.

**Comment by Roasbeef** [comment]
Closing due to inactivity, also see the recent-ish changes w.r.t strict forwarding.

**Pull request closed without merging**
