### PR TITLE
Allow CORS

### PR DESCRIPTION
**Pull request by phillyfan1138**
This PR allows CORS IP addresses to be entered in the lnd.conf similar to rpclisten and restlisten.  However, the protocol (HTTP/HTTPS) needs to be specified.

### CODE REVIEW

**Comment by phillyfan1138** [comment]
Isn't that was the Gopkg.lock is for?

**Comment by renepickhardt** [comment]
sure the gopgk.lock is fixing the dependancy to a certain commit. But what happends if another developer also uses this dependancy later and decides to change to a newer version of it. this version might break your code but we won't see that since there is not tests included. I guess in the setting of CORS this is unlikely since only api changes would occure and thouse would be seen at compiletime I guess so maybe I was a little bit too cautios. Other oppinions?

**Comment by phillyfan1138** [comment]
I can certainly add test cases for the version.  Are there any other such tests that I can copy the style from?  I'm not as familiar with go.

**Comment by Roasbeef** [comment]
Will be done in https://github.com/lightningnetwork/lnd/pull/4141

**Pull request closed without merging**
