### PR TITLE
Subtract funding tx fee from requested channel capacity

### PR DESCRIPTION
**Pull request by simonhorlick**
In this PR we address a minor usability issue when opening a channel that uses the entire remaining wallet balance. Currently if a user wants to spend their entire wallet balance on channels they would issue a "lncli walletbalance" and use the total_balance as the local_amt in "lncli openchannel", however this will error out as openchannel requires the wallet to have enough to cover the fee for the funding transaction as well as the local_amt for the channel. This PR causes the fee for the funding transaction to be subtracted from the local_amt passed to openchannel, allowing users to pass the entire wallet balance to openchannel. A similar issue occurs when running autopilot with autopilot.allocation=1.0 as autopilot will attempt to call openchannel without leaving enough room for the fee and having that repeatedly fail.

This is currently WIP as I haven't yet updated the tests to reflect any of the changed functionality. But more importantly I would like feedback on whether this implementation makes sense, or if there's a better way to architect it. Finally, this should all probably exist behind a flag as otherwise it would be a surprising change in the default behaviour.

Related issues: #619 #986

### CODE REVIEW

**Comment by Roasbeef** [comment]
How's this related to either of those issues? Can you expand the PR description with the rationale for this change?

**Comment by simonhorlick** [comment]
Sure, I've updated the description with a proper rationale.

**Comment by AndrewSamokhvalov** [comment]
@simonhorlick Correct me if I am wrong, but is seems that with this change we will be able to calculate `funding_fee` as `funding_fee = capacity - (local_amt + remote_amt) - commit_fee` which is good, but probably you had plans to add `funding_fee` field in RPC responses of `pendingchannels` and  `listchannels` in this PR as well?

**Comment by simonhorlick** [comment]
@AndrewSamokhvalov I didn't plan on exposing the actual chosen fee in the rpc, that might be good as a separate improvement though.

**Comment by simonhorlick** [comment]
Closing for now as I don't have time to work on this.

**Pull request closed without merging**
