### PR TITLE
docs+Makefile: update fuzz.md to explain new build/run process

### PR DESCRIPTION
**Pull request by Crypt-iQ**
Updates documentation and Makefile.  While doing this, I found that `make fuzz-build` would break.  This PR fixes this by also installing `go-fuzz/go-fuzz-dep`. Would greatly appreciate if others could verify that these build steps work for them!

### CODE REVIEW

**Review by yyforyongyu — COMMENTED** [review]
Tried to run it locally, got the following error,
```make fuzz-build pkg=lnwire
Fetching go-fuzz-dep package
go get -v github.com/dvyukov/go-fuzz/go-fuzz-dep@b1f3d6f
 Creating fuzz harnesses for packages 'lnwire'.
scripts/fuzz.sh build "lnwire"
Building fuzz packages
Building zip file for lnwire/accept_channel
.../lnd/fuzz/lnwire/accept_channel.go:33:27: emptyMsg.MaxPayloadLength undefined (type lnwire.AcceptChannel has no field or method MaxPayloadLength)
.../lnd/fuzz/lnwire/fuzz_utils.go:36:27: emptyMsg.MaxPayloadLength undefined (type lnwire.Message has no field or method MaxPayloadLength)
.../lnd/fuzz/lnwire/node_announcement.go:33:27: emptyMsg.MaxPayloadLength undefined (type lnwire.NodeAnnouncement has no field or method MaxPayloadLength)
.../lnd/fuzz/lnwire/open_channel.go:33:27: emptyMsg.MaxPayloadLength undefined (type lnwire.OpenChannel has no field or method MaxPayloadLength)
typechecking of github.com/lightningnetwork/lnd/fuzz/lnwire failed
make: *** [fuzz-build] Error 1
```

I think the `MaxPayloadLength` is removed in `lnwire` but not in `fuzz`.

**Comment by yyforyongyu** [comment]
Also I think we need to update the `go.mod` too? Running it locally altered my `go.sum` and `go.mod`.

**Comment by Crypt-iQ** [comment]
You can omit building the `lnwire` package (which is fixed in #5395) by:
`make fuzz-build pkg="brontide wtwire zpay32"` and then `make fuzz-run` with the same pkg's.

I don't think the `go.mod` should be updated since most users of LND will not be running the fuzz scripts

**Comment by yyforyongyu** [comment]
> You can omit building the `lnwire` package (which is fixed in #5395) by:
> `make fuzz-build pkg="brontide wtwire zpay32"` and then `make fuzz-run` with the same pkg's.

Non-blocking but curious about why is this commit comes before #5395, in particular the `lnwire` fix.  Seems we could fix `lnwire` first?

> I don't think the `go.mod` should be updated since most users of LND will not be running the fuzz scripts

This would be weird for developers as after they run the fuzz there will be modified files and uncleaned commits😵. Maybe we should put notes in the docs. And curious why modifying `go.mod` is not preferred? That it occupies disk space for the users?

**Comment by Crypt-iQ** [comment]
Fuzzing already modifies the local lnd directory by adding lots of files -- I see no reason to add the go-fuzz and related binaries to the user's machine unless they opt into it.  But if this project is in the habit of adding everything to go.mod even if few people will run this make script, I can do that.

**Comment by yyforyongyu** [comment]
> Fuzzing already modifies the local lnd directory by adding lots of files -- I see no reason to add the go-fuzz and related binaries to the user's machine unless they opt into it. But if this project is in the habit of adding everything to go.mod even if few people will run this make script, I can do that.

Got it. Yeah probably one day we could move it out of the lnd repo and make it an independent project.

**Review by yyforyongyu — APPROVED** [review]

**Comment by Crypt-iQ** [comment]
> > Fuzzing already modifies the local lnd directory by adding lots of files -- I see no reason to add the go-fuzz and related binaries to the user's machine unless they opt into it. But if this project is in the habit of adding everything to go.mod even if few people will run this make script, I can do that.
> 
> Got it. Yeah probably one day we could move it out of the lnd repo and make it an independent project.

It's common practice to keep the fuzz targets in the repo.  Build script doesn't necessarily have to live in the repo. The main problem I see is that I don't think there are optional `go.mod` entries that are hidden with diff build flags?

**Comment by Crypt-iQ** [comment]
@bhandras Could you review this? If you can't, I can try to find another reviewer

**Review by bhandras — APPROVED** [review]
LGTM :mango:

**Pull request merged**
