### PR TITLE
chore: fix typos [skip ci]

### PR DESCRIPTION
**Pull request by xiaoxianBoy**
## Change Description
fix typos

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Review by bhandras — APPROVED** [review]

**Review by ellemouton — APPROVED** [review]
Thanks 🙏

**Comment by ellemouton** [comment]
oh actually, @xiaoxianBoy  - could you please just first update the commit title to: `docs+lntest: fix typos`?

**Comment by ellemouton** [comment]
@xiaoxianBoy  - i dont mean the PR title, I mean the commit title

**Comment by ellemouton** [comment]
you dan do this by going `git commit --amend` & then force pushing the branch again

**Review by guggero — APPROVED** [review]

**Pull request merged**
