### PR TITLE
Ask for confirmation for command lncli sendcoins

### PR DESCRIPTION
**Pull request by zx9r**
Addresses issue #7129

### CODE REVIEW

**Comment by ziggie1984** [comment]
This feature sounds good, in reminds me of the feature when paying an invoice. You could get inspiration from there to implement your feature, its always a good idea to stay consistent in a code base. Hence I proposing using the flag [`force` ](https://github.com/lightningnetwork/lnd/blob/b1d6991b275e78f5ee81c333cc3b9d5af4108504/cmd/lncli/cmd_payments.go#L521) instead of `skip_confirmation `. And the corresponding [confirmation function ](https://github.com/lightningnetwork/lnd/blob/b1d6991b275e78f5ee81c333cc3b9d5af4108504/cmd/lncli/cmd_payments.go#L233)

**Comment by positiveblue** [comment]
It looks like a useful feature, overall for scripts :+1:

There are only a few changes needed to merge the PR:
- Rename the flag to `--force` so we stay consistent with the rest of the commands
- It could be useful to create a function only to hold the logic of printing relevant data + get confirmation. Because it is only a couple of fields it is not a deal breaker. But we should follow the same format as in the other commits (one print `key: value` per field +  the confirmation prompt
- The linter is complaining (remember to rebase before fixing them, maybe they are already fixed) 
- Remember to add an entry to the release notes.

**Comment by zx9r** [comment]
Thank you for your review. I will try to fix this in the following days

**Review by positiveblue — CHANGES_REQUESTED** [review]
Don't forget to re-request review when the PR has been updated

**Pull request closed without merging**
