### PR TITLE
lncli: add chan_id to pendingchannels response

### PR DESCRIPTION
**Pull request by ErikEk**
This pr addresses #5575. It includes the id of channels in the `lncli pendingchannels` response for both "waiting close channels" and "pending force closing channels". Because there are no channel id yet formed for a channels in the opening stage; it can't be included for "pending open channels".

### CODE REVIEW

**Comment by C-Otto** [comment]
Thanks a lot, it works. However, the channel ID appears next to the top level details (in pending_force_closing_channels), and I'd expect it in the channels object (where it already states the pubkey, capacity, channel point).

**Comment by ErikEk** [comment]
@C-Otto Problem is that the parameters within the channel structure are all used and valid among opening **and** closing channels. And since there are no channel id until a channel has been confirmed on chain, the channel id would be zero for channels in the opening stage - which means we would need a separate structure for "waiting closing"/"force closing" pending channels. I would like to have a second opinion on this before I modify the channel structure in the response.

**Comment by C-Otto** [comment]
Is this merged? Abandoned? I don't quite understand why it's not in master.

**Comment by ErikEk** [comment]
I think might be regarded as bloated since we can use `channel_point` instead.

**Comment by LNBIG-COM** [comment]
Hello!

I would like to ask you to apply this particular PR.

I had exactly the same need to know chan_id. But if the original creator (@C-Otto) of ticket was able to quickly solve the problem through channel_point, then my situation is more complicated. I need to know exactly chan_id, since I need to find forwarding payments for pending channels, and [there is no channel point information there - only chan_id](https://lightning.engineering/api-docs/api/lnd/lightning/forwarding-history#lnrpcforwardingevent).

I can, of course, recreate the chan_id using calls to bitcoind node through RPC, but I would have to make three heavy calls: find the transaction and get the hash of the block from there, then get the block data, including all transactions and find the channel point transaction among the array of all and thus find out the transaction index in the block. Only then, having the block height, the transaction index number in the block and the output index, you can recreate the chain_id, but all this is not worth such effort. In addition, such a fix will serve to improve the API, since this information may be necessary.

After looking at this patch, I see that the chan_id is already ready inside the LND, it's enough to simply insert it into the  returned result.

**Comment by C-Otto** [comment]
I agree that having this information would be great. @LNBIG-COM I suggest you create a mapping (channel ID - channel point) for all known channels, so that you can use this mapping whenever the information is missing. There might be cases, though, where you still need to do the "heavy calls". In lnd-manageJ I decided to use publicly available APIs that provide the necessary information for any given transaction hash (bitaps, blockcypher). There are privacy concerns (and possibly security concerns), though.

**Comment by LNBIG-COM** [comment]
> I suggest you create a mapping

Thank you! I will try :)

**Pull request closed without merging**
