### PR TITLE
build: create v0.18.1-beta release branch

### PR DESCRIPTION
**Pull request by guggero**
Adds the following PR as the sole fix for `v0.18.1-beta`:
 - https://github.com/lightningnetwork/lnd/pull/8862

### CODE REVIEW

**Review by ellemouton — APPROVED** [review]
LGTM ✅

**Comment by ellemouton** [comment]
ah - the only thing is that this now contains the release notes for 0.18.2 ...

**Review by ellemouton — APPROVED** [review]
cool - nice

**Review by Roasbeef — APPROVED** [review]
LGTM 🥇

**Comment by ellemouton** [comment]
replaced by https://github.com/lightningnetwork/lnd/pull/8863

**Pull request closed without merging**
