### PR TITLE
kvdb/bolt_compact: have log message take account space multiplier

### LINKED ISSUE #5937: Compaction error message due to low disk space is wrong
### Background

When compaction failed as described in #5936 I got the following message:

> could not start compaction, destination folder /home/bitcoin/.lnd/data/graph/mainnet only has 10823012352 bytes of free disk space available while we need at least 10196967424 for worst-case compaction

This is confusing, as 10823012352 > 10196967424.

### Your environment

* 0.14.0-beta.rc2
* Linux server 5.10.0-8-amd64 #&#8203;1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
* bitcoind v22

### Steps to reproduce

Have large channel.db and attempt compaction. In my case: 9.5 GByte channel.db (plus around 600 MB sphinxreplay/wtclient) on a partition with 20 GByte total space.

### Expected behaviour

The error message shows correct numbers.

### Actual behaviour

The numbers in the error message are wrong (see above).

### PR DESCRIPTION
**Pull request by jyturley**
Fixes #5937

### CODE REVIEW

**Comment by jyturley** [comment]
It looks like there is an integration test failing:
```
=== RUN   TestLightningNetworkDaemon/tranche00/01-of-90/bitcoind/test_multi-hop_htlc/committype=SCRIPT_ENFORCED_LEASE/local_force_close_on-chain_htlc_timeout
    harness.go:354: 
        	Error Trace:	harness.go:354
        	            				lnd_multi-hop_test.go:264
        	            				lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go:29
        	            				lnd_multi-hop_test.go:111
        	Error:      	Received unexpected error:
        	            	failed to receive state client stream: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	Test:       	TestLightningNetworkDaemon/tranche00/01-of-90/bitcoind/test_multi-hop_htlc/committype=SCRIPT_ENFORCED_LEASE/local_force_close_on-chain_htlc_timeout
        	Messages:   	unable to create new node for Carol
```
Which seems unrelated to this change

**Comment by yyforyongyu** [comment]
Thanks for the PR! You may consider use `[skip ci]` as mentioned in the [contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure), 
> If a PR only fixes a trivial issue, such as updating documentation on a small scale, fix typos, or any changes that do not modify the code, the commit message should end with [skip ci] to skip the CI checks.

As for the integration test, there are flakes so it's unrelated.

**Comment by jyturley** [comment]
Thanks for pointing that out @yyforyongyu. I've added `[skip ci]` to the end of the commit message.

**Review by guggero — APPROVED** [review]
Thanks for the fix, LGTM :tada:

**Review by yyforyongyu — APPROVED** [review]
LGTM⚡️

**Comment by jyturley** [comment]
Awesome. Thank you both for the review. I don't think this necessitates editing release notes as per the guideline, since this is an extremely minor change. Which means, all is required is for an authorized user to merge.

**Comment by yyforyongyu** [comment]
> Awesome. Thank you both for the review. I don't think this necessitates editing release notes as per the guideline, since this is an extremely minor change. Which means, all is required is for an authorized user to merge.

Indeed, that's what the `skip ci` is for. I've updated the checklist to hopefully make it clear, as in #5953

**Comment by guggero** [comment]
We're currently in the RC phase of a release, so merging is blocked. Your PR will be merged as soon as the merge window opens again.

**Comment by Roasbeef** [comment]
@jyturley can you add this to the _0.14.1_ release notes?

**Comment by jyturley** [comment]
I don't see a 0.14.1 release notes file, so I created a new one. I hope that was okay.

**Pull request merged**
