### PR TITLE
skip failing tests

### PR DESCRIPTION
**Pull request by gregwebs**
## Change Description

This PR is an attempt at getting the test suite to pass by disabling failing tests. Some of the test failures seem consistent but I don't know if all of them are.

## Steps to Test

Does the build pass?

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by Roasbeef** [comment]
Which platform/hardware are you running the tests on? We're investigating some recent (?) failures w/ the latest version of Go on M1/M2 hardware.

**Comment by gregwebs** [comment]
The goal of this PR is to pass on Travis. I get similar failures running on Linux (Ubuntu).

**Comment by gregwebs** [comment]
Thanks for enabling the PR! I didn't see the existing ones. It looks like they have been sitting for 2 months :(

It would be great to get back to a passing build. It is possible to use an environment variable to only skip tests in Travis, etc.

**Comment by yyforyongyu** [comment]
Usually we don't want to skip the tests because the failing tests are indicating potential bugs and need attention. The only exception I can think of is when a test is too complicated to be fixed in one PR. In that case, a corresponding issue should be made with plans of how to fix the test, also explaining why the test fails and adding a `TODO` there.

**Comment by gregwebs** [comment]
This PR passes the Travis build.

> Usually we don't want to skip the tests because the failing tests are indicating potential bugs and need attention. The only exception I can think of is when a test is too complicated to be fixed in one PR. In that case, a corresponding issue should be made with plans of how to fix the test, also explaining why the test fails and adding a TODO there.

It makes for a lot more work to submit a PR right now: I now have to look through a lot of logs to see if the failures are from my change or if they are pre-existing failures.

I like your suggestion of moving these failure issues into a github issue. Would you like me to create issues for them? But I don't have any understanding of why they are failing.

**Comment by yyforyongyu** [comment]
>  I now have to look through a lot of logs to see if the failures are from my change or if they are pre-existing failures.

What changes are you referring to?

> Would you like me to create issues for them? But I don't have any understanding of why they are failing.

I don't think we need them at the moment. I've managed to fix almost all and now working on new PRs to include the latest changes.

**Comment by gregwebs** [comment]
> > I now have to look through a lot of logs to see if the failures are from my change or if they are pre-existing failures.
> 
> What changes are you referring to?

Changes I am making in a pull request. On most projects, if the build fails that means there is a problem with my pull request. But on lnd, if the build fails the pull request is probably fine. But I have to go to extra effort to look through failure logs to determine that.

> > Would you like me to create issues for them? But I don't have any understanding of why they are failing.
> 
> I don't think we need them at the moment. I've managed to fix almost all and now working on new PRs to include the latest changes.

That would be great! I have been pointed to PRs from 2 months ago. It would be great to finally get them merged.

**Comment by yyforyongyu** [comment]
> On most projects, if the build fails that means there is a problem with my pull request. But on lnd, if the build fails the pull request is probably fine. But I have to go to extra effort to look through failure logs to determine that.

Yeah I'd expect the same and sorry about this. We've prioritized the itest refactor and they should be fixed in `v0.16.0`!

**Comment by gregwebs** [comment]
That's great to know. Probably a test refactor would not have to be fully tied to a release?
I will close this PR now.

**Comment by yyforyongyu** [comment]
> Probably a test refactor would not have to be fully tied to a release?

Totally, we will merge the fixes as we go and aim to fix all of them by `0.16.0`.

**Pull request closed without merging**
