### PR TITLE
docs: Add tlsextraip + tlsextradomain to sample config

### PR DESCRIPTION
**Pull request by LightningK0ala**
Include missing example configs for tlsextraip and tlsextradomain in sample-lnd.conf.
This is useful for users wishing to connect to lnd from a remote client.

### CODE REVIEW

**Comment by jcsmesquita** [comment]
Might be worth adding a note telling users they have to remove their old tls.key and tls.cert if they have already run the client and setting these configs?

**Comment by halseth** [comment]
can add "(old tls files must be deleted if changed)"

**Comment by LightningK0ala** [comment]
Added 👍

**Comment by halseth** [comment]
cool, LGTM! Could you squash the changes into a single commit? :)

**Comment by LightningK0ala** [comment]
Done :)

**Pull request merged**
