### PR TITLE
lnrpc: avoid lookupinvoice endpoint collision

### PR DESCRIPTION
**Pull request by wilmerpaulino**
Changes the `listinvoices` and `lookupinvoice` endpoints to avoid collisions.

We can still retrieve a list of pending invoices by passing the parameter `?pending_only=true` to the request URL.

### CODE REVIEW

**Comment by dabura667** [comment]
Do invoices/subscribe and invoices/{r_hash_str} both work with this PR?

**Comment by dabura667** [comment]
concept ACK

**Comment by wilmerpaulino** [comment]
@dabura667 I totally missed the `SubscribeInvoices` endpoint, thanks for catching that! I've addressed that as well.

**Comment by Roasbeef** [comment]
Can you rebase this to fix the conflict in the generated protos? Thanks!

**Comment by wilmerpaulino** [comment]
Rebased to master.

**Pull request merged**
