### PR TITLE
Fix the docker instruction error

### PR DESCRIPTION
**Pull request by Liaojinghui**
Change from `$ docker-compose up -d "alice"` to `docker start "alice"`

#### Pull Request Checklist

- [ ] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [ ] All changes are Go version 1.12 compliant
- [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [ ] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and
  logging level
- [ ] Code has been formatted with `go fmt`
- [ ] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [ ] Running `make check` does not fail any tests
- [ ] Running `go vet` does not report any issues
- [ ] Running `make lint` does not report any **new** issues that did not
  already exist
- [ ] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

### CODE REVIEW

**Comment by Liaojinghui** [comment]
I struggled this for a whole day, everytime I try to connect `alice` to `Faucet`, error of can't find `admin.macaroon` in the `testnet` path. To fix this, I changed all the default network from `simnet` to `testnet` in the shell source code and recreate all my containers again. I know this is stupid, but I can not figure out which command is missing in the docker instruction https://github.com/lightningnetwork/lnd/tree/master/docker#connect-to-faucet-lightning-node.

**Comment by valentinewallace** [comment]
> I struggled this for a whole day, everytime I try to connect `alice` to `Faucet`, error of can't find `admin.macaroon` in the `testnet` path. To fix this, I changed all the default network from `simnet` to `testnet` in the shell source code and recreate all my containers again. I know this is stupid, but I can not figure out which command is missing in the docker instruction https://github.com/lightningnetwork/lnd/tree/master/docker#connect-to-faucet-lightning-node.

I'm getting the same problem. Could you open an issue for this?

**Comment by valentinewallace** [comment]
> I struggled this for a whole day, everytime I try to connect `alice` to `Faucet`, error of can't find `admin.macaroon` in the `testnet` path. To fix this, I changed all the default network from `simnet` to `testnet` in the shell source code and recreate all my containers again. I know this is stupid, but I can not figure out which command is missing in the docker instruction https://github.com/lightningnetwork/lnd/tree/master/docker#connect-to-faucet-lightning-node.

Unfortunately `docker start` doesn't let you set new environment variables, so in order to switch to testnet you need to get rid of your existing `alice` container, set `export NETWORK=testnet` and re-run `docker-compose run -d --name alice lnd_btc` before starting the container again. Lmk if this works for you.

**Comment by valentinewallace** [comment]
@Liaojinghui Hi, sorry for the confusion but I just saw [this replacement PR](https://github.com/lightningnetwork/lnd/pull/3393) which fixes the same problem and also solves the problem you mentioned in [your comment](https://github.com/lightningnetwork/lnd/pull/3411#issuecomment-522190872). So I'll be closing this PR in favor of that one :)

**Pull request closed without merging**
