### PR TITLE
make: don't optimize debug binaries

### PR DESCRIPTION
**Pull request by liviu-ln**
Disable compiler optimizations and function inlining on a debug build to
improve debugging experience.

### CODE REVIEW

**Review by guggero — COMMENTED** [review]
Changes look good to me. This either needs an entry in the 0.15 release notes or the `[skip ci]` suffix in the commit message title.

**Review by guggero — APPROVED** [review]
Thanks, LGTM :tada:

**Comment by liviu-ln** [comment]
Is there anything else that needs my attention before the PR can be merged?

**Comment by guggero** [comment]
No, this just needs a second reviewer. Going to pick someone.

**Review by bhandras — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
