### PR TITLE
itest: fix on-chain recovery flake caused by short timeout/btcd on ARM

### PR DESCRIPTION
**Pull request by bhandras**
Attempted fix for: https://github.com/lightningnetwork/lnd/issues/5532

~Timeout flake has been appearing on Travis lately due to possible performance degradation. In the log it clearly shows that while we scan the chain while running the wallet recovery we do run out of the 30 sec default timeout window: https://termbin.com/ytdy~

Edit:
After some discussion it turned out to be a `btcd` issue so the attempted solution for this flake is to (at least temporarily) switch the ARM itest build on Travis to use `bitcoind`.

### CODE REVIEW

**Comment by guggero** [comment]
I have a suspicion what this could be. I don't think that increasing the timeout will make this go away.
I think that because of a bug in `btcd` the mining btcd node and lnd's chain backend btcd node lose each other's connection, that's why the miner never learns of some of the broadcast transactions. Perhaps switching to `bitcoind` will solve the problem for us (at least for ARM)?

**Comment by bhandras** [comment]
> I have a suspicion what this could be. I don't think that increasing the timeout will make this go away.
> I think that because of a bug in `btcd` the mining btcd node and lnd's chain backend btcd node lose each other's connection, that's why the miner never learns of some of the broadcast transactions. Perhaps switching to `bitcoind` will solve the problem for us (at least for ARM)?

Possible, but the attached log also seem to indicate timeout is indeed happening. I'll try and run a few more times and we'll see.

**Comment by bhandras** [comment]
> > I have a suspicion what this could be. I don't think that increasing the timeout will make this go away.
> > I think that because of a bug in `btcd` the mining btcd node and lnd's chain backend btcd node lose each other's connection, that's why the miner never learns of some of the broadcast transactions. Perhaps switching to `bitcoind` will solve the problem for us (at least for ARM)?
> 
> Possible, but the attached log also seem to indicate timeout is indeed happening. I'll try and run a few more times and we'll see.

Did check the miner and chain backend logs too, and indeed as you mention it seems there are some requests that fail and backoff for 5sec but the majority of the requtests seem to go through. I'll dig into this a bit more to see how much these disconnections count.

**Comment by bhandras** [comment]
Okay did a few runs, indeed it seems like `btcd` reconnects hurt these tests badly. Sometimes the longer timeout did help, sometimes it didn't. I'll change the miner and chain backend ti `bitcoind` instead.

**Comment by bhandras** [comment]
Can confirm, the ARM chain recovery flakes are fixed.

**Review by guggero — APPROVED** [review]
Nice, LGTM :100:

**Review by yyforyongyu — APPROVED** [review]
Nice!!!LGTM🦾

**Pull request merged**
