### PR TITLE
go.mod: update LND sub-module deps

### PR DESCRIPTION
**Pull request by ellemouton**
Demonstrate CI passes for https://github.com/lightningnetwork/lnd/pull/9212

Will update to tags once that PR is merged.

### CODE REVIEW

**Comment by guggero** [comment]
Pushed 4 new tags: `healthcheck/v1.2.6 kvdb/v1.4.11 sqldb/v1.0.5 tor/v1.1.4`

**Comment by ellemouton** [comment]
Thanks @guggero !! 🎉  updated

**Review by guggero — APPROVED** [review]
Can you rebase on top of the merged https://github.com/lightningnetwork/lnd/pull/9228 please? That should fix some of the itest failures.

Other than that LGTM :tada:

**Review by bhandras — APPROVED** [review]
LGTM ☕

**Pull request merged**
