### PR TITLE
lncli: add leaseoutput command

### PR DESCRIPTION
**Pull request by joostjager**
Adds the complement of `releaseoutput`. Also extends `releaseoutput` with the lock id flag.

### CODE REVIEW

**Comment by joostjager** [comment]
Cannot update release notes, because there is no file yet. Unless this can still be included in 0.14?

**Review by guggero — APPROVED** [review]
utACK, LGTM :tada: 

We're not sure if RC3 is already the final one. So probably best to create the file for 0.15 release notes.

**Comment by carlaKC** [comment]
@guggero accidentally re-requested you when adding myself as reviewer, sorry!

**Review by carlaKC — APPROVED** [review]
tACK, thanks for the contribution

**Review by guggero — APPROVED** [review]

**Comment by guggero** [comment]
GitHub thinks there is a merge conflict but doesn't show what exactly. Can you rebase to get rid of it please?

**Comment by joostjager** [comment]
I think the conflict was on the release notes. Rebased.

**Pull request merged**
