### PR TITLE
Fixing newline on "Shutdown complete" log message	modified:   lnd.go

### LINKED ISSUE #8713: [bug]: Regression: Missing newline in "Shutdown complete" log message
See https://github.com/lightningnetwork/lnd/issues/3801. This bug resurfaced with `v0.17.3-beta` or before:

This is the output (in `lnd.log`) with `lncli stop` (v0.17.3-beta) and then re-starting lnd (v0.18.0-beta.rc1).
```
2024-04-30 15:21:12.886 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2024-04-30 15:21:12.899 [INF] LTND: Shutdown complete2024-04-30 15:21:19.087 [INF] LTND: REST API is disabled!
2024-04-30 15:21:19.089 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
```

### PR DESCRIPTION
**Pull request by MPins**
Fixes #8713 

## Change Description
Insert a blank line log message after the "Shutdown complete" log message to ensure that a new line is printed.
		
This is actually a workaround as the '\n' character was not working properly in some situations. See the tests I did at #8713. 

You can reproduce the bug starting and stopping the LND using the "systemctl start lnd" and "systemctl stop lnd".

## Steps to Test
The bug fix was tested on Ubuntu using systemctl start/stop lnd, as the bug only manifested this way. 

## Original Flaw

2024-05-20 14:04:17.705 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
2024-05-20 14:04:17.705 [INF] LTND: Version: 0.18.0-beta.rc2 commit=v0.18.0-beta.rc1-48-g2a8ca878f, build=development, logging=default, debuglevel=info
.
.
.
2024-05-20 14:05:01.948 [INF] LTND: **Shutdown complete2024-05-20** 14:05:19.906 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
2024-05-20 14:05:19.907 [INF] LTND: Version: 0.18.0-beta.rc2 commit=v0.18.0-beta.rc1-48-g2a8ca878f, build=development, logging=default, debuglevel=info

## Test After the PR

2024-05-20 15:59:47.298 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
2024-05-20 15:59:47.298 [INF] LTND: Version: 0.18.0-beta.rc2 commit=v0.18.0-beta.rc1-48-g2a8ca878f-dirty, build=development, logging=default, debuglevel=info
.
.
.
**2024-05-20 16:00:29.366 [INF] LTND: Shutdown complete
2024-05-20 16:00:29.366 [INF] LTND:**
2024-05-20 16:00:47.594 [WRN] LTND: Config 'bitcoin.active' is deprecated, please remove it
2024-05-20 16:00:47.594 [INF] LTND: Version: 0.18.0-beta.rc2 commit=v0.18.0-beta.rc1-48-g2a8ca878f-dirty, build=development, logging=default, debuglevel=info

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by Abdulkbk** [comment]
Hi @MPins thanks for the PR.

I tested your work and it seems a `newline` is not added after the log "Shutdown complete" message. It was though before your PR as can be seen in the shots below:

*Before* 
b4


*After*
after

**Review by Abdulkbk — COMMENTED** [review]
It seems this doesn't add a new blank line after the final log statement

**Comment by Chinwendu20** [comment]
I think @C-Otto [was right](https://github.com/lightningnetwork/lnd/issues/8713#issuecomment-2087071166), this "\n" should not be needed at the end of the shutdown complete message anyway because it should be added by the [logging library](https://github.com/btcsuite/btclog/blob/master/log.go). I was not able to reproduce it but from your test it seems only to occur with systemd? Maybe we should figure out first if this is an lnd an issue and why exactly the new line does not work?

**Comment by MPins** [comment]
Hello @Abdulkbk and @Chinwendu20 ... you only see the bug on the log file and you have to start and stop LND using systemd command.

You can see a lot of tests I did before and after the PR at #8713

**Comment by MPins** [comment]
Closing this PR as the https://github.com/lightningnetwork/lnd/pull/9083 solve the issue https://github.com/lightningnetwork/lnd/issues/8713 .

**Comment by MPins** [comment]
Hello @saubyk this PR should be closed as the https://github.com/lightningnetwork/lnd/pull/9083 solve the issue https://github.com/lightningnetwork/lnd/issues/8713 .

**Comment by guggero** [comment]
Replaced by https://github.com/lightningnetwork/lnd/pull/9083.

**Pull request closed without merging**
