### PR TITLE
[trivial] remove noop env from script 

### PR DESCRIPTION
**Pull request by halseth**

### CODE REVIEW

**Comment by halseth** [comment]
`GO111MODULE=on` seems to not work with some of the tools we are fetching.

**Comment by halseth** [comment]
I initially did set `GO111MODULE=on` as a global variable, but that didn't work for `go get` `glide`, and `gometalinter` etc. Instead I just remove the redundant `env` for now.

**Comment by cfromknecht** [comment]
needs rebase to resolve conflict

**Comment by halseth** [comment]
Not relevant after the latest changes to the Travis config. Closing.

**Pull request closed without merging**
