### PR TITLE
Update licenses to 2019

### PR DESCRIPTION
**Pull request by junderw**
Small fixes to copyright years on all files.

### CODE REVIEW

**Comment by molxyz** [comment]
ACK!

We need to update the licenses before this year is over!  😆

**Comment by Crypt-iQ** [comment]
Looks good to me

**Comment by alexbosworth** [comment]
Almost too late

Ack but maybe we can go to 2020 now

**Comment by guggero** [comment]
Needs rebase!

**Comment by junderw** [comment]
🤣

**Pull request closed without merging**
