### PR TITLE
Added feature route to self

### PR DESCRIPTION
**Pull request by ZapUser77**
* Added ability to find paths to self

* Added unit tests for self routing

This allows queryroutes to find a route to self for manual balancing of channels.
And will lays the grounds for rebalance command, as well as auto-balancing channels.

### CODE REVIEW

**Comment by ZapUser77** [comment]
Solves: https://github.com/lightningnetwork/lnd/issues/1645

**Comment by ZapUser77** [comment]
Fixed bad interaction between FindPath and FindPaths that wasn't previously detected in unit testing, which caused an infinite loop between them.

**Comment by halseth** [comment]
Blocked by #1321.

**Comment by joostjager** [comment]
In my opinion, the implementation as it is now contains assumptions that may not be true leading to suboptimal results. In particular the determination of the "middle node". 

I am not sure either whether this is optimal performance-wise with the recursive `findPath` call.

I think the plan with a virtual self node as outlined in https://github.com/lightningnetwork/lnd/pull/1652 is more solid. Don't want to reopen the discussion, but just drop the reference for any reviewers to consider.

**Comment by ZapUser77** [comment]
You don't have to find the "optimum" path on the first try, that's what "FindPaths" does.  
FindPaths finds more than one path, then provides them in ascending order.
Virtual self simply does not work, as it doesn't look down paths where it encounters a node that's closer, which is *must* do to function properly.

**Comment by ZapUser77** [comment]
Needs to have the code pieces moved around to compensate for the reverse pathfinding introduced in 1321.

**Comment by ZapUser77** [comment]
Had to re-write to be compatible with new pathfind algo.
Closing this PR and opened https://github.com/lightningnetwork/lnd/pull/1751

**Pull request closed without merging**
