### PR TITLE
lnrpc listpayments enhancement

### PR DESCRIPTION
**Pull request by de6df1re**
[Add Total Number of Payments in REST GET /v1/payments](https://github.com/lightningnetwork/lnd/issues/5382)

Action Taken:

- Update lnrpc/rpc.proto with new attribute for total_payments, updated documentation
- Updated rpcserver.go with new logic for total_payments
- Ran make rpc to update rpc.swagger.json and rpc.pb.go
- Updated lnd_test.go -> testListPayments() to test new logic and attribute in two scenerios (incomplete_incomplete false and true), this test succeeded
- Formatted all code per the standards
- Testing, in test environment, built, installed and tested REST API as well is CLI in various scenarios and confirmed new total_payments attribute works as expected
- Resolved merge conflict with lnrpc/rpc.pb.go

#### Pull Request Checklist

- [x] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [x] All changes are Go version 1.12 compliant
- [x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [x] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [NA] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [x] Any new logging statements use an appropriate subsystem and
  logging level
- [x] Code has been formatted with `go fmt`
- [x] Protobuf files (`lnrpc/**/*.proto`) have been formatted with
  `make rpc-format` and compiled with `make rpc`
- [NA] New configuration flags have been added to `sample-lnd.conf`
- [x] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [x] Running `make check` does not fail any tests
- [x] Running `go vet` does not report any issues
- [x] Running `make lint` does not report any **new** issues that did not
  already exist
- [x] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [x] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

### CODE REVIEW

**Comment by alexbosworth** [comment]
Querying all records rather than index, I would think this is not going to execute very quickly

**Comment by de6df1re** [comment]
This is good feedback... I can dig into querying the index instead

**Comment by Roasbeef** [comment]
This call should be useful for that: https://pkg.go.dev/github.com/coreos/bbolt#Bucket.Sequence

**Comment by de6df1re** [comment]
I am working on using the index/sequence to get total_payments count, however one of the requirements in the issue is to adjust the returned count based on the include_incomplete flag.  In order to meet this requirement, I think it would be necessary to inspect each payment for failure, as opposed to using the index count.  If that requirements seems unnecessary, it will be easier to get the total_payments count from something like the index bucket ->sequence value.

**Comment by de6df1re** [comment]
Closing in favor of separating out some bug fixes included here and resubmitting individual PRs in a more concise way

**Pull request closed without merging**
