### PR TITLE
release: create v0.17.5 release branch 

### PR DESCRIPTION
**Pull request by Roasbeef**
This release includes a single PR: #8573. This fixes an issue with bitcoind which starts to explicitly reject values it deems to be high fee from `sendrawtransaction`. See #8571 for more details.

### CODE REVIEW

**Comment by Roasbeef** [comment]
Hit this failure in CI: 
```
--- FAIL: TestLightningWalletBitcoindZMQ (10.38s)
    test_interface.go:3277: unable to establish connection to bitcoind: method did not return within the timeout
--- FAIL: TestLightningWalletBitcoindRPCPolling (31.08s)
    --- FAIL: TestLightningWalletBitcoindRPCPolling/btcwallet/bitcoind-rpc-polling:transaction_subscriptions (4.34s)
        test_interface.go:1479: 
                Error Trace:    /home/runner/work/lnd/lnd/lnwallet/test/test_interface.go:1479
                                            /home/runner/work/lnd/lnd/lnwallet/test/test_interface.go:3465
                Error:          Received unexpected error:
                                unmatched backend error: -25: Unspendable output exceeds maximum configured by user (maxburnamount)
                Test:           TestLightningWalletBitcoindRPCPolling/btcwallet/bitcoind-rpc-polling:transaction_subscriptions
```

Was fixed here in master: https://github.com/lightningnetwork/lnd/commit/783e9140275c2bae355cb0696248c2f6dc743f5a

Similar thing where `bitcoind` doesn't like large amounts of Bitcoin in `OP_RETURN` outputs. We used it previously to burn Bitcoin in a test. Now we'll just send to a random pubkey. 

Tacked on just that commit from the greater PR (https://github.com/lightningnetwork/lnd/pull/8345), which has other _new_ logic re `testmempoolaccept` usage.

**Comment by guggero** [comment]
Unit tests fail because of the borked Unix socket support in `bitcoind` v27.0 (see https://github.com/bitcoin/bitcoin/pull/27679, broken by https://github.com/bitcoin/bitcoin/pull/22087). Was fixed in https://github.com/lightningnetwork/lnd/pull/8273, but maybe that whole PR is a bit too involved to apply to this branch.
We could just replace all instances of `ipc://` with `tcp://`, for example: https://github.com/lightningnetwork/lnd/blob/b5a626be783e2a65e87073742a5a46bb5f5952c3/routing/chainview/interface_test.go#L716

This will be flakey without the fix to the unique port generation code in #8273 but at least most of the unit tests would pass.

**Comment by Roasbeef** [comment]
@guggero thanks for that!

Cherry picked it into the branch.

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Pull request merged**
