### PR TITLE
lnrpc: make ChannelPoint.funding_txid a protobuf oneof and change CloseChannel endpoint

### LINKED ISSUE #552: Force-Closing a channel over Rest fails
Hi, I cannot close a channel with either the rest API or `lncli`...

Rest API:
```
Client error: `DELETE https://lightningsale:***@lnd:8080/v1/channels/1198623c07ceb98ccfe4674e74d1f7b22840cc805e1a9491e9d17b88c32d98ec/0` resulted in a `400 Bad Request` response:
{"error":"type mismatch, parameter: channel_point.funding_txid, error: unsupported field type uint8","code":3}
```

Rest API (output index 1):
```
Client error: `DELETE https://lightningsale:***@lnd:8080/v1/channels/1198623c07ceb98ccfe4674e74d1f7b22840cc805e1a9491e9d17b88c32d98ec/1` resulted in a `400 Bad Request` response:
{"error":"type mismatch, parameter: channel_point.funding_txid, error: unsupported field type uint8","code":3}
```

Please advice :)

Also how do I force close a channel over Rest?

### PR DESCRIPTION
**Pull request by wilmerpaulino**
Fixes #552.

This PR introduces the following changes:

* Makes `ChannelPoint`'s `funding_txid` a oneof between its `bytes` and `string` representation.
* Updates the rest of `lnd` and `lncli` to handle the new proto update from above.
* Changes the endpoint of `CloseChannel` to use the string representation `funding_txid_str` instead.

### CODE REVIEW

**Comment by wilmerpaulino** [comment]
Forgot to update tests, will fix.

**Comment by wilmerpaulino** [comment]
Should be good for review now.

**Comment by Roasbeef** [comment]
With #596 merged, can you rebase this now? Thanks!

**Comment by wilmerpaulino** [comment]
Rebased and made some minor nit changes.

**Comment by Roasbeef** [comment]
Can you rebase this? Thanks!

**Comment by Roasbeef** [comment]
Can you rebase this? Thanks!

**Comment by wilmerpaulino** [comment]
Rebased.

**Comment by Roasbeef** [comment]
After the rebase, the build is broken: 
```
./lnd_test.go:2410:42: cannot use chanPoint.FundingTxid (type lnrpc.isChannelPoint_FundingTxid) as type []byte in argument to "github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/chaincfg/chainhash".NewHash
./lnd_test.go:2619:42: cannot use chanPoint.FundingTxid (type lnrpc.isChannelPoint_FundingTxid) as type []byte in argument to "github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/chaincfg/chainhash".NewHash
```

**Comment by wilmerpaulino** [comment]
Should be good now.

**Pull request merged**
