### PR TITLE
build: update to latest version of btcwallet w/ taproot estimation fix

### PR DESCRIPTION
**Pull request by Roasbeef**
Fixes https://github.com/lightningnetwork/lnd/issues/6873

### CODE REVIEW

**Comment by guggero** [comment]
Looks like the itest needs a slight adjustment:

```
 === CONT  TestLightningNetworkDaemon/tranche03/92-of-109/btcd/wallet_import_account
 --- FAIL: TestLightningNetworkDaemon/tranche03/92-of-109/btcd/wallet_import_account/standard_BIP-0086 (4.59s)
    lnd_wallet_import_test.go:270: 
        	Error Trace:	lnd_wallet_import_test.go:270
        	            				lnd_wallet_import_test.go:701
        	            				lnd_wallet_import_test.go:646
        	            				lnd_wallet_import_test.go:618
        	            				test_harness.go:115
        	            				lnd_wallet_import_test.go:613
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = unmatched backend error: -26: TX rejected: transaction 1509a2735bfbfad2e7c6ac43a47a7bd534d7c95631801d176d4b68e765151af8 has insufficient priority (657894.7368421053 <= 5.76e+07)
        	Test:       	TestLightningNetworkDaemon/tranche03/92-of-109/btcd/wallet_import_account
```

**Comment by Roasbeef** [comment]
Thx for those fixes @guggero! I took over your `btcwallet` branch, and selectively applied the patch you sent above. Waiting for CI now...

**Comment by guggero** [comment]
Argh, I should have run the full test suite locally...
There's one more failure:

```
diff --git a/lntest/itest/lnd_recovery_test.go b/lntest/itest/lnd_recovery_test.go
index fe1f629ed..02cafddb4 100644
--- a/lntest/itest/lnd_recovery_test.go
+++ b/lntest/itest/lnd_recovery_test.go
@@ -338,11 +338,11 @@ func testOnchainFundRecovery(net *lntest.NetworkHarness, t *harnessTest) {
        }
        restoreCheckBalance(finalBalance, 9, 20, promptChangeAddr)
 
-       // We should expect a static fee of 50100 satoshis for spending 9 inputs
+       // We should expect a static fee of 36400 satoshis for spending 9 inputs
        // (3 P2WPKH, 3 NP2WPKH, 3 P2TR) to two P2WPKH outputs. Carol should
        // therefore only have one UTXO present (the change output) of
        // 9 - 8 - fee BTC.
-       const fee = 50100
+       const fee = 36400
        restoreCheckBalance(finalBalance-minerAmt-fee, 1, 21, nil)
 
        // Last of all, make sure we can also restore a node from the extended
```

But after that fix, the itest should be fully green.

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Review by yyforyongyu — APPROVED** [review]
LGTM👍

**Pull request merged**
