### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by BTCparadigm**
Should this be updated?

### CODE REVIEW

**Comment by alexbosworth** [comment]
also see https://github.com/lightningnetwork/lnd/pull/2644

**Review by prayank23 — APPROVED** [review]
ACK https://github.com/lightningnetwork/lnd/pull/6168/commits/7400600fa2d735dc76bcec0865dce3a3f9a8ec63

**Review by guggero — COMMENTED** [review]
Changes look good to me. Please rebase to get rid of the merge commit and prefix the commit messages according to [our contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure).

**Comment by BTCparadigm** [comment]
Hopefully #6239 replaces this PR. Couldn't figure out how to rebase this correctly.
image

**Comment by yyforyongyu** [comment]
You can close this one if it's replaced by #6239.

**Pull request closed without merging**
