### PR TITLE
lntest/node: persist network subscription state across restarts

### LINKED ISSUE #1496: Missing channel announcement
While working on PR #1493 I believe I discovered a bug related to missing announcements to connected peer.

Problem can be see [here](https://travis-ci.org/lightningnetwork/lnd/jobs/399082974) 
The integration tests failed with an error "channel not opened before timeout".

This error is not consistent and has a probability for showing up (my guess is 25%). 

Let me explain the situation using 3 nodes:Alice, Bob, Carol

1. Alice (P2Pport 19555) connects with Bob (19558). They open a channel between them.

2. Carol (19561) connects with Alice.

3. Bob restarts. At startup both Alice and Bob tries to restore the connection. Lets assume that Bob managed to create the connection, from port 59756 to 19555. Alice detected that she does not need to continue trying to set a connection with Bob.

Alice log:
```
2018-07-02 11:28:57.038 [DBG] CMGR: Attempting to connect to 0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f@127.0.0.1:19558 (reqid 13)
2018-07-02 11:28:57.039 [DBG] CMGR: Failed to connect to 0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f@127.0.0.1:19558 (reqid 13): dial tcp 127.0.0.1:19558: connect: connection refused
2018-07-02 11:28:57.039 [DBG] CMGR: Retrying connection to 0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f@127.0.0.1:19558 (reqid 13) in 5s
2018-07-02 11:28:57.539 [INF] SRVR: New inbound connection from 127.0.0.1:59756
2018-07-02 11:28:57.539 [INF] SRVR: finalizing connection to 0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f, inbound=true
2018-07-02 11:28:57.539 [DBG] PEER: Sending Init to 127.0.0.1:59756
2018-07-02 11:28:57.539 [DBG] CMGR: Canceling: 0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f@127.0.0.1:19558 (reqid 13)
2018-07-02 11:28:57.540 [DBG] PEER: Received Init from 127.0.0.1:59756  
```

4. Now, Carol opens a channel with Alice. All good so Alice tries to broadcast the channel announcement to Bob

Alice log:
```

2018-07-02 11:29:01.680 [INF] DISC: Broadcasting batch of 4 new announcements
2018-07-02 11:29:01.680 [DBG] SRVR: Broadcasting 1 messages
2018-07-02 11:29:01.680 [DBG] SRVR: Broadcasting 1 messages
2018-07-02 11:29:01.680 [DBG] SRVR: Broadcasting 1 messages
2018-07-02 11:29:01.680 [DBG] SRVR: Broadcasting 1 messages
2018-07-02 11:29:02.039 [DBG] CMGR: Attempting to connect to 0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f@127.0.0.1:19558 (reqid 13)
2018-07-02 11:29:02.042 [DBG] CMGR: Ignoring connection for canceled connreq=0397268f5962e3cdf0fe3d9f8acac4b2384f74a8ace109ed400e19727b4cc9da6f@127.0.0.1:19558 (reqid 13)

```

Result - Bob is not aware of the channel between Carol and Alice. 

This is exactly the situation in the integration test:

- Alice and Bob connected.
- testSwitchCircuitPersistence - restarts Alice and Bob. They will restore the connection by not always it will be by Alice
- In case connection restored by Bob, testSwitchOfflineDelivery will fail.

### PR DESCRIPTION
**Pull request by cfromknecht**
In this PR, we modify the test harness to persist the state of prior subscription events across restarts. @offerm discovered that the `testSwitchCircuitPersistence` fails probabilistically, depending on which node established the connection after a restart.

The test only seemed to fail whenever the restarted node connects successfully. Since a topology update is ignored if we detect a duplicate, after restarting this event will not be replayed to any `SubscribeChannelGraph` clients.

Thus after a restart, a node would not deliver another event, even though it had already seen the channel. In our testing harness, we currently wipe the state of subscriptions during restart, since the maps for tracking prior updates were not tied to the `HarnessNode` struct. The fix is then to keep these indexes on the `HarnessNode`, instead of in the local scope of the subscription client, that way the client can "remember" updates it received prior.

Resolves #1496 and closes #1730.

### CODE REVIEW

**Comment by offerm** [comment]
Hi @cfromknecht Happy to help.

I'm not sure how this PR solves the problem. Can you please explain.

I think this is an implementation problem and not a test infrastructure issue.

**Comment by cfromknecht** [comment]
The test you reproduced fails because Bob doesn't report knowing about his own channel with Alice, which is created before the restart. Thus the graph subscription is delivered before Bob is restarted. After a restart, we won't send out a duplicate for the same channel, so the test reports that Bob doesn't know about the channel. This is fixed by having the test remember that Bob received the update before shutting down.

**Comment by cfromknecht** [comment]
Could it also be that #1730 didn't recreate the actual scenario, but instead triggers a similar error in the integration tests?

**Comment by cfromknecht** [comment]
As there was no restart in the test previously

**Comment by offerm** [comment]
#1730 recreate the same problem.

What do you mean by "no restart in the test setup"?

**Comment by cfromknecht** [comment]
#1730 adds a restart right after making the Alice->Bob channel, which causes the test to lose state about what events it's already received. This restart is not present in master, so I'm suggesting the root cause may be different

**Comment by cfromknecht** [comment]
#1730 recreates the same _error_, which doesn't necessarily mean it reproduces the same issue

**Comment by offerm** [comment]
1730 reproduce the error, not the exact scenario. 

I have seen this happened in a few tests. 

Also explained in #1496 the reason for it.

This is a code problem and not a test problem. I can easily reproduce it manually.

**Comment by cfromknecht** [comment]
Are you able to reproduce it without a restart?

**Comment by offerm** [comment]
I can try to reproduce the exact same scenario of #1496 if you like. 

Note that I added a restart to make sure the connection between Alice and Bob will be created in the problematic direction. Without this restart, the direction of the connection is random (may be from a previous test) and you will see the problem only from time to time (when the connection direction is problematic). This is why it is so challenging to reproduce.

**Comment by offerm** [comment]
Also note that when the test is starting Alice and Bob are already connected (and sometimes have a channel between them).  

I can probably reproduce it by placing the restart in the test prior to the fail one.  There are many restarts of Bob and Alice and if the test starts when the connection is in the wrong direction, it will fail (even without a restart)

**Comment by cfromknecht** [comment]
I moved the restart to the very top of the test, and now the tests passes reliably. Can you confirm that this happens for you?

**Comment by offerm** [comment]
Will try to do tomorrow. Need some sleep time. Late here.

**Comment by cfromknecht** [comment]
fwiw, i ran this test 300 times in isolation and it never failed. perhaps it is triggered by entering some state in the prior test?

**Comment by offerm** [comment]
@cfromknecht I Played with the test a bit and here are my conclusions:

- I couldn't work on #1493 error (pointed from #1496) - The logs are already lost. 

- moving the port and restart to the top of the test will not fail the test. The reason is that at the top of the test there is no channel between Alice and Bob. After the restart nor Alice nor Bob attempt to restore the connection between them. When the test setup the channel between Alice and Bob, Alice will use the "new" port to connect to Bob and there will be no issue. 

- Running the test testSwitchCircuitPersistence with port and restart produces a failure every time, even if running in an isolated environment (single test).

- Managed to reproduce the same problem also in testSwitchOfflineDelivery (that was easy since these 2 tests are basically the same up to the point of failure).

- The EnsureConnected has no impact related to the problem. I removed it from the{ setport, restart, ensureconnected} block and the failure is still here.

- Removing the block few lines down (see PR) to let Alice<->Bob channel setup complete made no difference.

**Comment by cfromknecht** [comment]
@offerm 

> I couldn't work on #1493 error (pointed from #1496) - The logs are already lost.

Yeah unfortunately they get cut off for Alice and Bob towards the end

> The EnsureConnected has no impact related to the problem. I removed it from the{ setport, restart, ensureconnected} block and the failure is still here.

This makes sense, Bob should try to establish a persistent connection on start up with the last known address. 

> Running the test testSwitchCircuitPersistence with port and restart produces a failure every time, even if running in an isolated environment (single test).

> The reason is that at the top of the test there is no channel between Alice and Bob

> Removing the block few lines down (see PR) to let Alice<->Bob channel setup complete made no difference.

Right, though these are caused by what i'm pointing out in this PR. If a channel is created before restarting Bob, then `bob.WaitForNetworkOpen` will lose all state about prior events and those updates won't come through after the restart as they would be duplicates.

By making those carry over across restarts, this PR proves that all notifications _are_ getting delivered, even with the restart in place. I'm saying the test framework would need modification in order to properly check if channels were opened with`RestartNode` as placed, aka, _anywhere_ between creating `Alice->Bob` and `bob.WaitForNetworkOpen`. With such a fix, placing a restart there does not trigger any bugs because we are properly tracking updates before and after the restart.

**Comment by offerm** [comment]
@cfromknecht I understand better now. Thanks

I didn't get it that WaitForNetworkOpen is not checking with the node but relies on the test infrastructure.  Did you consider to replace it with `describegraph` rpc call? The graph should be similar for all nodes hence easy to check with the current implementation.  

I would also consider to add a check at the begining of the test[s] to make sure that the network is according to the state we think it is. I have seen cases when channels are left open accross tests and causing failures like `htlc mismatch` (we count 5 htlcs in all channels not just the test channel).

Anyway, once this is merged I will try to play with the tests again.  I think this is not the only problem that causes this test to fail randomly.  I'm also spending some time on #1632 which failed in the same test but for a different reason.  Looks really bad. You may want to have a look, specially at Alice's log:

> 
> 2018-07-24 11:01:54.636 [ERR] LTND: unable to lookup witness: no witnesses
> 2018-07-24 11:01:54.636 [ERR] LTND: unable to lookup witness: no witnesses
> 2018-07-24 11:01:54.636 [ERR] LTND: unable to lookup witness: no witnesses
> 2018-07-24 11:01:54.636 [ERR] LTND: unable to lookup witness: no witnesses
> 2018-07-24 11:01:54.636 [ERR] LTND: unable to lookup witness: no witnesses
> 

I will update #1632 if/when I have findings.

Thanks for your help!

Somehow related, I suggest you give attention to #1588

**Comment by halseth** [comment]
Promoting to P2, as this will resolve some flake issues we are seeing. 

Should be ready for merge after a rebase! (and one more LGTM)

**Comment by cfromknecht** [comment]
@halseth rebased!

**Pull request merged**
