### PR TITLE
Update fee after channel becomes active, fixes #8790

### LINKED ISSUE #8790: [bug]: stale commitment fee for rarely active channels
### Background

Commitment fee (CFee) may get very stale after a while for the private (unpublished) channels if the peer isn't online for a while. I have a few such private channels to my own various wallets and also a channel to my friend. He only uses it rarely to receive payments and exits the app right after that. I initiated this channel so only I can update the CFee. However, it was once set to 1 sat/vB and never updated since. This issue applies mostly to the private channels because they're assumed to be inactive most of the time. Public channels are used for routing and must always be active so the update will happen sooner or later.

I did a little research and it seems that CFee only [updates](https://github.com/lightningnetwork/lnd/blob/b137892ceba2ea06d87a751028eeab5549733a44/htlcswitch/link.go#L1361) (links point to the relevant source line) when a channel timer elapses but never for any other reason. The timer has a random period [between 10 and 60 minutes](https://github.com/lightningnetwork/lnd/blob/b137892ceba2ea06d87a751028eeab5549733a44/htlcswitch/link.go#L56), it can not be changed by the user I assume, couldn't find any relevant code and config parameters. So the clients that don't stay online for quite a long while (up to 1 hour) will never receive a fee update. They may get stuck with a very low fee until they have to FC (due to their LSP losing the state/shutting down/the LSP decides to FC instead) only to find out that their FC tx can't even enter the mempool because it's below the purge level.

AFAIK no apps show the current CFee so the problem would be quite hidden. I see it in `lntop` and I can also check it with `lncli listchannels` of course. But the mobile clients either have it buried in the dev settings or don't expose it at all. Asking the peer to keep their phone on with the app active for up to 1 hour (I don't know what period the timer has, it's random) so that their balance can actually be resolved on chain if things go south, is an extremely bad UX. Also CFee can not be forcibly updated by the lnd user. The only way is that single timer, I didn't find any other lines that call this function.

### Your environment

* version of `lnd` v0.17.5
* which operating system (`uname -a` on *Nix) 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC (Debian 12.5 stable)
* version of `btcd`, `bitcoind`, or other backend v26.1.knots20240325
* any other relevant environment details

### Steps to reproduce

1) Open a private channel, can be public as well, it shouldn't matter; for mobile apps I usually open a private one
2) Wait for the fees to be low enough, keep the app running so the CFee is updated
3) Exit the app, wait for the fees to rise
4) Open the app, do any payments, close it in under 10 minutes
5) Keep doing it from time to time and your CFee will stay low

### Expected behaviour

I have two ideas:
1) When a channel becomes active check if more than [DefaultMaxLinkFeeUpdateTimeout](https://github.com/lightningnetwork/lnd/blob/b137892ceba2ea06d87a751028eeab5549733a44/htlcswitch/link.go#L60) passed since the last fee update. If yes, do a fee update.
2) Also do it after every settled HTLC.

Now, both ideas assume that we *can* (we're the initiator) and *should* ([fees changed by a lot](https://github.com/lightningnetwork/lnd/blob/b137892ceba2ea06d87a751028eeab5549733a44/htlcswitch/link.go#L725)) do a fee update. Otherwise it's a NOP.

### PR DESCRIPTION
**Pull request by rkfg**
## Change Description
See #8790

## Steps to Test
Have a low commitment fee, make the estimated fee high and reconnect the peer. The commitment fee should update.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by rkfg** [comment]
I'm not sure how to proceed from here. I see many tests failing but they don't seem to fail because of this PR.

**Comment by guggero** [comment]
It seems like your code produces a deadlock. All the unit tests are completely stalled and then aborted when the timeout is reached.

**Comment by rkfg** [comment]
It's probably harder to fix than I expected then. I only asked if it can be fixed quickly this way and if it can't then I'd rather wait until someone knowledgeable solves it the right way.

**Comment by rkfg** [comment]
Oh wait, I've got another much simpler idea. We can set the update timer to 0 so it elapses instantly and the relevant code should run at the expected moment.

**Pull request closed without merging**
