### PR TITLE
lint: disable gomnd

### PR DESCRIPTION
**Pull request by guggero**
Fix the annoying "magic number" linter.

### CODE REVIEW

**Review by yyforyongyu — APPROVED** [review]
Bye bye magic numbers. Maybe we could also delete the `nolint:gomnd`?

**Comment by guggero** [comment]
> Bye bye magic numbers. Maybe we could also delete the `nolint:gomnd`?

Ah yes, good point. Done.

**Review by morehouse — APPROVED** [review]
LGTM

**Review by ellemouton — APPROVED** [review]
Yaaaayyy!!

**Pull request merged**
