### PR TITLE
itest: fix payment test error message

### PR DESCRIPTION
**Pull request by de6df1re**
Minor bug fix to payments test to include correct object in test fail message.  

#### Pull Request Checklist

- [x] All changes are Go version 1.15 compliant
- [x] Your PR passes all CI checks. If a check cannot be passed for a justifiable reason, that reason must be stated in the commit message and PR description.
- [X] If this is your first time contributing, we recommend you read the [Code Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
   - [x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
   - [x] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
- [x] For new code: Code is accompanied by tests which exercise both the positive and negative (error paths) conditions (if applicable)
- [x] For bug fixes: If possible, code is accompanied by new tests which trigger the bug being fixed to prevent regressions
- [x] Any new logging statements use an appropriate subsystem and logging level
- [x] For code and documentation: lines are wrapped at 80 characters (the tab character should be counted as 8 characters, not 4, as some IDEs do per default)

### CODE REVIEW

**Comment by de6df1re** [comment]
Very easy review! Anyone willing to take @guggero @Roasbeef @alexbosworth ?

**Review by yyforyongyu — APPROVED** [review]
LGTM👍

**Review by guggero — APPROVED** [review]
Thanks, LGTM :tada: 

Though this either needs an entry in the release notes or the `[skip ci]` suffix in the commit message to signal that you opt out from running all the checks (and also from being mentioned in the release notes).

**Review by alexbosworth — APPROVED** [review]

**Comment by de6df1re** [comment]
Thank you @guggero , I have updated the release notes and included in the PR

**Comment by guggero** [comment]
Thanks! Though it seems now you've included a merge commit in your PR. Can you rebase it please to get rid of that?

**Comment by de6df1re** [comment]
Thanks @guggero ... did rebase, resolved conflict, and I think I've cleaned it up ... let me know if I am mistaken, appreciate your help.

**Pull request merged**
