### PR TITLE
lnrpc: format protos

### PR DESCRIPTION
**Pull request by halseth**
Unformatted protos are aking travis fail.

### CODE REVIEW

**Review by bhandras — APPROVED** [review]

**Comment by halseth** [comment]
Merging to unblock other PRs.

**Comment by cfromknecht** [comment]
@halseth how was this not caught in our builds?

**Comment by guggero** [comment]
Not sure. Maybe the "offending" PR was merged before #4911? We didn't _format_ the protos before, only compile. Now the docker process first formats then compiles. That's probably why all PRs were blocked after #4911 went in.

**Comment by halseth** [comment]
Yeah, I think it was because the offending PR was not rebased on the formatting check before merge.

**Pull request merged**
