### PR TITLE
itest: add parallel flakehunter

### PR DESCRIPTION
**Pull request by guggero**
To make it easier to hunt down the flakes in the integration tests, we add a way to run the same flaky tests multiple times in parallel to try to provoke the flaky behavior. This can also be done for multiple tests in a row if a dependency is expected.

Example:

```
make flakehunter-parallel icase='(data_loss_protection|channel_backup)' backend=neutrino
```

### CODE REVIEW

**Review by bhandras — APPROVED** [review]
LGTM :racehorse:

**Comment by carlaKC** [comment]
Tried out the example command for this - `make flakehunter-parallel icase='(data_loss_protection|channel_backup)' backend=neutrino`. Is it expected to get `invalid value "-n" for flag -runtranche: parse error`? 

I haven't kept up with the recent changes to the itests, so pretty low on context here. The tests still run, but this looked strange to me?
```
/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche-n -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=-n
```

More in depth log dump:
```
 make flakehunter-parallel icase='(data_loss_protection|channel_backup)' backend=neutrino
 Flake hunting neutrino integration tests in parallel.
while [ $? -eq 0 ]; do make itest-parallel tranches=1 parallel=6 icase='(data_loss_protection|channel_backup)' backend='neutrino'; done
 Installing btcd.
cd /tmp && GO111MODULE=on go get -v github.com/btcsuite/btcd@v0.20.1-beta.0.20200903105316-61634447e719
 Building lnd binary
CGO_ENABLED=0 GO111MODULE=on go build -v -tags="dev autopilotrpc chainrpc invoicesrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc rpctest neutrino" -o lntest/itest/lnd-itest -ldflags " -X github.com/lightningnetwork/lnd/build.Commit=v0.11.0-beta-401-gd4361f0ff480c315052a17417ff9596fce1b467f -X github.com/lightningnetwork/lnd/build.CommitHash=d4361f0ff480c315052a17417ff9596fce1b467f -X github.com/lightningnetwork/lnd/build.GoVersion=go1.15.1 -X github.com/lightningnetwork/lnd/build.RawTags=dev,autopilotrpc,chainrpc,invoicesrpc,routerrpc,signrpc,verrpc,walletrpc,watchtowerrpc,wtclientrpc,rpctest,neutrino" github.com/lightningnetwork/lnd/cmd/lnd
 Building itest binary for neutrino backend
CGO_ENABLED=0 GO111MODULE=on go test  -v ./lntest/itest -tags="dev autopilotrpc chainrpc invoicesrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc rpctest neutrino" -logoutput -goroutinedump -c -o lntest/itest/itest.test
 Running tests
rm -rf lntest/itest/*.log lntest/itest/.logs-*
echo -n "$(seq 0 $(expr 6 - 1))" | xargs -P 6 -n 1 -I {} scripts/itest_part.sh {} 1  -test.run="TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup)" -test.timeout=40m
/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche0 -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=0
/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche-n -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=-n
/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche2 -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=2
/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche1 -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=1
/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche3 -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=3
/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/itest.test -test.v -test.run=TestLightningNetworkDaemon/.*-of-.*/.*/(data_loss_protection|channel_backup) -test.timeout=40m -logoutput -goroutinedump -logdir=.logs-tranche4 -lndexec=/Users/carla/go/src/github.com/lightningnetwork/lnd/lntest/itest/lnd-itest -splittranches=1 -runtranche=4
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon
=== RUN   TestLightningNetworkDaemon
invalid value "-n" for flag -runtranche: parse error
```

**Comment by guggero** [comment]
Thanks for the report! I think this is something internal to either `make` or `echo` that works differently on Mac OS with the `-n` flag. But I removed it since it isn't necessary anymore. It should work now.

**Review by carlaKC — APPROVED** [review]
tACK!

**Review by halseth — APPROVED** [review]
LGTM 🌮

**Pull request merged**
