### PR TITLE
channeldb+invoices: refactor invoice logic when updating

### PR DESCRIPTION
**Pull request by Crypt-iQ**
Noticed some things to tidy up here. The AMP copy is added to be consistent with the other invoice copying and can be used in a later PR to surface this information at the rpc layer.

### CODE REVIEW

**Review by yyforyongyu — APPROVED** [review]
LGTM🎉

**Comment by Roasbeef** [comment]
Needs a rebase!

**Review by Roasbeef — APPROVED** [review]
LGTM ⌛️

**Comment by Crypt-iQ** [comment]
rebasaed

**Pull request merged**
