### PR TITLE
CI: update test coverage library go-acc

### PR DESCRIPTION
**Pull request by ffranr**
## Change Description
This change updates the test coverage tool go-acc to its latest release version.

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Review by yyforyongyu — COMMENTED** [review]
Pending a release note, otherwise LGTM👍

**Review by yyforyongyu — COMMENTED** [review]
LGTM, thanks for the PR!

**Comment by ffranr** [comment]
@yyforyongyu thanks for taking a look! Am I ok to merge like this or do I need another review?

**Comment by yyforyongyu** [comment]
@ffranr yeah we need at least two ACKs to merge.

**Review by guggero — APPROVED** [review]

**Review by Crypt-iQ — APPROVED** [review]

**Pull request merged**
