### PR TITLE
docker lnd: add custom params RPCHOST and RPCCRTPATH

### PR DESCRIPTION
**Pull request by eldios**
## Change Description
Add support for custom RPCHOST and TLS CRT PATH needed while working on custom implementations

## Steps to Test
Change should be 100% backward compatible, but it's as easy as creating a new deployment and set the two new variables via environment variables or leave them empty for default values.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Review by ellemouton — COMMENTED** [review]
Hi @eldios! Thanks for this! Looks good!

Just 2 things: 
- Please see [our contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#model-git-commit-messages) for how to structure your commit title and message.
- Please add an entry to the release notes

**Comment by eldios** [comment]
hey @ellemouton do you prefer me to create an additional NOOP commit with the proper commit message and fix the PR title or do you prefer me to create a new one with everything clean?

**Comment by ellemouton** [comment]
You can just amend the existing commit :)

**Comment by eldios** [comment]
@ellemouton unfortunately I opened this PR via the GH web UI and I don't have access now to push from CLI thus no amend feature that I can see 🤦 no worries, I now used my own fork and have a dedicated branch ready to open a new PR. Let me close this one and open a new clean one instead.

**Pull request closed without merging**
