### PR TITLE
router: do not fail MPP if shard runs into a temporary channel failure 

### PR DESCRIPTION
**Pull request by C-Otto**
## Change Description
See #5746 and #5733 for a discussion. On testnet this change allows me to use `SendToRouteV2` to send MPPs and replace failing shards with new shards, so that the total payment amount, over time, reaches the destination.

As far as I understand the code, the failure previously returned is treated as a terminal/final failure, which causes the whole MPP to fail. This is OK/necessary for failures sent by the destination node, for example if the MPP timed out.

However, the omnipresent "temporary channel failure" should not have this influence on the whole MPP.

As I don't know a lot about the internals of lnd, please let this PR serve as an inspiration so that a proper fix can be implemented.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by yyforyongyu** [comment]
I think the reason we want to fail the shard in the first place is that when using `SendToRouteV2`, the route is constructed beforehand, hence the implication is once you specify a route to use `lnd` would only use that route. In which aspect is the opposite of `SendPaymentV2`, where `lnd` takes care of finding the path and constructing the route, retrying a new path if needed.

**Comment by C-Otto** [comment]
> I think the reason we want to fail the shard in the first place is that when using `SendToRouteV2`, the route is constructed beforehand, hence the implication is once you specify a route to use `lnd` would only use that route.

How does this relate to MPPs, where there's more than one route, though?

**Comment by yyforyongyu** [comment]
I think the method focuses more on the route being "right". But yeah it'd be troublesome to play with MPP. I'm thinking maybe we could add a flag to the `sendtoroute` to specify not falling the payment on temp shard error.

**Comment by yyforyongyu** [comment]
Replaced by #6545.

**Pull request closed without merging**
