### PR TITLE
trivial: Fix spelling errors

### PR DESCRIPTION
**Pull request by Rooke**
- Fixes some spelling in code comments and a couple of function names

### CODE REVIEW

**Comment by guggero** [comment]
Thanks for the fixes. Since this touches code (function/variable names), we'll want to run the full CI. Can you please remove the `[skip ci]`? I'll add the `no-changelog` label so the release notes check will be skipped instead.

**Review by guggero — APPROVED** [review]
Thanks, LGTM :tada: (pending a successful CI run).

EDIT: Seems like the linter is complaining.

**Review by yyforyongyu — COMMENTED** [review]
Pending linter fix, otherwise LGTM, thanks for the PR✨

**Comment by guggero** [comment]
Will merge once the final 0.17 version is out.

**Comment by yyforyongyu** [comment]
hmm still has linter issues...

**Comment by Rooke** [comment]
I'll investigate these test errors eventually.

**Comment by guggero** [comment]
> I'll investigate these test errors eventually.

Some of our tests unfortunately are still flaky, so it's very likely not this PRs fault they aren't passing. Since this is just a rename, we expect the linter/compilation and at least one of the unit and integration tests to pass (which it does).

**Review by yyforyongyu — APPROVED** [review]
LGTM🙏

**Comment by Rooke** [comment]
@guggero I'll forgo trying to track down the integration test errors on your advice. Anything else for me to do here?

**Review by saubyk — APPROVED** [review]
Ack

**Pull request merged**
