### PR TITLE
sqlite db backend

### LINKED ISSUE #6176: add SQLite3 backend option
LND 0.14 ships with [support for Postgres](https://github.com/lightningnetwork/lnd/pull/5366) as a database backend. Unfortunately the full potential of Postgres can't be reached because internally LND still uses key/value storage everywhere. 

This means that currently with a Postgres backend, the data that is stored is mostly unreadable. It uses custom serialization/deserialization in several flavours. Any tool that wants to operate on this data needs to implement the exact same serialization methods.

More importantly, maintaining custom serialization code is time-consuming and error-prone. This becomes apparent in an extreme way for database migrations. For each migration, a [frozen copy](https://github.com/lightningnetwork/lnd/tree/master/channeldb/migration21) of the serialization code needs to be added to the code base, to ensure that the migration won't ever break.

Furthermore, a minimalistic kv store like bbolt doesn't offer functionality like indexes (other than on the key) and constraints. Functionality that could be put to good use to guard database integrity in a simple way and make lnd more reliable and faster overall.

These are all advantages that could be unlocked by a step-by-step migration from kv to structured sql. The problem with that migration is that there is still bbolt. If bbolt support needs to stay, a large amount of code needs to be added to have two implementations for every store in the system. This means more potential for bugs and increased maintenance costs.

One way to address this problem is to replace bbolt by SQLite. SQLite is probably one of the [top five most deployed software modules](https://www.sqlite.org/mostdeployed.html) in the world, so reliability shouldn't be an issue.

The initial replacement will stick to the kv model for data. But once fully on the sql platform, it becomes possible to migrate select sub-systems that need it the most to structured sql tables. This migration can happen at the same time for both SQLite and Postgres, so that there won't be duplicate implementations.

Ideas for a light abstraction to iron out the differences in SQL dialect between Postgres and SQLite can be taken from [c-lightning](https://github.com/ElementsProject/lightning/blob/master/wallet/db_common.h).

A first test with LND on SQLite has been [carried out](https://github.com/lightningnetwork/lnd/pull/5366#issuecomment-863203760) successfully.

### PR DESCRIPTION
**Pull request by seejee**
## Change Description
Closes #6176

This PR brings SQLite support to LND. As mentioned in #6176, this PR is a first pass implements sqlite support in a somewhat naive way. 

It builds on the postgres support work that was added recently, however to avoid any premature abstraction, I've intentionally duplicated some things between the `postgres` and `sqlite` kvdb modules. Specifically, the `kvdb/sqlite/readwrite_*.go` files are nearly completely identical to the ones in the `postgres` package, and (thanks for golang's `database/sql` library) could likely be used as-is for future SQL-based kvdb backends. 

The table schema used by sqlite is almost identical to the postgres table schema. It is still very much a key-value approach as opposed to a properly normalized SQL table structure. The intention is that moving to a more normalized table structure could come in the future, along with tooling to migrate from the existing tables or from boltdb, but that would likely come in a future PR.   

We're also making use of the https://github.com/mattn/go-sqlite3 package (which relies on C bindings) because of its maturity, as opposed to the less mature, but pure golang sqlite driver: https://pkg.go.dev/modernc.org/sqlite. If requiring CGO is a problem, then we could attempt to use the modernc sqlite package instead. 

Tasks:
- [x] Get basic SQLite support working via unit tests
- [x] Get integration tests passing with sqlite backend
- [ ] Wire up lncfg support for sqlite
- [ ] Do manual integration testing with the sqlite driver

## Steps to Test
TODO

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by blckbx** [comment]
👍 
Would it be possible to adapt database replication within this inital PR?
Like CLN does:

**Comment by seejee** [comment]
> Would it be possible to adapt database replication within this initial PR?

@blckbx good question! For the first iteration, but I was hoping to keep things simple and not bring that sort of complexity into lnd.

There is a new project (which I've only read about, but haven't used yet) called [litestream.io](https://litestream.io/) that looks promising as a way to replicate sqlite database to another file locally or to cloud storage. That might be a nice solution because litestream runs as a sidecar service and so none of the replication complexity would have to come into `lnd` itself.

Curious to hear your thoughts!

**Comment by blckbx** [comment]
> > Would it be possible to adapt database replication within this initial PR?
> 
> @blckbx good question! For the first iteration, I was hoping to keep things simple and not bring that sort of complexity into lnd.

Absolutely true. Best to move this to another PR/discussion. But to get back to litestream ...

> There is a new project (which I've only read about, but haven't used yet) called [litestream.io](https://litestream.io/) that looks promising as a way to replicate sqlite database to another file locally or to cloud storage. That might be a nice solution because litestream runs as a sidecar process and so none of the replication complexity would have to come into `lnd` itself.
> 

Unfortunately I'm not knowledgable enough to recommend a definite solution. So I just point to the [issue](https://lightning.readthedocs.io/BACKUP.html?highlight=litestream#sqlite-litestream-replication) CLN devs experienced using litestream, namely [crashes](https://github.com/ElementsProject/lightning/issues/4857). In the end they went away from litestream and implemented [direct sqlite3 replication](https://github.com/ElementsProject/lightning/pull/4890) instead.

**Comment by Roasbeef** [comment]
Hey @seejee are you still interested in continuing this PR?

**Comment by Roasbeef** [comment]
Replaced by https://github.com/lightningnetwork/lnd/pull/7251 

Thanks for getting this started!

**Pull request closed without merging**
