### PR TITLE
Added command: Rebalance

### PR DESCRIPTION
**Pull request by ZapUser77**
* Added Rebalance Command
* Added incoming and outgoing args to:
QueryRoutes
FindRoutes
FindPaths
FindPath

### CODE REVIEW

**Comment by ZapUser77** [comment]
Requires https://github.com/lightningnetwork/lnd/pull/1751 to be in first.  (All changes in 1751 are included here.)

**Comment by ZapUser77** [comment]
Solves: https://github.com/lightningnetwork/lnd/issues/1603

**Comment by grunch** [comment]
I tried to compile it but I get an error
```
(38/43) Wrote golang.org/x/net@ae89d30ce0c63142b652837da33d782e2b0a9b25
(39/43) Wrote golang.org/x/crypto@49796115aa4b964c318aad4f3084fdb41e9aa067
(40/43) Wrote github.com/ltcsuite/ltcd@cdab10132e8c6e4a3ffd112dba54791946d28906
(41/43) Wrote github.com/btcsuite/btcd@f899737d7f2764dc13e4d01ff00108ec58f766a9
(42/43) Wrote google.golang.org/genproto@df60624c1e9b9d2973e889c7a1cff73155da81c4
(43/43) Wrote golang.org/x/text@v0.3.0
 Building debug lnd and lncli.
go build -v -tags=debug -o lnd-debug -ldflags "-X main.Commit=08673651129a15aff3c46b5cb080d45fd4990bcc" github.com/lightningnetwork/lnd
github.com/lightningnetwork/lnd/chainntnfs
github.com/lightningnetwork/lnd/keychain
# github.com/lightningnetwork/lnd/keychain
../../lightningnetwork/lnd/keychain/btcwallet.go:181:25: addr.DerivationInfo undefined (type waddrmgr.ManagedPubKeyAddress has no field or method DerivationInfo)
github.com/lightningnetwork/lnd/ticker
github.com/lightningnetwork/lnd/lnrpc
github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify
github.com/lightningnetwork/lnd/chainntnfs/btcdnotify
github.com/lightningnetwork/lnd/chainntnfs/neutrinonotify
# github.com/lightningnetwork/lnd/chainntnfs/bitcoindnotify
../../lightningnetwork/lnd/chainntnfs/bitcoindnotify/bitcoind.go:90:21: undefined: chain.BitcoindConn
../../lightningnetwork/lnd/chainntnfs/bitcoindnotify/driver.go:18:29: undefined: chain.BitcoindConn
Makefile:132: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by ZapUser77** [comment]
It compiles just fine on Travis. 
Those errors aren't related to the code changes in this PR.  Looks like you don't have the correct dependencies?

**Comment by grunch** [comment]
I get it directly from the branch Rebalance on your lnd fork, I just ran `make` and `make install` before, on the same box I had running lnd `f0f5e11b826e020c11c37343bcbaf9725627378b` without any problem, in another directory, not related with your fork

What can it be? I would like to try this feature

**Comment by ZapUser77** [comment]
The make file on my branch doesn't point to it's own branch.  It points to LightningNetwork.  
I'm unfamiliar with GIT, and couldn't get the my local copy of my fork to work right, because it kept trying to use LND's generated proto's instead of mine.  So, what I do is work on a local copy of LND, compile/test, then just move the changes to my branch and upload.

All I can suggest is: get a copy of LND that at the same commit level as my branch, and copy over the changed files.

Probably a horrid way of doing it... but it's the best (only) solution I can think of.

**Comment by halseth** [comment]
Rebalancing can be done by external scripts together with `SendToRoute`

**Pull request closed without merging**
