### PR TITLE
Java grpc example

### PR DESCRIPTION
**Pull request by MaartenTutak**
Hi,

I've created a Java gRPC client example, based on the JS & Python examples.

Thanks

### CODE REVIEW

**Comment by halseth** [comment]
Thanks for this PR! This will make it easier to get started with using `lnd` from Java! Especially proto compilation can be tricky, so this will help a long way 👍 

Are the java options in the proto file needed? I feel it would be nice to keep the protos language agnostic, if possible.

**Comment by MaartenTutak** [comment]
The **java_multiple_files** option shouldn't be necessary but I couldn't get my example to work without it. My IDE had problems referencing the generated class.

The option **java_package** is also optional. It's more of a best practice in Java.
> If no explicit java_package option is given in the .proto file, then by default the proto package (specified using the “package” keyword) will be used. However, proto packages generally do not make good Java packages since proto packages are not expected to start with reverse domain names.

Let me know what you want changed and i'll rewrite my example accordingly.

**Comment by yayitswei** [comment]
This example helped me get up and running from Clojure. I think it will help other folks new to gRPC on the JVM.

**Comment by halseth** [comment]
@MaartenTutak If you could try making this work without modifying the `proto` files, that would be awesome! 😀  

If this turns out to be hard, maybe add to the guide that the users should add these Java specific lines to the proto before continuing?

**Comment by yayitswei** [comment]
For the record, I didn't need the proto changes to get my example working, I just used `lnrpc` as the package name instead of `network.lightning.rpc`.

**Comment by MaartenTutak** [comment]
Removed options from rpc.proto, modified example.

**Comment by halseth** [comment]
Nice, it compile fine here now. However, when running it, it hangs for a few seconds, before it throws an exception, do you know anything about it?
```
$ mvn exec:java -Dexec.mainClass="com.mycompany.app.App"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.13
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 13
[INFO] os.detected.classifier: osx-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ my-app ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/johan/.m2/repository/io/netty/netty-common/4.1.16.Final/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
0375b318cbb1d71ab180d79a74f28862665f4d3c0084ebeb68c239f5ee4ad1f063
[WARNING] thread Thread[threadDeathWatcher-1-1,1,com.mycompany.app.App] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[threadDeathWatcher-1-1,1,com.mycompany.app.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-1,5,com.mycompany.app.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-executor-0,5,com.mycompany.app.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-2,5,com.mycompany.app.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-3,5,com.mycompany.app.App] will linger despite being asked to die via interruption
[WARNING] thread Thread[grpc-default-worker-ELG-2-4,5,com.mycompany.app.App] will linger despite being asked to die via interruption
[WARNING] NOTE: 6 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.mycompany.app.App,maxpri=10]
java.lang.IllegalThreadStateException
    at java.lang.ThreadGroup.destroy (ThreadGroup.java:776)
    at org.codehaus.mojo.exec.ExecJavaMojo.execute (ExecJavaMojo.java:321)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.209 s
[INFO] Finished at: 2018-01-13T14:33:52+01:00
[INFO] Final Memory: 21M/70M
[INFO] ------------------------------------------------------------------------
```
I installed `java` and `maven` using brew, created a project as described [here](https://maven.apache.org/guides/getting-started/), then followed your instructions.

**Comment by MaartenTutak** [comment]
This seems to be related to the Maven Exec plugin. Try the following command. 
`mvn exec:java -Dexec.mainClass="com.mycompany.app.App" -Dexec.cleanupDaemonThreads=false
`

**Comment by halseth** [comment]
Thanks, that worked! 😁 

Any chance you could update the guide with steps for people (as me 😛) not using an IDE? Either by using maven to run it, or a way to run the class directly after `maven command` is done.

**Comment by MaartenTutak** [comment]
Will do!

Op 13 jan. 2018 6:13 p.m. schreef "Johan T. Halseth" <notifications@github.com>:

Thanks, that worked! 😁

Any chance you could update the guide with steps for people (as me 😛) not using an IDE? Either by using maven to run it, or a way to run the class directly after maven command is done.

**Comment by halseth** [comment]
Cool, looks good.  👍 Could you rebase and squash the commits into one?

**Pull request merged**
