### PR TITLE
lnwallet/btcwallet: use CheckTransactionStandard to validate txns before broadcast

### PR DESCRIPTION
**Pull request by Roasbeef**
In this commit, we start to use the `CheckTransactionStandard` function
from the `mempool` package to validate transactions further before
broadcast. This'll help catch instances where we make a massive
transaction, and therefor can't actually propagate it across the
network.

Fixes https://github.com/lightningnetwork/lnd/issues/4760
Fixes https://github.com/lightningnetwork/lnd/issues/6556

### CODE REVIEW

**Comment by Roasbeef** [comment]
Thanks to @ellemouton for making the change to the btcd's `mempool` package to export the func used here.

**Comment by Roasbeef** [comment]
This is a very simple approach that just ensures we won't broadcast these transactions. Ideally we should add this check before this step even, in areas like the funding manager so we can just bail out if we know coin selection is weird or w/e. This is covered in the more encompassing PR here: https://github.com/lightningnetwork/lnd/pull/6400

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Thanks for picking this up! My main question is since the `wallet.PublishTransaction` already handles removing the failed tx from `TxStore`, what's the effect of adding `CheckTransactionStandard` from the caller's view?

https://github.com/btcsuite/btcwallet/blob/af5562928b707e0b56c1e44052ece3205bb66552/wallet/wallet.go#L3743-L3754

By adding `CheckTransactionStandard` here, it does save us from the process of first writing the tx to `TxStore` and later removing it. re #4760, it seems the dangling tx would still be there?

> Ideally we should add this check before this step even, in areas like the funding manager so we can just bail out if we know coin selection is weird or w/e.

I think we need to do this instead. From caller's view the behavior of the new `btcwallet.PublishTransaction` is not changed.

**Comment by Roasbeef** [comment]
> lready handles removing the failed tx from TxStore, what's the effect of adding CheckTransactionStandard from the caller's view?

That's a good question: AFAICT, something is happening where even though we remove the transaction there, it is kept around somewhere and been rebroadcasted again. See this issue as an example: https://github.com/lightningnetwork/lnd/issues/6556.

**Comment by Roasbeef** [comment]
> I think we need to do this instead. From caller's view the behavior of the new btcwallet.PublishTransaction is not changed.

Thought about this a bit more, and it's potentially a bit more error prone: any new `PublishTransaction` call sites need to be aware of this required check, vs just being able to call `PublishTransaction` and know you'll get an error if something is up (which is effectively the same behavior as we have w/ and w/o this PR).

**Comment by Roasbeef** [comment]
Here's a crude diff I used to verify the question above: 
```diff
diff --git a/lnwallet/btcwallet/btcwallet.go b/lnwallet/btcwallet/btcwallet.go
index ff0161d36..455af3126 100644
--- a/lnwallet/btcwallet/btcwallet.go
+++ b/lnwallet/btcwallet/btcwallet.go
@@ -14,7 +14,6 @@ import (
 	"github.com/btcsuite/btcd/btcutil/hdkeychain"
 	"github.com/btcsuite/btcd/chaincfg"
 	"github.com/btcsuite/btcd/chaincfg/chainhash"
-	"github.com/btcsuite/btcd/mempool"
 	"github.com/btcsuite/btcd/txscript"
 	"github.com/btcsuite/btcd/wire"
 	"github.com/btcsuite/btcwallet/chain"
@@ -1059,7 +1058,7 @@ func (b *BtcWallet) PublishTransaction(tx *wire.MsgTx, label string) error {
 	// Note that we just use the time of the last block header here vs
 	// calculating the full median time past (BIP 113). We do this as a
 	// block's timestamp MUST be greater than the MTP of the prior block.
-	bestHash, bestHeight, err := b.chain.GetBestBlock()
+	/*bestHash, bestHeight, err := b.chain.GetBestBlock()
 	if err != nil {
 		return err
 	}
@@ -1074,7 +1073,7 @@ func (b *BtcWallet) PublishTransaction(tx *wire.MsgTx, label string) error {
 	)
 	if err != nil {
 		return fmt.Errorf("tx failed policy checks: %w", err)
-	}
+	}*/
 
 	// TODO(roasbeef): can also use testmempoolaccept here
 
diff --git a/lnwallet/test/test_interface.go b/lnwallet/test/test_interface.go
index 158f0dd99..19612f730 100644
--- a/lnwallet/test/test_interface.go
+++ b/lnwallet/test/test_interface.go
@@ -2055,9 +2055,14 @@ func testPublishTransaction(r *rpctest.Harness,
 		// TODO(roasbeef): we can't use Unwrap() here as TxRuleError
 		// doesn't define it
 		err := alice.PublishTransaction(testTx, labels.External)
-		require.True(
-			t, strings.Contains(err.Error(), "max allowed weight"),
-		)
+		fmt.Println(err)
+		//require.True(
+		//	t, strings.Contains(err.Error(), "max allowed weight"),
+		//	)
+		txHash := testTx.TxHash()
+		tx, err := alice.FetchTx(txHash)
+		require.NoError(t, err)
+		fmt.Println("tx value: ", tx)
 	})
 }
 ```

In this case, after I look up the transaction it isn't present, which confirms the suspicion that we _are_ properly removing the transaction as expected if policy is violated. So I don't think we really need this branch as is, other than the funding manger, which is already covered elsewhere.

**Comment by Crypt-iQ** [comment]
I don't want this one to get lost since it's security-related so reopening it

**Comment by Roasbeef** [comment]
Superseded by #8345

**Pull request closed without merging**
