### PR TITLE
[NANO]: lnwallet: fix OnionBlob to 1366 bytes

### PR DESCRIPTION
**Pull request by ProofOfKeags**
## Change Description
Prior to this commit, In some places we had fixed onions and in others we had dynamic onions. This makes things consistent across the codebase.

## Steps to Test
make unit pkg=lnwallet

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ] [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Cool I like it, plus `array` is "safer" than `slice` since it's always copied by value. Need to fix the CI tho.

**Comment by ProofOfKeags** [comment]
Looks like this is much better to just include in one of the later PRs.

**Comment by carlaKC** [comment]
cACK for updating this!!

> Looks like this is much better to just include in one of the later PRs.

Why?

**Comment by ProofOfKeags** [comment]
I thought I could cherry-pick this commit out of the stream and float it to the beginning independently, but it turns out I simplified a bunch of other code before making this change originally so cherry-picking it resulted in broken builds. It is now part of #8981

**Pull request closed without merging**
