### PR TITLE
Add option to poll for blocks/txs via RPC instead of using ZMQ

### PR DESCRIPTION
**Pull request by orbitalturtle**
Normally Bitcoin Core block notifications come in via ZMQ. This PR adds an option for polling for blocks via RPC when using Bitcoin Core as the backend for LND. To use, the flag --rpcpolling needs to be set for lnd

Requires https://github.com/btcsuite/btcwallet/pull/784

### CODE REVIEW

**Comment by Roasbeef** [comment]
Great PR! Will need to ensure we did an adequate amount of testing for the combined lnd+btcwallet PR to make sure we don't introduce any unexpected regressions in stability/performance, given we've been using the ZMQ code paths since `lnd` was created.

**Comment by Roasbeef** [comment]
One other important difference is that in the event of a re-org, ZMQ as is, will give you each disconnected block, then the set of connected blocks. An implementation based on polling will need to do the extra work to deliver blocks in the same order, so we don't need to modify any of the logic in the chain notifier. 

As is, I don't see the PR updating the notifier or itests to exercise the new operating mode.

**Comment by ellemouton** [comment]
Commenting here mostly to keep review bot happy :)

Did a review of the btcwallet PR. See my latest comment [here](https://github.com/btcsuite/btcwallet/pull/784#pullrequestreview-855693144)

> in the event of a re-org, ZMQ as is, will give you each disconnected block, then the set of connected blocks

Interestingly, this seems to not be the case. ZMQ seems to be height based. So in the event of a reorg, it will just send you the blocks of the heights it has not sent to you yet. Then we externally, [here](https://github.com/btcsuite/btcwallet/blob/master/chain/bitcoind_client.go#L632), notice that it is a re-org and deal with it there. 

I put together a playground & script for verification of this: https://github.com/ellemouton/playgrounds/tree/master/zmq_reorg

**Comment by orbitalturtle** [comment]
Just FYI, I made some changes here based on @ellemouton's feedback on the btcwallet change. Also added some unit tests which further show the blocks being notified in order in the event of a reorg

@Roasbeef for the itests, do you mean adding a new mode which replays all of the itests on top of this new --rpcpolling flag? Like how all the itests are replayed with the --txindex flag? Just want to make sure before I get too into the weeds with that

**Comment by Roasbeef** [comment]
> @Roasbeef for the itests, do you mean adding a new mode which replays all of the itests on top of this new --rpcpolling flag?

Yep, this can effectively be considered a _new_ backend, just like we run the itests for: neutrino, btcd, and bitcoind-zmq.

**Comment by orbitalturtle** [comment]
@Roasbeef That makes sense! Added those tests

**Comment by ellemouton** [comment]
Just posting an update here to keep the bot happy: currently waiting on updates in the dependant PR before reviewing this one

**Comment by ellemouton** [comment]
going to remove my review request too due to #6345

**Comment by ellemouton** [comment]
closing this as it has been replaced by #6345

**Comment by ellemouton** [comment]
closing this as it has been replaced by #6345 which does retain some of the commits from this pr. Thanks again @orbitalturtle !

**Pull request closed without merging**
