### PR TITLE
tools: upgrade linter version to v1.46.2

### PR DESCRIPTION
**Pull request by guggero**
I was getting the following error after cleaning my go mod cache:

```
verifying github.com/mgechev/revive@v1.1.3/go.mod: checksum mismatch
        downloaded: h1:ZZq2bmyssGh8MSPz3VVziqRNIMYTJXzP8MUKG90vZ9A=
        go.sum:     h1:jMzDa13teAuv/KLeqgJw79NDe+1IT0ZO3Mht0vN1Yls=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

This dependency was used by the previous version of `golangci-lint` and an upgrade fixed the problem.
The new version also brings a couple of new rules, one of which we disable and one of which we fix.

### CODE REVIEW

**Comment by guggero** [comment]
@sputn1ck PTAL.

**Review by sputn1ck — APPROVED** [review]
Tested ACK. I was not able to reproduce the checksum mismatch though.

**Review by yyforyongyu — APPROVED** [review]
tACK!

**Comment by guggero** [comment]
> I was not able to reproduce the checksum mismatch though.

I think that only happens if you run `go clean -modcache` and it has to download all modules again. So I wouldn't recommend running that, even though it can free up multiple gigabytes of space on your disk.

**Pull request merged**
