### PR TITLE
error out when non-anchor channels are tried to bump the force close fee.

### PR DESCRIPTION
**Pull request by ziggie1984**
Small bug-fix for the new `bumpforceclose` api.

### CODE REVIEW

**Comment by Roasbeef** [comment]
Perhaps we should target this for 0.18.3? Small bug fix that makes the API harder to use incorrectly.

**Comment by ziggie1984** [comment]
This api call was introduced in the current lnd 19 master branch (https://github.com/lightningnetwork/lnd/pull/8843)

**Review by yyforyongyu — APPROVED** [review]
LGTM 🙏

**Review by Roasbeef — APPROVED** [review]
LGTM 🪡

**Comment by Roasbeef** [comment]
Needs a rebase, then this should be g2g.

**Pull request merged**
