### PR TITLE
Fix comments regarding breach hint and key calculations

### LINKED ISSUE #9169: [docs]: Confusion in code comments regarding the encryption of justice-kit
### Background

I recently started learning about watchtowers. Many [online papers](https://docs.lightning.engineering/the-lightning-network/payment-channels/watchtowers#docs-internal-guid-f1ea8f2e-7fff-62c4-498a-b0e2fb76316f) explain that watchtowers receive from clients the parameters for the revocation transaction (a.k.a justice-kit?) in the following way:

- They receive a "hint" for the breach transaction-id that they are looking for: the first half (16 bytes) of the transaction-id.
- They receive the revocation transaction encrypted, and the encryption-key the full transaction-id of the breach commitment transaction.

This is useful for privacy reasons - no need for the watchtower to know about the revocation transaction in the optimistic use-case, where the breach transaction is not submitted.

However, I've noticed from your code that:

- The hint is calculated from the first half of the `SHA256` of the trasnaction-id: https://github.com/lightningnetwork/lnd/blob/0dd58ee52937a545fd82108678e9a31611b7471f/watchtower/blob/derivation.go#L18-L26
- The encryption-key is calculated from `SHA256(txid || txid)`: https://github.com/lightningnetwork/lnd/blob/0dd58ee52937a545fd82108678e9a31611b7471f/watchtower/blob/derivation.go#L53-L71

This makes sense from a cryptographic viewpoint, because revealing to the watchtower even half of the encryption-key is a bad practice, and its better to have both the hint and the encryption-key *derived* from hashing the transaction-id. However, I think there are some comments left from the old implementation that don't make sense:

- https://github.com/lightningnetwork/lnd/blob/0dd58ee52937a545fd82108678e9a31611b7471f/watchtower/wtclient/backup_task.go#L342-L343 says "Compute the breach key as SHA256(txid)." instead of `SHA256(txid || txid)`, and says nothing about the hint that is also calculated there.
- https://github.com/lightningnetwork/lnd/blob/0dd58ee52937a545fd82108678e9a31611b7471f/watchtower/wtclient/backup_task_internal_test.go#L655 says "Verify that the breach hint matches the breach txid's prefix." even though the hint must match the prefix of the `SHA256` of the full txid, not only the txid's prefix.
- https://github.com/lightningnetwork/lnd/blob/0dd58ee52937a545fd82108678e9a31611b7471f/watchtower/lookout/lookout.go#L203-L208 says "The decryption key for the state update should be computed as SHA256(txid)" instead of `SHA256(txid || txid)`

### PR DESCRIPTION
**Pull request by oren-z0**
Closes #9169

### CODE REVIEW

**Review by ellemouton — APPROVED** [review]
LGTM! Thanks for the contribution 🙏

**Review by yyforyongyu — COMMENTED** [review]
Thanks for the PR! Approved CI run. Note that the commit msg should begin with the package name, so it should be sth like `watchtower: fix comments...`.

**Review by saubyk — APPROVED** [review]
Ack pending YY's comment

**Comment by oren-z0** [comment]
Added prefix "watchtower: " to commit message.

**Review by yyforyongyu — APPROVED** [review]

**Pull request merged**
