### PR TITLE
server: restrict to forwarding only one port when using NAT traversal

### PR DESCRIPTION
**Pull request by wpaulino**
Realized this was meant to be removed after moving the check to `config.go`. I've also modified this to only forward one port, as before we'd forward all the ports `lnd` was listening on, which would be in violation of BOLT 7's requirement of _one_ address of each type.

### CODE REVIEW

**Comment by wpaulino** [comment]
Rebased.

**Comment by cfromknecht** [comment]
rebase 4 final approve?

**Comment by Roasbeef** [comment]
Still relevant?

**Comment by halseth** [comment]
ping @wpaulino

**Pull request closed without merging**
