### PR TITLE
Funding TX Recovery

### PR DESCRIPTION
**Pull request by johng**
For the final part of #386 

Comments:
* Uses CPFP, spending from our change funding point output
* Done some refactoring in fundingmanager + lnd test to prevent code dup 
* Have only been testing this in simnet so far, but the workflow seems correct

This PR is mainly to get initial feedback on how this mechanism will work, would be great to get some comments on my initial ideas.

#### Pull Request Checklist

- [ ] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [ ] All changes are Go version 1.12 compliant
- [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [ ] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and
  logging level
- [ ] Code has been formatted with `go fmt`
- [ ] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [ ] Running `make check` does not fail any tests
- [ ] Running `go vet` does not report any issues
- [ ] Running `make lint` does not report any **new** issues that did not
  already exist
- [ ] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

### CODE REVIEW

**Comment by halseth** [comment]
How do we handle stuck funding transactions with no change output?

Also, note that there is a fundingmanager refactor PR up: #1910

**Comment by johng** [comment]
Then we should not entering recovery mode, and just continue to note. Will need to implement that

**Comment by johng** [comment]
> How do we handle stuck funding transactions with no change output?

Currently we fail the recovery workflow, added a change to prevent entering it in the first place

**Comment by johng** [comment]
@halseth I've rebased ontop of your changes in #1910

**Comment by halseth** [comment]
Now that we have fee bumping added, we should explore reusing that logic to bump the funding tx fee: https://github.com/lightningnetwork/lnd/pull/3140

**Comment by halseth** [comment]
After discussing this a bit we have come to the conclusion we _do not_ want to introduce more persistent state during the funding process. Instead we should let the fundingmanager 
1) unlock the coins after a timeout, making them spendable in other transactions. 
2) In combination with something like #1755  this should allow it to gracefully fail the channel.

To bump the fee on an unconfirmed channel manually, the current bump fee logic can be used.

I will add this to the issue, feel free to open a new PR for 1).

**Pull request closed without merging**
