### PR TITLE
fundingmanager+channeldb: export and use WriteOutpoint

### PR DESCRIPTION
**Pull request by Crypt-iQ**
Gets rid of the utxonursery encoding in favor of the channeldb variant and has a migration to go with it for nodes with pending channels in the fundingmanager. A small change but helps us get closer to refactoring the fundingmanager.

Conflicts with #4642

### CODE REVIEW

**Comment by Roasbeef** [comment]
Hmm, is this absolutely necessary? Just from a PoV of minimizing migrations in general....

**Comment by Crypt-iQ** [comment]
> Hmm, is this absolutely necessary? Just from a PoV of minimizing migrations in general....

Not necessary but otherwise we have to export this varint encoding somewhere and maintain it.

**Comment by halseth** [comment]
Could we copy the encoding into the funding manager itself?

**Comment by Crypt-iQ** [comment]
> Could we copy the encoding into the funding manager itself?

Yeah

**Comment by Crypt-iQ** [comment]
What package should the exported function go in? `channeldb` perhaps? It's also used elsewhere in `lnd` so it doesn't make sense in my opinion to move it to `fmgr`.

**Comment by halseth** [comment]
> What package should the exported function go in? channeldb perhaps? It's also used elsewhere in lnd so it doesn't make sense in my opinion to move it to fmgr.

If the idea is to get rid of a dependency to make the fundingmanager easier to move later, I would just copy these few lines of code in there. Simple, and we can forget about the other parts of the codebase that uses this for now.

**Pull request closed without merging**
