### PR TITLE
kvdb+watchtower: fix unreachable code

### PR DESCRIPTION
**Pull request by undefinedor**
## Change Description
fix unreachable code 

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
Thanks @undefinedor for the PR! The changes look good to me. Thanks! But please review our contribution guidelines on how to write commit messages.

**Comment by mohamedawnallah** [comment]
Thanks @undefinedor for the PR! The changes look good to me but please review our contribution guidelines on how to write commit messages.

**Comment by mohamedawnallah** [comment]
I wonder if we could detect this automatically in our CI linting to ensure it doesn't happen again (less likely at least). I've found [go vet package ](https://pkg.go.dev/cmd/vet) which is capable of detecting these kinds of issues.

For instance, running go vet ./... on all packages available revealed several issues, including unreachable code analysis:
``` 
➜  lnd git:(master) go vet ./...
# github.com/lightningnetwork/lnd/internal/musig2v040
# [github.com/lightningnetwork/lnd/internal/musig2v040]
internal/musig2v040/musig2_test.go:402:2: struct field tag `json:"expected_error` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
internal/musig2v040/musig2_test.go:1065:6: call to (*testing.T).Fatalf from a non-test goroutine
internal/musig2v040/musig2_test.go:1069:6: call to (*testing.T).Fatalf from a non-test goroutine
# github.com/lightningnetwork/lnd/contractcourt
# [github.com/lightningnetwork/lnd/contractcourt]
contractcourt/briefcase_test.go:354:20: assignment copies lock value to contestTimeout: github.com/lightningnetwork/lnd/contractcourt.htlcTimeoutResolver contains sync.Mutex
contractcourt/briefcase_test.go:359:20: assignment copies lock value to contestSuccess: github.com/lightningnetwork/lnd/contractcourt.htlcSuccessResolver contains sync.Mutex
# github.com/lightningnetwork/lnd/watchtower/wtclient
# [github.com/lightningnetwork/lnd/watchtower/wtclient]
watchtower/wtclient/session_negotiator.go:338:3: unreachable code
watchtower/wtclient/session_negotiator.go:397:2: unreachable code
```

**Comment by undefinedor** [comment]
> I wonder if we could detect this automatically in our CI linting to ensure it doesn't happen again. I've found [go vet package ](https://pkg.go.dev/cmd/vet) which is capable of detecting these kinds of issues.
> 
> For instance, running `go vet ./...` on all packages available revealed several issues, including unreachable code analysis:
> 
> ```
> ➜  lnd git:(master) go vet ./...
> # github.com/lightningnetwork/lnd/internal/musig2v040
> # [github.com/lightningnetwork/lnd/internal/musig2v040]
> internal/musig2v040/musig2_test.go:402:2: struct field tag `json:"expected_error` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
> internal/musig2v040/musig2_test.go:1065:6: call to (*testing.T).Fatalf from a non-test goroutine
> internal/musig2v040/musig2_test.go:1069:6: call to (*testing.T).Fatalf from a non-test goroutine
> # github.com/lightningnetwork/lnd/contractcourt
> # [github.com/lightningnetwork/lnd/contractcourt]
> contractcourt/briefcase_test.go:354:20: assignment copies lock value to contestTimeout: github.com/lightningnetwork/lnd/contractcourt.htlcTimeoutResolver contains sync.Mutex
> contractcourt/briefcase_test.go:359:20: assignment copies lock value to contestSuccess: github.com/lightningnetwork/lnd/contractcourt.htlcSuccessResolver contains sync.Mutex
> # github.com/lightningnetwork/lnd/watchtower/wtclient
> # [github.com/lightningnetwork/lnd/watchtower/wtclient]
> watchtower/wtclient/session_negotiator.go:338:3: unreachable code
> watchtower/wtclient/session_negotiator.go:397:2: unreachable code
> ```

You're correct.
I've eliminated all unreachable code.
Next, I'll submit another pull request to update the CI linting.

**Review by mohamedawnallah — COMMENTED** [review]
Thanks @undefinedor! The changes look good to me 🎉!

**Review by mohamedawnallah — APPROVED** [review]
Thanks @undefinedor! The changes look good to me 🎉!

**Review by guggero — APPROVED** [review]
LGTM, thanks!

**Review by ellemouton — APPROVED** [review]
Lgtm! nice clean up :) 

Pls add a release notes entry 🙏

**Comment by guggero** [comment]
> You're correct. I've eliminated all unreachable code. Next, I'll submit another pull request to update the CI linting.

We do have a linter (`golangci-lint`, check `.golangci.yml` in the repo). But that only looks at new code starting at a specific commit, because previous code would generate way too many warnings.

But if you want, you can comment out the `  new-from-rev: 8c66353e4c02329abdacb5a8df29998035ec2e24` part and run the linter locally. The output will likely be massive and a lot of non-critical stuff.
PRs for linter fixes for old commits are accepted, if they're easy to review and small risk. Ideally we'd be able to remove the `new-from-rev` at some point, but don't think that's going to happen any time soon.

**Pull request merged**
