### PR TITLE
Confirm.correctedFirstTransaction

### PR DESCRIPTION
**Pull request by zachwylde00**
#### Pull Request Checklist

- [√ ] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [√ ] All changes are Go version 1.12 compliant
- [√ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [ √] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [ √] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [ √] Any new logging statements use an appropriate subsystem and
  logging level
- [√ ] Code has been formatted with `go fmt`
- [ √] Protobuf files (`lnrpc/**/*.proto`) have been formatted with
  `make rpc-format` and compiled with `make rpc`
- [ √] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [√ ] Running `make check` does not fail any tests
- [ √] Running `go vet` does not report any issues
- [ √] Running `make lint` does not report any **new** issues that did not
  already exist
- [√ ] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [√ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

### CODE REVIEW

**Comment by zachwylde00** [comment]
what do I do next?

**Comment by cfromknecht** [comment]
@zachwylde00 if you have an issue, [file an issue](https://github.com/lightningnetwork/lnd/issues/new).

**Comment by zachwylde00** [comment]
no, no issues but I don't know if I did it correctly it wasn't allowed to
finish it was closed before it could complete on the second run I don't see
any reason to piss anyone off by creating an issue. it's only money.

**Comment by zachwylde00** [comment]
okay it was supposed to be executable the only error showed on the log was
exit with a 2, which was correct why wasn't it executable?

**Comment by zachwylde00** [comment]
also I am testing my system for transaction configuration I thought I had
everything correct but according to you I did not.  So, please tell me
where I went wrong I do not want an app or anything that configures
incorrect data that has ni purpose what so ever to me.

**Pull request closed without merging**
