### PR TITLE
Removed deprecated interfacer linter

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Removed the deprecated interfacer linter from being called for linting.

https://github.com/lightningnetwork/lnd/issues/5741

### CODE REVIEW

**Review by guggero — COMMENTED** [review]
Looks good to me, thanks!
I wonder if we should remove the ` // nolint:interfacer` comments we have in some of the files, mostly because of false positives?

**Comment by naveensrinivasan** [comment]
> Looks good to me, thanks!
> I wonder if we should remove the ` // nolint:interfacer` comments we have in some of the files, mostly because of false positives?

I can remove those.

**Comment by naveensrinivasan** [comment]
> > Looks good to me, thanks!
> > I wonder if we should remove the ` // nolint:interfacer` comments we have in some of the files, mostly because of false positives?
> 
> I can remove those.

I have removed them. Let me know if this looks good. Thanks

**Review by bhandras — APPROVED** [review]
LGTM, thanks :bulb:

**Review by guggero — COMMENTED** [review]
Changes look good to me, thanks. But I think we should split the pure formatting changes into their own commit and prefix the commit messages according to the contribution guideline.

**Comment by guggero** [comment]
Replaced by https://github.com/lightningnetwork/lnd/pull/6080 to speed up review process. Original commit author was preserved, thank you for your contribution.

**Pull request closed without merging**
