### PR TITLE
harness: remove killed nodes from active nodes

### PR DESCRIPTION
**Pull request by bhandras**
Fix for https://github.com/lightningnetwork/lnd/issues/5491

### CODE REVIEW

**Review by carlaKC — APPROVED** [review]
Nice fix!

**Review by guggero — APPROVED** [review]
Ooooh, nice find!

tACK, ran this 3 times through my itest flake finder setup and didn't get a single failure :100: 

What do you think about adding this to the embedded `etcd` code in `kvdb/etcd/embed.go` to reduce the noise of the itest a bit?

```
	cfg.Debug = false
	cfg.Logger = "zap"
	cfg.LogLevel = "error"
```
Non-blocking for this PR of course!

**Comment by bhandras** [comment]
> Ooooh, nice find!
> 
> tACK, ran this 3 times through my itest flake finder setup and didn't get a single failure 
> 
> What do you think about adding this to the embedded `etcd` code in `kvdb/etcd/embed.go` to reduce the noise of the itest a bit?
> 
> ```
> 	cfg.Debug = false
> 	cfg.Logger = "zap"
> 	cfg.LogLevel = "error"
> ```
> 
> Non-blocking for this PR of course!

Yes indeed, this is a good idea, added as a separate commit. This excessive logging has been bothering me too and added the same fix to another PR too (https://github.com/lightningnetwork/lnd/pull/5513/commits/5745fa52deadc0e94d8794df8e12ea49abe48a37).

**Comment by guggero** [comment]
This fixes the `etcd` failover test as advertised. Confirmed that Travis fails with other known flags.

**Pull request merged**
