### PR TITLE
"Production" Docker Image

### PR DESCRIPTION
**Pull request by tyzbit**
This PR satisfies the auto-build functionality desired in #722 without changing anything in the `docker` folder.  This allows development and testing to continue to build and use images locally, but external users get a very lean Docker image they can use.  The size difference is appreciable.

```
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
lnd                            latest              3634dcf5df68        17 seconds ago      1.19GB
lnd-single                     latest              b295cc248447        30 minutes ago      56MB
```

Right before merging this PR, an Automated Build repository should be configured on the appropriate account ([lightningnetwork](https://hub.docker.com/r/lightningnetwork/)?) on Docker Hub with the name of `lnd` in order to match documentation.

I see there are already some repositories created, however *I think* best practice for Docker is to have a single repository and different tags for different architectures.  The included image is based off of Alpine, but in the future we could extend into multiple Dockerfiles (example: ARM support, or being Ubuntu based).

So in this proposed scenario, `lightningnetwork/lnd:latest` would be `alpine`, but `lightningnetwork/lnd:ubuntu` would be an ubuntu-based image, for example.

(With thanks to @alingenhag for https://github.com/f-u-z-z-l-e/docker-lnd/ from which I borrowed heavily)

### CODE REVIEW

**Comment by guggero** [comment]
I think the changes of this PR are great and the use of a builder image and the resulting tiny production image with all the options exposed as environment variables is fantastic!

But something does not look right with your commit history. Especially the two merge commits at the beginning are very strange. I think you need to properly rebase everything. Drop me a line over at Slack if you need assistance, I have the same username there.

**Comment by tyzbit** [comment]
I was doing something weird with my fork of `lnd` (PRing against master rather than checking out upstream), I've rebased the changes and squashed the commits, though they're not perfect as to what files were changed.

**Comment by erkarl** [comment]
Just tested it out with 2 docker containers. Works great.

**Comment by Roasbeef** [comment]
Agreed w.r.t re-creating all the arguments. I think as is, since we're using a CMD as an entrypoint, we should be able to pass the arguments directly?

**Comment by tyzbit** [comment]
I'm not in a spot to update the PR, but I did create `tyzbit/lnd:alt-cmd` for everyone to test that changes the command from `lncli` to `lnd`, which allows for this to work:

```
docker run --name testnet-neutrino tyzbit/lnd:alt-cmd --bitcoin.active --bitcoin.testnet --bitcoin.node=neutrino --neutrino.connect=faucet.lightning.community
```
I will update the PR as soon as I can, as long as there aren't any concerns.

This has the benefit of allowing literal commandline options or environment variables, whichever the user prefers.

**Comment by tyzbit** [comment]
Per discussion with @Roasbeef on IRC, updated PR to only allow command-line options.

Updated Docker documentation to reflect the change and also added some information about volumes.

**Pull request merged**
