### PR TITLE
Added CBC and SHA256 crypto algorithms

### PR DESCRIPTION
**Pull request by johng**
Added the new more secure Crypto algorithms available in Go 1.8

As per [issue](https://github.com/lightningnetwork/lnd/issues/281)

### CODE REVIEW

**Comment by halseth** [comment]
@aakselrod

**Comment by aakselrod** [comment]
@johng, this looks good! One more request. Please add the following as well: `tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305` and `tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305` (I think I left these out of the issue). That should be it - then you can rebase and we'll merge. Thanks!

**Comment by johng** [comment]
@aakselrod  Added

**Comment by aakselrod** [comment]
@johng looks like during the squash, it undid the merge you did earlier and now there are 34 files being changed by the PR.

**Comment by johng** [comment]
@aakselrod  should be fine now? I readded the changes after merging the branch

**Pull request merged**
