### PR TITLE
channeldb+multi: export {Write,Read}Outpoint, new {Write,Read}VarOutPoint

### PR DESCRIPTION
**Pull request by Crypt-iQ**
Removes duplicate `writeOutpoint` and `readOutpoint` function in `utxonursery.go`.

### CODE REVIEW

**Comment by halseth** [comment]
Does this work? Seems like the method in `channeldb` is different from the one from nursery.

**Comment by Crypt-iQ** [comment]
So I think if we want them to conform we need a db migration?

**Comment by halseth** [comment]
Not sure if this change is worth it, given that we might want to phase out the old encoding (and as you say that would require a migration).

**Comment by Crypt-iQ** [comment]
This is needed for isolating the fundingmanager in its own package since it uses the old extra byte encoding. So migration is better and I'll go with that approach.

**Pull request closed without merging**
