### PR TITLE
Add more details on using macaroons with GRPC.

### PR DESCRIPTION
**Pull request by brndnmtthws**
This addresses #730.

### CODE REVIEW

**Comment by halseth** [comment]
Thank you for the PR!

I think the macaroon readme should be language agnostic, would it be better to modify the Java example to include this?

**Comment by brndnmtthws** [comment]
That makes sense. I didn't even see the Java example in there. I'll move this over and update accordingly.

**Comment by brndnmtthws** [comment]
Also, wouldn't it make sense to move those code samples to a separate repo? Then we can just link to them. That way people can just clone the repos to get started.

**Comment by brndnmtthws** [comment]
I moved the code sample into the Java GRPC example, and added the curl example from #730.

**Comment by brndnmtthws** [comment]
@Roasbeef I think you were looking at an outdated diff.

Here's the updated PR with 2 separate commits.

**Comment by brndnmtthws** [comment]
Regarding travis: that's weird, I use it on a bunch of other projects without any trouble.

**Comment by brndnmtthws** [comment]
@Roasbeef oh you're right, I did get banned:

screen shot 2018-03-01 at 08 16 47

That's what I get for contributing to one of these shady bitcorn projects 😛

**Pull request merged**
