### PR TITLE
chore: Update minimum golang version to 1.13

### PR DESCRIPTION
**Pull request by jakesyl**
### Description

6250ed1cf1670fea11ddff1c330a26193c3f0915 from #4141 uses [http.NewRequestWithContext](https://github.com/lightningnetwork/lnd/blame/87880c0d56937f2380acee37910492b2fc7b910f/lnrpc/websocket_proxy.go#L97). This will not compile with go 1.12 since this method was only introduced in go 1.13 [see changelog entry](https://golang.org/doc/go1.13).

Alternatively, a PR can be opened to remove the usage of this method.

#### Pull Request Checklist

- [x] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [ ] ~All changes are Go version 1.12 compliant~ see pr description
- [x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [x] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [x] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [x] Any new logging statements use an appropriate subsystem and
  logging level
- [x] Code has been formatted with `go fmt`
- [x] Protobuf files (`lnrpc/**/*.proto`) have been formatted with
  `make rpc-format` and compiled with `make rpc`
- [x] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [x] Running `make check` does not fail any tests
- [x] Running `go vet` does not report any issues
- [x] Running `make lint` does not report any **new** issues that did not
  already exist
- [ ] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

### CODE REVIEW

**Comment by cfromknecht** [comment]
we're still seeing issues with go1.14 on 32-bit ARM, as such idt we can bump this yet. we may have to consider removing the use of `NewRequestWithContext` for 0.11 if those issues are not resolved in time.

**Comment by jakesyl** [comment]
@cfromknecht got it, so in that case it wouldn't be upgraded. The current issue is my `go.mod` will pass but the build will fail because of `http.NewRequestWithContext` on a fresh clone. I'm happy to open up a new PR removing the `http.NewRequestWithContext`, but right now this is failing on fresh clones

**Comment by Roasbeef** [comment]
@jakesyl the issue with ARM appears to be resolved now with #4408, so I think once this is rebased it can land.

**Comment by jakesyl** [comment]
will do

**Comment by jakesyl** [comment]
Looks like this is still failing

**Comment by Roasbeef** [comment]
Ah, so you need to add that line to the referenced file (log error white list) and then things should pass. That new check is an attempt to tend towards only using the `Errorf` logging level for really serious errors.

**Pull request merged**
