### PR TITLE
itest: mine blocks on tower session assertion failure

### PR DESCRIPTION
**Pull request by ellemouton**
In the tower session itest, we make sure to mine blocks on session count assertion failure. This required because the session count is expected to change only when 2 things both happen: 1) a closable session is queued and 2) a new block notification comes through _after_ the session has been queued. Only then will it be deleted. So we need to do this to prevent the case where all the block notifications are consumed _before_ the session is queued for deletion. This flake tended to happen in the windows itest.

This same pattern has been used previously in other watchtower itests. 

An example of the flake failure can be seen [here](https://github.com/lightningnetwork/lnd/actions/runs/8333246594/job/22804251071?pr=8159)

### CODE REVIEW

**Comment by ellemouton** [comment]
unforch there are still other windows flakes

**Review by bhandras — APPROVED** [review]
LGTM 🌊 Thanks for the fix!! 🏄

**Comment by ellemouton** [comment]
here is a link to a passing windows test with these changes: https://github.com/ellemouton/lnd/actions/runs/8341950322

Previously it would very consistently fail

**Review by guggero — APPROVED** [review]
Very nice, thanks a lot for the fix!
Will merge as soon as we see the test pass in CI.

**Pull request merged**
