### PR TITLE
Retire obsolete Neutrino RPC

### PR DESCRIPTION
**Pull request by ffranr**
## Change Description

This PR retires Neutrino RPC endpoints which retrieve chain data (`GetBlock` and `GetBlockHash`). These endpoints were made obsolete by the new `ChainKit` RPC endpoints. 

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by ErikEk** [comment]
@ffranr Still working on this?

**Comment by ffranr** [comment]
@ErikEk I'm not actively working on this right now. I think that I could narrow its scope and land the first complete commit. I'll investigate tomorrow and figure out what to do with this PR.

**Comment by ErikEk** [comment]
@ffranr I would remove the verbose parameter and just return the header data + the raw block data like you have. If someone want to use the verbose parameter they could request it from bitcoind or btcd instead. Then we add getblockheader to the chain subserver for users who doesn't want to request the full block data. What do you think?

**Comment by ErikEk** [comment]
@ffranr I could finish it with you as co-author if you are busy.

**Comment by ffranr** [comment]
The endpoints in question have now (on `master`) been tagged with "depreciated".

**Pull request closed without merging**
