### PR TITLE
contractcourt: cancel invoices that timeout on chain

### LINKED ISSUE #4987: Invoice HTLC shards should not remain in ACCEPTED state after cancelation
### Background

As currently designed in the invoices RPC: invoices enter an ACCEPTED state when HTLCs are held but not yet settled with the preimage. This is designed to allow a caller to know when HTLCs are safely held and that they can settle with a preimage.

However if the preimage is never provided, the HTLCs will never leave this ACCEPTED state even though after a timeout they will no longer be able to be claimed

Ideally the surfaced state of the HTLC would indicate a different state to the RPC caller to disambiguate between "able to be settled" and "no longer able to be settled"

### Your environment

* LND 0.12.0-beta

### PR DESCRIPTION
**Pull request by carlaKC**
This PR adds logic to contractcourt to cancel invoices when their htlcs timeout on chain. Previously, we would simply resolve the htlc without checking whether it was for one of our invoices, so we would not update invoices state accordingly. It only takes this action for invoices (not forwards), so that there are no unexpected interactions between forwards/invoices with the same hash.

This change fixes #4987 by cancelling the invoice (and its htlcs) once we reach our timeout on chain, and #4587 because the cancelled invoice can't be settled after timeout.

Our existing itest is modified to assert that this bug occurs, then updated with the fix. Since travis doesn't run on each commit, I've opened PRs on my own fork to demonstrate that the incremental changes to the itest pass: 
- Refactoring in [a78acd6](https://github.com/carlaKC/lnd/pull/9) 
- Reproduce in [3b374da ](https://github.com/carlaKC/lnd/pull/8)
(have been running into docker rate limiting issues with these, will address)

### CODE REVIEW

**Comment by joostjager** [comment]
I am thinking about this new call from contract court to invoice registry. What currently happens is that an hodl invoice isn't settled, causing the channel to be force-closed, which leads to the resolver marking the invoice as cancelled.

What would happen if the preimage was supplied right before the invoice is marked as cancelled by the resolver? IIRC the cancel call would fail and leave the invoice in the settled state, even though the htlc was lost.

One future step might be to cancel the htlc in the link just before the channel is going to force-close. The htlc is lost and the invoice cancelled and the force-close isn't going to change anything about that. Of course this is only possible if the peer is online.

I think it may be worth considering how just-in-time cancellation would interact with the changes in this PR. The general approach so far has been take keep the invoice registry in control. Making the invoice registry follow in certain cases could cause problems with race conditions, such as the one described above.

Suppose just-in-time cancellation would be implemented in the invoice registry, then invoices are always cancelled before they expire and we go to chain. That would make it unnecessary to modify the resolver, I think.

**Comment by carlaKC** [comment]
> What would happen if the preimage was supplied right before the invoice is marked as cancelled by the resolver? IIRC the cancel call would fail and leave the invoice in the settled state, even though the htlc was lost.

Also been thinking about that possible race for this PR. I think one way to handle that a bit better would be to remove this [early timeout check](https://github.com/lightningnetwork/lnd/blob/4af24158c405db5482aeb63cdc7d1244d3cc0064/contractcourt/htlc_incoming_contest_resolver.go#L120), and then leave the resolver to only [handle a settle or timeout](https://github.com/lightningnetwork/lnd/blob/4af24158c405db5482aeb63cdc7d1244d3cc0064/contractcourt/htlc_incoming_contest_resolver.go#L303), so that we don't end up in the case where the resolver tries to cancel after we've settled. 

> One future step might be to cancel the htlc in the link just before the channel is going to force-close. 

I think that this would be a reasonable addition for hodl invoices. While they are an advanced feature, it's not ideal to have mass force closures if you don't cancel back in time. Perhaps just on an opt-in basis to give people the option. 

> Suppose just-in-time cancellation would be implemented in the invoice registry, then invoices are always cancelled before they expire and we go to chain. That would make it unnecessary to modify the resolver, I think.

I floated some other approaches in the [original issue](https://github.com/lightningnetwork/lnd/issues/4987#issuecomment-800091710), including a block-based invoice expiry watcher. That could be one way of keeping control with the registry?

**Comment by joostjager** [comment]
>Also been thinking about that possible race for this PR. I think one way to handle that a bit better would be to remove this early timeout check, and then leave the resolver to only handle a settle or timeout, so that we don't end up in the case where the resolver tries to cancel after we've settled.

Doesn't that then keep the resolver alive and the leave the invoice in the `accepted` state even though the htlc is long gone on-chain?

>I think that this would be a reasonable addition for hodl invoices. While they are an advanced feature, it's not ideal to have mass force closures if you don't cancel back in time. Perhaps just on an opt-in basis to give people the option.

Yes, it is tricky now. If your app is down and you can't get it up in time, channels will start to force-close. But why make it opt-in? Not force-closing seems to be always preferable to force-closing?

>I floated some other approaches in the original issue, including a block-based invoice expiry watcher. That could be one way of keeping control with the registry?

Yes, that option 1 is indeed what I always had in mind as a solution to fix this. We've had earlier design challenges too where we needed to decide which component is in charge. By always driving from the invoice registry, it became possible to get rid of the race conditions that were threatening us then.

**Comment by carlaKC** [comment]
> Doesn't that then keep the resolver alive and the leave the invoice in the `accepted` state even though the htlc is long gone on-chain?

I don't think so, just makes sure that we're handling expiry/settles in a single select rather than having an early expiry check where we don't consider our hodl subscription. But I think we can still get in a bad state if we expire and get registry update at the exact same time.

> But why make it opt-in? Not force-closing seems to be always preferable to force-closing?

Just because it would be a behaviour change, don't know what you may break if you start cancelling invoices which previously could be settled on-chain if needed.

> Yes, that option 1 is indeed what I always had in mind as a solution to fix this. We've had earlier design challenges too where we needed to decide which component is in charge. By always driving from the invoice registry, it became possible to get rid of the race conditions that were threatening us then.

Going to look into this approach, thanks for the insight on this one!

**Comment by joostjager** [comment]
>Just because it would be a behaviour change, don't know what you may break if you start cancelling invoices which previously could be settled on-chain if needed.

But could they be settled on-chain? An invoice would only be cancelled once the underlying accepted htlc expires. So also on-chain, it has expired by then. Or do you mean that there is still an option to win the race on-chain? The current behavior is to not enter that race anyway, so is it really a behavioral change other than the prevention of a force-close without any side-effects?

**Comment by carlaKC** [comment]
replaced by #5206

**Pull request closed without merging**
