### PR TITLE
mod+build: bump btcd version to v0.23.3 and bump lnd version to v0.15.4-beta

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightningnetwork/lnd/issues/7096.

### CODE REVIEW

**Review by bhandras — APPROVED** [review]

**Review by GeorgeTsagk — APPROVED** [review]

**Review by ellemouton — APPROVED** [review]

**Review by positiveblue — APPROVED** [review]

**Review by Crypt-iQ — APPROVED** [review]

**Comment by pinheadmz** [comment]
ACK thanks and thanks @ellemouton 

```
    "version": "0.15.4-beta commit=v0.15.3-beta-3-g64f20b6b5",
    "commit_hash": "64f20b6b5b408c32e49ea2d432e2f8ec866e0b8e",
...
    "block_height": 761262,
    "block_hash": "00000000000000000001e5923f47b41c9f3f0daac869b0e37442a1bdc4ca39bc",
    "best_header_timestamp": "1667304928",
    "synced_to_chain": true,
    "synced_to_graph": true,
```

**Review by sangaman — APPROVED** [review]
Chain sync works for me on testnet using `64f20b6b5b408c32e49ea2d432e2f8ec866e0b8e` on linux

**Comment by C-Otto** [comment]
Can confirm, btcd 0.23.3 fixed it for me (which I added manually, unrelated to this PR).

**Comment by Jossec101** [comment]
Does this CI/CD process release a new Docker image?

Superb job guys!

**Comment by C-Otto** [comment]
Fixed version is available here: https://github.com/lightningnetwork/lnd/releases/tag/v0.15.4-beta

**Pull request merged**
