### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by antonilol**
## Change Description
Description of change / link to associated issue.

found some typos while trying to debug an issue

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Thanks for the PR. Please read our contribution guideline regarding how to write commit messages. Also `iff` means `if and only if`, not a typo.

**Comment by antonilol** [comment]
> Also iff means if and only if, not a typo.

Makes sense

Will be fixing this later today

**Comment by yyforyongyu** [comment]
Please note this requirement,
> - [ ] [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or [skip ci] in the commit message for small changes.

**Review by yyforyongyu — APPROVED** [review]
LGTM

**Review by guggero — APPROVED** [review]
LGTM, thanks :tada:

**Pull request merged**
