### PR TITLE
release: create branch for v0.18.4-beta.rc1

### LINKED ISSUE #9173: [release]: Cherry Pick Commits for LND v0.18.4 Release
## Description:

Create a new branch off of `lnd` v0.18.3 and cherry pick desired commits for the v0.18.4 release.

To facilitate this process, use the script: https://gist.github.com/Roasbeef/b76730b6e5548a4eb2813da0bcf4d82c. 
Note: occasional rebase failures may require manual intervention via a no-ff merge.

## Task:

* Create new branch from `lnd` v0.18.3
* Cherry pick desired commits using the provided script
* Resolve any rebase conflicts or perform manual no-ff merges as needed

### PR DESCRIPTION
**Pull request by guggero**
Preparation PR to kick off the `v0.18.4-beta.rc1` release.

Closes #9173.

This PR includes rebased versions of the following PRs (in order):
 - #8996 
 - #8520
 - #9007 
 - #9025 
 - #9030
 - #9044 
 - #9049
 - #8981 
 - #9072 
 - #9095 
 - #9134 
 - #8960 
 - #9154
 - #9187
 - #9059
 - #9195
 - #9197
 - #9199
 - #9223
 - #9062
 - #9084
 - #9082
 - #9194
 - #9272
 - #9253
 - #9288

NOTE: Replaces https://github.com/lightningnetwork/lnd/pull/9174 to have branch in upstream repo.

### CODE REVIEW

**Comment by guggero** [comment]
Added https://github.com/lightningnetwork/lnd/pull/9187.

**Comment by guggero** [comment]
Added #9195.

**Comment by guggero** [comment]
Added #9197.

**Comment by guggero** [comment]
Added #9199.

**Comment by guggero** [comment]
Added #9223.

**Comment by Roasbeef** [comment]
We'll need this PR in this branch as well: https://github.com/lightningnetwork/lnd/pull/9062

**Comment by guggero** [comment]
Added #9062 and updated its milestone to 0.18.4.

**Comment by Roasbeef** [comment]
Pushed up a version of this w/ the HTLC PR to my fork (temp): https://github.com/lightningnetwork/lnd/compare/0-18-4-branch-rc1...Roasbeef:lnd:0-18-4-branch-rc1?expand=1

**Comment by guggero** [comment]
Added #9194. Ready for full review now!

**Comment by Roasbeef** [comment]
Added https://github.com/lightningnetwork/lnd/pull/9272

**Comment by guggero** [comment]
> Added #9272

Force pushed the fixed version of #9272.

**Comment by Roasbeef** [comment]
We'll also want to pull this one in: https://github.com/lightningnetwork/lnd/pull/9253. \

**Comment by guggero** [comment]
Added #9253.

**Comment by guggero** [comment]
Added #9288.

**Review by Roasbeef — APPROVED** [review]
LGTM 💫

**Pull request merged**
