### PR TITLE
FundPsbt and EstimateFee improvements

### PR DESCRIPTION
**Pull request by jalavosus**
`FundPsbt` and `EstimateFee` now support spending from the underlying
wallet using unconfirmed inputs or inputs with a specific number of
minumum confirmations; this is made possible by adding the
params `min_confs` and `spend_unconfirmed` to the underlying proto
messages, and implementing checks in their function calls.

This commit also changes the interface of `WalletController` slightly; it
adds the param `minConfs` to `CreateSimpleTx` inside the
`WalletController` interface, thus allowing the underlying
implementation of the function to pass `minConfs` to its
underlying wallet's `createsimpletx` implementation (if possible and/or desired).

#### Pull Request Checklist

- [x] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [x] All changes are Go version 1.12 compliant
- [x] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [x] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [x] Any new logging statements use an appropriate subsystem and
  logging level
- [x] Code has been formatted with `go fmt`
- [x] Protobuf files (`lnrpc/**/*.proto`) have been formatted with
  `make rpc-format` and compiled with `make rpc`
- [x] New configuration flags have been added to `sample-lnd.conf`
- [x] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [ ] Running `make check` does not fail any tests
- [ ] Running `go vet` does not report any issues
- [x] Running `make lint` does not report any **new** issues that did not
  already exist
- [ ] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [x] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

### CODE REVIEW

**Comment by guggero** [comment]
@jalavosus was the repo for this PR removed by accident? Or what happened?
Was going to review this now, since 0.12.0 is almost out. Or should I instead close this and review #4905?

**Comment by jakesyl** [comment]
@jalavosus I went ahead and applied the patch for this commit to xplorfin/lnd#11 so if you want to change the base branch to `xplorfin/fundpsbt` we should be good to go here

**Comment by Roasbeef** [comment]
We should either proceed with this or #4905

**Comment by guggero** [comment]
Closing this due to inactivity and in favor of #4905.

**Pull request closed without merging**
