### PR TITLE
Fix typos in `dest_custom_records` comment

### PR DESCRIPTION
**Pull request by jholton**
This PR fixes a couple of minor typos.

### CODE REVIEW

**Review by guggero — APPROVED** [review]

**Review by carlaKC — APPROVED** [review]

**Review by carlaKC — CHANGES_REQUESTED** [review]
LGTM! 

Just need to run `make rpc` so that the change to the proto will reflect in the generated code.

**Comment by jholton** [comment]
Done!

**Review by carlaKC — APPROVED** [review]
LGTM!

**Comment by guggero** [comment]
We added a new check that makes sure every PR has a short (one sentence) description in the release notes. If you rebase, you'll find a section `Code health -> Code cleanup, refactor, typo fixes`. Can you add the link to your PR there please?

**Comment by jholton** [comment]
@guggero done!

**Pull request merged**
