### PR TITLE
Added feature: route to self

### PR DESCRIPTION
**Pull request by ZapUser77**
* Added route to self

* Added Unit tests for Route to Self

* Removed unnecessary bytes library import and function calls

### CODE REVIEW

**Comment by ZapUser77** [comment]
Solves: https://github.com/lightningnetwork/lnd/issues/1645

**Comment by ZapUser77** [comment]
Per previous conversation:
vSelf is not a viable solution.  Here's why: it breaks on any path greater than 3 hops.

Assume the shortest route is A-B-C-D-A'
A is connected to B and D, and says the shortest path to B and D is zero. [or near zero], so when C looks to D, it ignores D, because A-B-C is longer than A-D.

**Comment by halseth** [comment]
> A is connected to B and D, and says the shortest path to B and D is zero. [or near zero], so when C looks to D, it ignores D, because A-B-C is longer than A-D.

Can you explain this? After adding A' the path A-B-C-D-A' should be found if it is indeed the shortest.

You must remember that edges are directed, so even though the fee `A->D` is zero, the fee `D->A` is not necessarily zero.

I still don't see why

**Comment by ZapUser77** [comment]
Hmm... It's difficult for me to explain.  It doesn't matter what the fee is, during the pathfinding when it encounters a node, it sets a distance, and it always looks at the 'closest' nodes first, and once it gets to another hop trying to find 'it's way back' it ignores all paths that go back... because they are already found to be shorter.  Essentially, the natural loop-prevention of Dijkstra's also prevents vSelf from working.

With the new 'reverse' pathfinding, this only occurs when there is no constraint on "incoming".  If there's no constraint on incoming, the already existing pathfinding works with minimal modification.  (Setting SelfDistance = Inf, and some infinite loop prevention mechanisms.)
The recursive call only occurs in the same event that would cause "routing to vSelf" to break.

Lets say, for example, the fee from D-A is 10 satoshi, and fee from A-B-C is 100.  When at C, it'll ignore D because A-B-C-D is 'longer' than A-D.

Is my explanation clearer?

I have the code for vSelf... it doesn't work... I had to "cheat" to even get it to work with 3 hops.
It only fails because it sets distances to all directly connected neighbors, which doesn't happen with an explicitly "incoming" channel specified.  But for flexibility (Say for example, you have a node you just opened and want to balance it the cheapest way possible, you'd give an outgoing channel and no incoming channel) I re-wrote the solution with the recursive call.

**Comment by halseth** [comment]
I think I see what your problem is. Adding A' will result in this graph:

      A'
   /      \
 /          \
B - C - D
 \          /
   \      /
      A

Now, start your path finding at A,  and it will find the path `A->D->A'` as the shortest?

**Comment by halseth** [comment]
Ok, then I still don't understand the problem I'm afraid. Why do you expect it to find the path `A->B->C->D->A` if `A->D->A` is cheaper?

**Comment by ZapUser77** [comment]
There several... "problems" that required... creative 'fixing'.  ^_^  
Creating a next hop map... that's a loop... yet not an infinite loop.
Preventing A-D-A from being the shortest path.
Not breaking incoming isn't hard set.
Etc.  ^_^

**Comment by ZapUser77** [comment]
I explicitly tell it to never find paths that are A-D-A.  (assuming same channel ID) As it'd be trying to go in the channel it came out, which should never happen.

**Comment by ZapUser77** [comment]
Basically: When it gets to C, it will ignore D as "D.dist is > c.dist+weight" and return "path not found"

**Comment by ZapUser77** [comment]
@halseth 
To clarify:  This PR does not use vSelf, it uses a recursive call.  The first post was to clarify why.  vSelf can't work in all scenarios, where as the solution in this PR does.

**Comment by Roasbeef** [comment]
There really isn't a need for this feature. The current implementation is a pretty giant hack to the algo just for this particular case. Query routes _as is_ gives you all you need to rebalance: given a channel A you wish to rebalance, query for routes that include the vertex that A is connected to, ignore those that are directly outgoing to vertex V, then go through those routes and append the you->V hope, done!

**Comment by ZapUser77** [comment]
Queryroutes, as is, can not find a path back to self.  It'll fail 100% of the time.
Unless I'm missing something, nothing in QueryRoutes lets you specify an incoming and/or outgoing channel.  You can externally choose from a list, however, without internally always explicitly setting an 'incoming' channel, queryroutes can never find a path back to self.

**Comment by Roasbeef** [comment]
You don't ask a route to yourself. You ask for a route to a node, say `V`. You have a channel to node `V`. This is the channel you wish to rebalance. You then takes these routes, and ignore the ones which have the chan _to_ node `V` as the _first_ hop. You takes this filtered set of routes and _append_ that last hop. You now have a _circular_ route.

**Comment by ZapUser77** [comment]
What you're suggesting was the very first thing I tried.

It's much more than just appending, you have to change fees/HTLC, which requires externally finding fees/htlc, and digging into the return of Queryroutes and changing a bunch of stuff.  And it all has to be done before the HTLC's change, if we're not using Deltas.  It's quite complicated to do externally, and hubs shouldn't be forced to do so, when it's easily handled internally.

And that only applies if your wanting to rebalance inward on the channel from V.
If you want to rebalance outward (and just want the cheapest path going out that channel back to self), which will be the case more often than wanting to rebalance inward, how would you do this?  You can't query routes from V to self, which is what you'd need to do in this case.

**Comment by Roasbeef** [comment]
> which requires externally finding fees/htlc, and digging into the return of Queryroutes and changing a bunch of stuff

Yeah so you just need to hit `getchaninfo` to get the fees of that hop. From there you re-create the route by going backwards through it in order to increase the timelock and fees. All of this is already possible over the RPC interface and with the existing code. We should strive to make the code as simple as possible, and not add a lot of cruft in the from of hacks to try to create an "easy button". 

> If you want to rebalance outward (and just want the cheapest path going out that channel back to self), which will be the case more often than wanting to rebalance inward, how would you do this?

So to _reduce_ the available bandwidth in a channel? You do the a similar routine, but now query for routes to each of the peers that you have outgoing channels with. You then take these routes, and remove all those that _don't_ have that channel as the first outgoing edge. The process after this is identical to the prior case.

**Comment by ZapUser77** [comment]
"So to reduce the available bandwidth in a channel? "
When you first start up a node, all your bandwidth will be near side.  You'll want to send some out to get balanced channels.

"You do the a similar routine, but now query for routes to each of the peers that you have outgoing channels with. You then take these routes, and remove all those that don't have that channel as the first outgoing edge. The process after this is identical to the prior case"

So, if I'm understanding this correctly, if I had 500 channels, I'd have to find 499 paths, then figure out which is the cheapest, and reconstruct the route adding in the last hop?  Which would force me to change the HTLC and Send amount for all previous hops, as well as the overall amount.

And I'd have to do this each and every time I need to rebalance (which could be multiple times per second).

I mean no disrespect, but this doesn't sound like a solution to me.  

It's not just an 'easy button', it functionally scales dramatically better than trying to do it externally.

**Comment by ZapUser77** [comment]
"You then take these routes, and remove all those that don't have that channel as the first outgoing edge. "
I have a situation where that would fail:  
Imagine you want to send out a specific channel to get it balanced.
You then find the shortest path to all other nodes your attached to.
None of those paths lists your first hop as it's shortest.

**Comment by Roasbeef** [comment]
> And I'd have to do this each and every time I need to rebalance (which could be multiple times per second).

Yes, it is possible to write a program that does all this autonomously. The program can easily compute which is "cheapest" and execute that. However, it may not be the case that the "cheapest" route works, which is why it would need to have the proper retry logic. Glancing over the "rebalance" PR doesn't have this and assumes the route selected will just work. This requires users to then continually attempt to retry it (though it looks like there's no way to report failures to it, so it will keep trying the same route). 

> It's not just an 'easy button', it functionally scales dramatically better than trying to do it externally.

Scaling is the exact same, the same routes need to be sent in the end.

**Comment by Roasbeef** [comment]
> None of those paths lists your first hop as it's shortest.

The algo will continue to find the _k shortest_ paths. So the _first_ route will have that, while the others won't. It ensures that each route uses a distinct prefix set of edges.

**Comment by ZapUser77** [comment]
So: You have to go through significantly more than 499 paths, if you had 500 nodes, comparing the k-shortest paths for 499 nodes?  This isn't the same as finding the K-shortest path back to self, while not even trying paths that don't match the 'outgoing' specified.

The external version takes more time as number of number of channels grow, internally it does not.

**Comment by Roasbeef** [comment]
Both versions have the _exact_ same asymptotic complexity. If you set `k=1`, you get the shortest path. However, you may eventually need to prune this path out. 

> This isn't the same as finding the K-shortest path back to self, while not even trying paths that don't match the 'outgoing' specified.

The shortest path isn't guaranteed to work. When it doesn't, you need to try again and ignore that path and so on. I know of several large-ish routing nodes which are already successfully using the algorithm described above with zero issues.

**Comment by ZapUser77** [comment]
Another problem:
Internally it finds paths within the "max fee limit", but if you tack on an extra node, with fees, to the end, you can end up exceeding the max-fee-limit without knowing.

**Comment by Roasbeef** [comment]
All of these "problems" have very straight forward work arounds. You already know _ahead_ of time what the fee will be for that final hop. As a result, you can factor this into the max fee limit.

**Comment by ZapUser77** [comment]
"I know of several large-ish routing nodes which are already successfully using the algorithm described above with zero issues."  Please list a couple.  I'd like to make contact and look over their code.

Finding the k-shortest paths out channel X is not the same as finding the k-shortest paths to every single other node you're connected to and ignoring ones than aren't channel X as first hop.

**Comment by Roasbeef** [comment]
You can query "rompert" on the `lnd` slack if you'd like. Not the same but equivalent, and more _directed_. _No new code_ needs to be added to `lnd` to accomplish what you desire.

**Comment by ZapUser77** [comment]
Last time I spoke with him, he said his didn't work... all kinds of problems.  I'll chat him up again.

**Comment by ZapUser77** [comment]
They aren't equivalent either.  Internal version takes the same amount of time regardless of number of channels, an external version increases in time with number of channels, and potentially can't scale enough.

Lets say, there's some super node out there, with a million+1 channels.  Internally, it finds the shortest path going out channel X.  (or even a couple), whereas externally, it has to find 1 million paths (times k) then the external program has to dig through all one million (or more) paths, drop the ones that don't start with X, then add the recreate the path adding in Fees and HTLC to at least 1 million paths, and then sort them by cost.

**Comment by Roasbeef** [comment]
You've described a naive version of the algorithm. Yes the naive version is
naive. I've demonstrated that it's possible to implement this behavior with
no additional changes to lnd (and many have done so). I'm not sure what
else there is to discuss? In the worst case both versions will need to
retry in order to adjust to varying network conditions.

**Comment by Roasbeef** [comment]
You describe these steps as if it's infeasible for a program to perform
them. The work is happening either way, the question is: is it internal or
external? In spirit of minimizing added code and the rpc interface, for now
we prefer external. This may change at a future date. If you're looking for
work to do in this area, I'd check out joost's open PR's.

**Comment by ZapUser77** [comment]
Internally it's not finding million of paths.  It's finding just the k-shortest.
Externally, there's no way to know what the shortest path is without looking at every single one and adding in the last hop.

"You describe these steps as if it's infeasible for a program to perform them"
Yes, as the number of channels grows, how often rebalancing increases, so the algo needs to be efficient as possible.
Internally the time is a constant, externally it grows at a rate > linearly.  (Not sure what the growth rate is on sorting a list of paths are.)

**Comment by Roasbeef** [comment]
The greedy external algo doesn't need to go through a million paths.

**Comment by ZapUser77** [comment]
""You do the a similar routine, but now query for routes to each of the peers that you have outgoing channels with. You then take these routes, and remove all those that don't have that channel as the first outgoing edge. The process after this is identical to the prior case""

"The greedy external algo doesn't need to go through a million paths."

Is it not the case that if you has 1,000,001 channels, that you'd have to find 1m paths, and return said list to the external program?

**Comment by ZapUser77** [comment]
""None of those paths lists your first hop as it's shortest."
The algo will continue to find the k shortest paths. So the first route will have that, while the others won't. It ensures that each route uses a distinct prefix set of edges."

Ok, The external program would still fail if X channel is not in the K-shortest paths.
Whereas internally, it only fails if there truly isn't a path.

**Comment by ZapUser77** [comment]
Ok,

How about a compromise? What part of the code do you consider "pretty giant hack"?  The recursive call?
That's only needed if incoming isn't specified.  I could remove this, and add in "incoming" and "outgoing" parameters to Queryroutes/findroute/findpaths/findpath.  This would allow the existing algo to find a path to self with minimal mods: ignore paths of zero, ignore paths where prev channel == next channel, and processing the first step of the next hop map outside of the loop.

It removes some of the flexibility, but would help immensely.

**Comment by ZapUser77** [comment]
@Roasbeef 
How about a compromise?  I can remove the recursive pathfind call.  It'll still work as long as each call has 'incoming' specified, and the following additions:

		// If Source = destination the distance "to target" is set to
		// infintiy. So we need tempDist to be lower.
		var tempDist int64
		if toNodeDist.dist == infinity {
			tempDist = weight
		} else {
			tempDist = toNodeDist.dist + weight
		}


if bestNode.PubKeyBytes == sourceNode.PubKeyBytes {
			// In the event that we're sending payments to ourselves,
			// we don't want to give up when starting at the source,
			// thinking the shortest path is zero.
			if distance[targetVertex].dist == 0 &&
				sourceNode.PubKeyBytes == targetNode.PubKeyBytes {
				distance[sourceVertex] = nodeWithDist{
					dist:            infinity,
					node:            targetNode,
					amountToReceive: amt,
					fee:             0,
				}
			} else {
				break
			}

			if pivot != Vertex(targetNode.PubKeyBytes) && next[pivot].ChannelID == inEdge.ChannelID {
				return nil
			}

if sourceNode.PubKeyBytes == targetNode.PubKeyBytes {
		// Determine the next hop forward using the next map.
		nextNode := next[currentNode]
		// Add the next hop to the list of path edges.
		pathEdges = append(pathEdges, nextNode)
		// Advance current node.
		currentNode = Vertex(nextNode.Node.PubKeyBytes)
		delete(next, sourceVertex)
	}

 else if sourceVertex == targetVertex && channelSource.PubKeyBytes != sourceNode.PubKeyBytes {
				// If routing to self bandwidth hints exist, but should be reversed.
				// We need to reverse bandwidth hints when current node is source, but
				// not when the next hop is source.
				edgeBandwidth = lnwire.NewMSatFromSatoshis(
					edgeInfo.Capacity) - edgeBandwidth
			}

Then add in just the "incoming & outgoing* args from the rebalance PR.

This would give at least some functionality to find path to self, without a "giant hack" as you put it.

Would this be acceptable to you?

**Comment by ZapUser77** [comment]
I'm simply asking if there is a way of doing it that's acceptable.

When I opened the Feature request... You weren't opposed to it.
After I spend a great deal of time/effort writing and keeping it up to date... you suddenly and blankly don't want the feature at all.  And considering you've admitted to having something personal against me...
I'm trying to see if the rejection is personal, or if there is any way we could work it something you'd accept.

Just tell me to go away and never both you again, and I'll do so.

**Comment by Roasbeef** [comment]
Please read the article (if you haven't already), open source is a process. I think you'll find some insight and applicable advice within it!

**Comment by Roasbeef** [comment]
> And considering you've admitted to having something personal against me.

Comments like this aren't productive at all. Please find this instance for me, it'll be a surprise to myself and the rest of the active contributors as well. I have never met you, you have never met me, do not assume that individuals on the internet are in any sort of obligation or debt to yourself. Me and the rest of the contributors working on `lnd` provide our work as is, and free of cost to you, please show respect to the rest of the contributors and avoid jumping to conclusions, thanks!

> you suddenly and blankly don't want the feature at all

Please show me the instance in the past when I _personally_ requested the feature. Again, please read the article as I think you'll learn a good bit as a new contributor to an existing open source project. Don't assume any comments or code review are anyway personal, nor that any feature or request is of the highest priority to the project. We use a prioritization system, and this PR has been marked as such.

**Comment by ZapUser77** [comment]
"pick a specific reviewer and go over the design. Ask for help and input early, and magically, you will find your code getting "pulled" (merged) on schedule."

This is what I'm trying to do, with you, right this second.

At this point, I'm not 'pushing' my pr, I'm asking what is an acceptable way to accomplish the task set forth in the Feature Request that you didn't have a problem with.  

I'm asking for input.

**Comment by Roasbeef** [comment]
There are over 100 PRs open atm, many of them with a higher priority that this PR (this one is a P4). PRs will be reviewed and responded to as time permits by the active contributors and code reviewers. Attempting to "bump" or repeatedly comment on PR's will not expedite the process.

**Comment by ZapUser77** [comment]
Anyway, my intent was reduce the workload for you and the others.  This obviously is having the opposite effect.  So, I'll stop being a bother now.

Thanks for all your hard work, and sorry for any problems I've caused you or anyone else.

**Comment by Roasbeef** [comment]
None of these messages are meant to discourage you or any future contributions you may make, they only are meant to connote one thing: patience. Please don't read past any of the comments in this thread, as it seems you've missed the underlying messages, I encourage you to re-read my prior messages.

**Comment by halseth** [comment]
Can be done using `SendToRoute`

**Comment by ZapUser77** [comment]
> 
> 
> Can be done using `SendToRoute`

Except... you can't get a route back to self.

**Pull request closed without merging**
