### PR TITLE
bump ltc payment limit

### LINKED ISSUE #980: Feature Request: Add configuration option to start lnd without the value limits
### Background

For Litecoin the current value limits the usage pegged to current about $4.80 USD, to increase those for mainnet usage would be code that later has to be thrown away.

### Your environment

* lnd version 0.4.0-beta
* Linux name 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* litecoind 0.16
* any other relevant environment details

### Steps to reproduce

Try to initiate a Litecoin Lightning payment to BitRefill.  The limit makes this impossible currently because the cheapest Steam voucher is $5.

### Expected behaviour

The max value should around $380 or be the node should be able to disable the limits.

### Actual behaviour

The max value is $4.80 USD.

### PR DESCRIPTION
**Pull request by Jasonhcwong**
increase litecoin payment limit to (0.04 * 60) as BTC is about 60 times more expensive than LTC
fixes #980

### CODE REVIEW

**Comment by Empact** [comment]
Instead of dropping the `const`, how about initializing in either case in `Start`? In any case, I doubt you'd want to drop `const` on those that can carry it.

**Comment by Jasonhcwong** [comment]
Isn't the value of const must be known at compile time?
The limit depends on the chain(btc or ltc) which is a "deploy time" / "run-time" decision.

**Comment by cfromknecht** [comment]
This would require modifying the spec or adding a feature bit to signal support for larger payments

**Comment by Jasonhcwong** [comment]
You are right, according to Bolt #2, the payment limit should be less than 2^24 satoshi which is about 0.16777216 BTC / LTC. So the max payment limit for litecoin will be 0.16777216 LTC (about 19 USD when LTC price is 113 USD)?

**Comment by patrick-walters-q2** [comment]
@Jasonhcwong because the spec is specific to safety measures, would it make sense to change this PR to allow an unsafe mode which ignores the limits?  I think that worst case scenario one node is running in #notcraeful mode and one is in safety and a channel would get rejected by the safe node either way if I understand correctly.

@cfromknecht would that be more acceptable as a PR?

**Comment by Jasonhcwong** [comment]
@cfromknecht I just added a local feature with feature bit 7 to support larger payment up to 1 BTC/LTC. There is also a config flag "largerpayment" to enable this feature.

**Comment by Roasbeef** [comment]
Closed as the other PR bumped up by 60x, we'll need to create a proper feature bit in the near future, but this at least lets `lnd` nodes use LN on Litecoin rn.

**Pull request closed without merging**
