### PR TITLE
scripts/check-release-notes.sh: fix bash expression

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
thanks @guggero !

**Comment by RandyMcMillan** [comment]
@guggero - I notice the CI needs some attention...
I will try to work out some of the issues... unless there is something I am not aware of...

**Comment by guggero** [comment]
> @guggero - I notice the CI needs some attention... I will try to work out some of the issues... unless there is something I am not aware of...

Unfortunately there are still a few flakes in the CI. Looks like most of the failures (except for the release notes check, but that should disappear on a re-push since I added the `no-changelog` label) are indeed flakes.

**Review by positiveblue — APPROVED** [review]
The  `[[` construct is not part of the POSIX standard but I think this should work in all the environments that we support (windows subsystem for linux, macOS, bash/zsh shells...)

Just adding some context in case some user gets an error in the future.

**Pull request merged**
