### PR TITLE
htlcswitch: make sure link is reestablished when starting

### PR DESCRIPTION
**Pull request by yyforyongyu**
This PR replaces #7157, and attempts to fix the issue described there from a different angle. In short, when a link is started, it's not ready for usage until it has finished its re-establishment. Currently, the re-establishment happens inside the goroutine `htlcManager`, and since the re-establishment might take some time, other systems will fail when working with this link.

This PR fixes it by moving the reestablishment inside `link.Start`, thus the caller can expect a working link when the link is created and started.

The primary reason for making this PR comes from the [discussion here](https://github.com/lightningnetwork/lnd/pull/7157#discussion_r1041397329). Essentially it makes the interface `CreateAndAddLink` deeper so that call sites like `peer` can care less about the link's implementation details.

### CODE REVIEW

**Review by Crypt-iQ — COMMENTED** [review]
The peer calls `loadActiveChannels` and will block until the link has started. However, the link needs `Reestablish` messages to be received, and the peer isn't listening via `readHandler` at this point.

I think this could be a viable approach, but some things will need to be shuffled around in `peer/brontide.go`s start-up order. And I think we should weigh this complexity with the other PRs complexity

**Comment by Crypt-iQ** [comment]
I think we can't move `loadActiveChannels` after the peer starts the 5 goroutines because we might get into the following situation (I think this is right):

* `FetchOpenChannels` is called in goroutine1. This includes a channel (called channel1) that hasn't received FundingLocked yet.
* peer goroutines are started (notably `readHandler` and `channelManager`) in goroutine1
* `loadActiveChannels` is called in goroutine1 with the argument from `FetchOpenChannels`.
* `readHandler` receives `FundingLocked` for channel1 in goroutine2 and passes it to the funding manager via `ProcessFundingMsg`
    * `handleFundingLocked` runs in goroutine3 and calls `AddNewChannel`.
      * `AddNewChannel` passes the `*OpenChannel` object to the peer's `channelManager` goroutine4.
      * `channelManager` adds the created `*LightningChannel` to the `activeChannels` map and starts the corresponding link.
      * The link has a state transition here.
* `loadActiveChannels` finally runs (kernel let it run), and will remove the existing link and replace it with a new link. However, the created `*LightningChannel` will be slightly outdated, similar to the duplicate link issue a while back.

**Comment by yyforyongyu** [comment]
> * `FetchOpenChannels` is called in goroutine1. This includes a channel (called channel1) that hasn't received FundingLocked yet.

Does this mean the channel is in a pending state and will be added to `activeChannels` with a nil value? Aslo it won't create the link?

**Comment by Crypt-iQ** [comment]
> > * `FetchOpenChannels` is called in goroutine1. This includes a channel (called channel1) that hasn't received FundingLocked yet.
> 
> Does this mean the channel is in a pending state and will be added to `activeChannels` with a nil value? Aslo it won't create the link?

The channel isn't pending (it's confirmed on-chain), it just hasn't received `FundingLocked` so the funding manager can still call `AddNewChannel` and add the link that way

**Comment by yyforyongyu** [comment]
Replaced by #7157

**Pull request closed without merging**
