### PR TITLE
clock: add module support

### PR DESCRIPTION
**Pull request by bhandras**
This PR makes `clock` which makes it possible to use in other projects too.

### CODE REVIEW

**Comment by bhandras** [comment]
> Is this specifically for projects that don't rely on `lnd` already? To me it looks a bit heavy to make a module for such a small bit of code, but interested to hear @Roasbeef's opinion.

The module added because the `clock` package itself is separate from `lnd` and wherever we depend on `clock` we should not be required to bump `lnd` version if there's a change.

Similar pattern is used for `queue`, `ticker` and `cert`.

**Comment by cfromknecht** [comment]
changes lgtm 👍

```
<time> [ERR] FNDG: Unable to advance state(<chan_point>): failed adding to router graph: error sending channel announcement: gossiper is shutting down
<time> [ERR] PEER: unable to close channel, ChannelID(<hex>) is unknown
```

**Comment by bhandras** [comment]
> changes lgtm +1
> 
> ```
> <time> [ERR] FNDG: Unable to advance state(<chan_point>): failed adding to router graph: error sending channel announcement: gossiper is shutting down
> <time> [ERR] PEER: unable to close channel, ChannelID(<hex>) is unknown
> ```

I looked trough the build logs but couldn't find these lines. Should fixing flakes be done in this PR? I'm asking because this PR is needed for another project to move on and imo flake fixing could be done separately.

**Comment by joostjager** [comment]
You can just add them to the whitelist

**Comment by federicobond** [comment]
This seems to break one of my Go projects that depends on both `btcwallet` and `lnd`, because now the import is ambiguous:
```
../../../../go/pkg/mod/github.com/btcsuite/btcwallet/wtxmgr@v1.2.0/tx.go:21:2: ambiguous import: found package github.com/lightningnetwork/lnd/clock in multiple modules:
        github.com/lightningnetwork/lnd v0.10.0-beta (/Users/federicobond/code/go/pkg/mod/github.com/lightningnetwork/lnd@v0.10.0-beta/clock)
        github.com/lightningnetwork/lnd/clock v1.0.1 (/Users/federicobond/code/go/pkg/mod/github.com/lightningnetwork/lnd/clock@v1.0.1)
```

`btcwallet` depends on clock at v1.0.1 but `lnd` is declared at v0.10.0-beta.

**Comment by wpaulino** [comment]
You should be able to get around this by updating the `lnd` dependency to a version after the `clock` module was introduced.

**Comment by federicobond** [comment]
Thanks @wpaulino! That solves the issue, but it means we will have to stay on a non-stable tip for the moment, since there is no released version of lnd which has the clock module yet.

**Pull request merged**
