### PR TITLE
fix typo comment for scanInvoicesOnStart function

### PR DESCRIPTION
**Pull request by bufo24**
## Change Description
I found a typo in the comments which describes the function scanInvoicesOnStart in invoiceregistery.go

## Steps to Test
Not applicable

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by guggero** [comment]
Thanks for the fix. Can you add the `[skip ci]` suffix to your commit message as per the checklist please?

**Review by guggero — APPROVED** [review]
Thanks, LGTM

**Review by positiveblue — APPROVED** [review]
Thank you for noticing + correcting it :tada:

**Comment by bufo24** [comment]
Merging still seems to be disabled due to the ci even thought i added [skip ci] in the commit message

**Pull request merged**
