### PR TITLE
Fix go module issue

### LINKED ISSUE #2394: build failed ltcsuite unknown revision
### Background
build fails when following readme guide to install.
### Your environment

ubuntu 18.04

### Steps to reproduce

go get -d github.com/lightningnetwork/lnd
cd $GOPATH/src/github.com/lightningnetwork/lnd
make && make install

### Expected behaviour

build success

### Actual behaviour

go: github.com/ltcsuite/ltcd@v0.0.0-20180701083835-cdab10132e8c: unknown revision cdab10132e8c
go: error loading module requirements
Makefile:99: recipe for target 'build' failed
make: *** [build] Error 1

### PR DESCRIPTION
**Pull request by johng**
When building LND docker image I got the following error when populating go modules

```
go: github.com/ltcsuite/ltcd@v0.0.0-20180701083835-cdab10132e8c: unknown revision cdab10132e8c
```

The commit in question `cdab10132e8c`, doesn't seem to be part of the master branch so I suspect that's why it's failing

Updating the revision of `ltcd` resolved the issue

Fixes #2394.

### CODE REVIEW

**Comment by JarenGlover** [comment]
>The commit in question cdab10132e8c, doesn't seem to be part of the master branch so I suspect that's why it's failing

I was just looking at the master branch and couldn't find it. I thought I was tripping. This make sense now. 

You can likely close #2260 too. 

Is there no concern bumping from July 2018 to Jan 19?

**Comment by Roasbeef** [comment]
Yeah looks like they force pushed to their main branch which removed that commit all together. We may want to consider just vendoring all our deps to avoid funky situations like this in the future.

**Comment by Roasbeef** [comment]
> Is there no concern bumping from July 2018 to Jan 19?

No, there's been no major changes since then. I originally made `ltcd`, and since then the Litecoin team has taken it over, re-making the fork as it had drifted a bit from `btcd`.

**Comment by jlopp** [comment]
confirmed, this resolved my issue

**Comment by gshub77** [comment]
this resolved my issue as well, thank you

**Pull request merged**
