### PR TITLE
multi: update to tlv/v1.1.0 and use new *P2P tlv decoding variants

### PR DESCRIPTION
**Pull request by Crypt-iQ**
This changes the call-sites in several places to use the *P2P variants to not trigger an OOM on untrusted input. This makes the code safe with the new tlv version. Note that the call-sites prior to this change were also safe.

### CODE REVIEW

**Review by morehouse — APPROVED** [review]
LGTM

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Comment by guggero** [comment]
Can you add an entry to the release notes please?

**Review by positiveblue — APPROVED** [review]
Ready to be merged after the release notes have been updated :+1:

**Comment by Crypt-iQ** [comment]
updated w/ notes

**Pull request merged**
