### PR TITLE
Remove warning about pruned nodes

### PR DESCRIPTION
**Pull request by Kixunil**
[Pruning is supported since 0.13](https://github.com/lightningnetwork/lnd/pull/5154)

#### Pull Request Checklist

This is just docs change.

### CODE REVIEW

**Review by carlaKC — APPROVED** [review]
Nice change! 

For extra credit, could add a sentence mentioning that lnd supports pruned mode as well :)

**Comment by Kixunil** [comment]
Good idea, I noted the version to avoid misunderstanding and pointed out performance implications.

**Review by guggero — APPROVED** [review]
LGTM :tada: 

Yes, currently every PR needs an entry in the release notes.

**Comment by Kixunil** [comment]
Added.

**Comment by guggero** [comment]
Thanks! Can you please also the first two commits and update the commit messages according to our [guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure).

**Comment by Kixunil** [comment]
Done.

**Pull request merged**
