### PR TITLE
Add version field to GetInfo RPC endpoint

### PR DESCRIPTION
**Pull request by mecampbellsoup**
This is inspired by the Bitcoin RPC `getnetworkinfo` endpoint which also includes version information:

https://bitcoin.org/en/developer-reference#getnetworkinfo

https://github.com/lightningnetwork/lnd/issues/1016

### CODE REVIEW

**Comment by mecampbellsoup** [comment]
@halseth thanks for reviewing :)

Did you notice the [failing build in the Travis CI matrix](https://travis-ci.org/lightningnetwork/lnd/jobs/362247434#L1025)? Is this a known intermittent test failure?

Also do I need to add some test coverage to get Coveralls to be happy again?

**Comment by halseth** [comment]
Travis failure is not related to your change. I restarted the failing build :)

We should definitely add some more coverage, but that should probably be done in another PR (since the code you added is not easily tested) 😀

**Comment by mecampbellsoup** [comment]
@halseth are there specs anywhere which make assertions on the serialized JSON emitted from the RPC commands/endpoints? Would be happy to add/adjust somewhere in those if they exist.

BTW, is there a way to manually restart a Travis build when we see intermittent failures like this? Or just you guys, the admins?

**Comment by mecampbellsoup** [comment]
@halseth Travis build failing again after rebasing onto `master` branch :(

https://travis-ci.org/lightningnetwork/lnd/jobs/362745562#L1043

**Comment by mecampbellsoup** [comment]
@Roasbeef is [this documentation](https://github.com/lightningnetwork/lnd/tree/master/lnrpc#generate-protobuf-definitions) the easiest way to regenerate the `rpc.pb.go` file with the conflicts now?

I'm just going to rebase onto master again and regenerate the `rpc.pb.go`.

**Comment by halseth** [comment]
@mecampbellsoup Yes, you only need to fix the conflict in the `.proto` file itself, then regenerate using `gen_protos.sh` :)

**Comment by mecampbellsoup** [comment]
@halseth done :)

Alas, our good buddy Travis seems to be strugglin' again :(

**Comment by mecampbellsoup** [comment]
@halseth @Roasbeef I think you guys need to 👍 again, as it seems that previous approvals become voided if I push a new commit or amend an existing commit to the remote. Cheers!

**Comment by mecampbellsoup** [comment]
@merehap are you able to review & approve PRs like this one as well? Pretty simple/straightforward one here.

**Comment by merehap** [comment]
@mecampbellsoup I don't have approver rights :-)

**Comment by mecampbellsoup** [comment]
Paging Dr. Beef! (@Roasbeef) :)

**Pull request merged**
