### PR TITLE
build: set Go version to 1.16

### PR DESCRIPTION
**Pull request by naveensrinivasan**
#### Pull Request Checklist

- [x] All changes are Go version 1.16 compliant
- [ ] Your PR passes all CI checks. If a check cannot be passed for a justifiable reason, that reason must be stated in the commit message and PR description.
- [ ] If this is your first time contributing, we recommend you read the [Code Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
   - [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
   - [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
- [ ] For new code: Code is accompanied by tests which exercise both the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: If possible, code is accompanied by new tests which trigger the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and logging level
- [ ] For code and documentation: lines are wrapped at 80 characters (the tab character should be counted as 8 characters, not 4, as some IDEs do per default)
- [x] A description of your changes [should be added to running the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes) for the milestone your change will land in.

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
* Now that go 1.17 is released go 1.15 isn't supported https://golang.org/doc/devel/release#policy
 * New security fixes will not be provided.
 * Changed the go version from 1.15 to 1.16

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/pull/5650 

We're investigating a possible regression related to the ARM build currently, if we can't resolve that before our next release is due, we'll likely just bump (for the release binaries) to the latest 1.16 version

**Comment by naveensrinivasan** [comment]
> See #5650
> 
> We're investigating a possible regression related to the ARM build currently, if we can't resolve that before our next release is due, we'll likely just bump (for the release binaries) to the latest 1.16 version

Isn’t your release binaries already 1.16?

**Comment by Roasbeef** [comment]
> Isn’t your release binaries already 1.16?

Correct, by latest version I meant `1.16.8`.

**Comment by Roasbeef** [comment]
Replaced by https://github.com/lightningnetwork/lnd/pull/5650

**Pull request closed without merging**
