### PR TITLE
Sample pull request. Allows specification of BTCD parameters.

### PR DESCRIPTION
**Pull request by mkl-**
1. Allows specification BTCD parameters. If not specified read them from btcd.conf file
2. Allows specification network parameters

### CODE REVIEW

**Comment by Roasbeef** [comment]
Thanks for the PR @mkl-! 

I've been meaning to set up proper config parsing, and a separate config file for `lnd` but haven't yet go around to it yet :)

However, importing the _entire_ config struct from `btcd` is unnecessary. The config for `lnwallet` only shares a handful of parameters with `btcd`'s config. 

Additionally, although `lnwallet` currently depends on a `btcd` full-node, in the near future we'll be integrating our in-progress [spv](https://github.com/LightningNetwork/lnd/tree/master/uspv) library, giving users an option as to which wallet they'd like to use. 

The added print statements are unnecessary as `lnd` will be getting a proper logging system in a future commit. 

Finally, although we currently have the active Bitcoin network set to `testnet`, we've been conducting testing on a different testnet, `testnetL` which has the features necessary to proper implement the full version of Lightning. Much of the scripting functionality used in `lnwallet` will be rejected by any network other than `testnetL`.

**Comment by Roasbeef** [comment]
But hey, how about we salvage this PR into something merge-able?

Here's how I recommend you proceed, if you'd still like to contribute 😎.
  * Remove all the unnecessary fields in the new config file you've created. Instead you should simply [embed](https://golang.org/doc/effective_go.html#embedding) the `Config` struct from `lnwallet` into the new config file you've created for the daemon. 
  * Set up the logging infrastructure for all packages. I had planned to use [btclog](https://github.com/btcsuite/btclog) for logging purposes accross all pacakges. It's rather simple, and allows one to easily set up logging for subsystems within the larger system. The packages which don't require their own subsystem logger include: `lnstate`, `lnwire`, `shachain`, and `elkrem`. [Here's an example from `btcwallet` setting up `btclog`](https://github.com/btcsuite/btcwallet/blob/master/log.go). 

You can either re-brand this PR with the above changes, or close this PR, instead creating a new PR implementing the above. It's up to you 🏂.

**Comment by mkl-** [comment]
I've rewritten configuration using approach similar to btcd: command line options + configuration file.
https://github.com/LightningNetwork/lnd/pull/8

Could you please explain what is testnetL and how to use it?
It seems that certificates are hardcoded into the code so I had disabled TLS when worked with lnd.

**Comment by Roasbeef** [comment]
Great! I'll close this PR so we can move along with #8. 

So it turns out we've decided to abandon testnetL. Instead, we're now using segnet for testing purposes since it has the malleability fixes we need for LN, and this way we don't have to maintain our own testnet ;)

**Pull request closed without merging**
