### PR TITLE
Add channel point in invoice and outgoing payment

### PR DESCRIPTION
**Pull request by AndrewSamokhvalov**
**Why it is needed?**
As the Hub providers we need to optimise our revenue. One of the tactics of optimisation revenue is collecting statistics and apply some form of statistical analysis for retrieval of behavioural patterns of adjacent nodes. In order to do that we need to have peers and channels ids in payments.

**What has been done?**

- invoice struct was populated with channel point.
- db version was added to have ability to control the versioning in deserialisation/serialisation functions.
- migration function was written to populate invoice and outgoing payment structures with empty channel point, in order to avoid deserialisation failures, for users whoa already have invoices and outgoing payments.
- invoice registry interface was updated accordingly.

**Questions:**

Is there a way to do versioning better, rather than putting version in every method?
Should the population of channel point be putted as the standalone method in invoice registry interface

### CODE REVIEW

**Comment by joostjager** [comment]
One on one relation between invoice/payments and channels will be lost with amp.

**Comment by AndrewSamokhvalov** [comment]
@joostjager 

Right now it is not possible to calculate flow of funds which goes through the particular channel outside of lnd, which might help on creating a rank of importance of channel. This rank later could be used for choosing which channel to close, if some funds has to be released from channels.

We could calculate incoming / outgoing flow of funds based `fwdinghistory` , `listpayments` rpc, but in  order to calculate receive flow for incoming payments we need to know which channel has been used for receiving funds, and `listinvoices` do not allow to do that. 

As far as I know, the only way for doing that is check is to use `listchannels` every time when payment has arrived, but this is highly unreliable.

**Comment by juscamarena** [comment]
Would be nice to have this or better accounting for every balance change for those needing strict auditing.

**Comment by Roasbeef** [comment]
Now available in the new database structure after the recent router/payments revamp.

**Pull request closed without merging**
