### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by lebedkin**
it's only useful info user needs to know. Otherwise, the output of test looks good even if it's bad so it's misleading.
```
...<many screens of text>...
--- PASS: TestSpecificationDeriveElement (0.00s)
	element_test.go:274: Passed (generate_from_seed 0 final node)
	element_test.go:274: Passed (generate_from_seed FF final node)
	element_test.go:274: Passed (generate_from_seed FF alternate bits 1)
	element_test.go:274: Passed (generate_from_seed FF alternate bits 2)
	element_test.go:274: Passed (generate_from_seed 01 last nontrivial node)
--- PASS: TestShaChainStore (0.28s)
PASS
ok  	github.com/lightningnetwork/lnd/shachain	0.292s
=== RUN   TestCreateWallet
=== RUN   TestUnlockWallet
--- PASS: TestCreateWallet (3.46s)
--- PASS: TestUnlockWallet (5.50s)
PASS
ok  	github.com/lightningnetwork/lnd/walletunlocker	5.626s
=== RUN   TestDecodeAmount
=== RUN   TestEncodeAmount
=== RUN   TestParseTimestamp
=== RUN   TestDecodeEncode
=== RUN   TestNewInvoice
--- PASS: TestDecodeAmount (0.00s)
--- PASS: TestParseTimestamp (0.00s)
--- PASS: TestEncodeAmount (0.00s)
--- PASS: TestNewInvoice (0.00s)
--- PASS: TestDecodeEncode (0.02s)
PASS
ok  	github.com/lightningnetwork/lnd/zpay32	0.095s
```
last screen of the output I've seen. Looks good, but there's two problems somewhere before which difficult to find unless you excpect the problem. The main idea of the test, in my hamble opinon, is the give east consumable feedback wheather everying is OK or NO.

### CODE REVIEW

**Comment by Roasbeef** [comment]
The tests will print `FAIL` at the bottom in the case a test actually does fail.

**Comment by lebedkin** [comment]
@Roasbeef I just got the example when it didn't happen. You answered: "The tests will print FAIL at the bottom in the case a test actually does fail." - no, there are at least some circumstances when the test will NOT print fail at the bottom. When you have dependency problems as an example. It's like: guys, there's a problem here. And reply: no, there's not. Well, great.

**Comment by Roasbeef** [comment]
@lebedkin if there are dependency problems, then it will fail to build all together. Tests in Go _always_ print user output if the test fails.
 
Can you give an example of an instance otherwise?

**Comment by Roasbeef** [comment]
>  Looks good, but there's two problems somewhere before which difficult to find unless you excpect the problem.

Can you paste which errors occurred when you were trying to run the test? If you don't run `glide install` beforehand, you may not have the correct dependancies.

**Pull request closed without merging**
