### PR TITLE
Fix Pruned Node Loss Sync Issue.

### PR DESCRIPTION
**Pull request by ziggie1984**
## Change Description
Fixes for https://github.com/lightningnetwork/lnd/issues/8250 happened in btcwallet (https://github.com/btcsuite/btcwallet/pull/903), this just bumps the version.

### CODE REVIEW

**Comment by yyforyongyu** [comment]
Curious why the `blockcache` didn't help, hmm

**Comment by ziggie1984** [comment]
So we did not have the block in the cache and it failed to get requested, hier is the stack trace from one of those deadlocks I analysed:

```
goroutine 3076998 [select, 863 minutes]:
github.com/btcsuite/btcwallet/chain.(*BitcoindConn).GetBlock(0xc00027ba20, 0xc014ea3a40)
	/home/cotto/go/pkg/mod/github.com/btcsuite/btcwallet@v0.16.10-0.20231129183218-5df09dd43358/chain/bitcoind_conn.go:479 +0x1f0
github.com/btcsuite/btcwallet/chain.(*BitcoindClient).GetBlock(0xc00dc0e7a0?, 0x0?)
	/home/cotto/go/pkg/mod/github.com/btcsuite/btcwallet@v0.16.10-0.20231129183218-5df09dd43358/chain/bitcoind_client.go:144 +0x1d
github.com/lightningnetwork/lnd/blockcache.(*BlockCache).GetBlock(0xc0062f4070, 0xc014ea3a40, 0xc005adeec0)
	/home/cotto/IdeaProjects/lnd/blockcache/blockcache.go:55 +0x246
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).GetBlock(0x0?, 0x48403c?)
	/home/cotto/IdeaProjects/lnd/lnwallet/btcwallet/blockchain.go:139 +0x1ff
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).fetchFundingTx(0xc0000d88c0, 0xc00dc0e6f4)
	/home/cotto/IdeaProjects/lnd/routing/router.go:1810 +0x66
github.com/lightningnetwork/lnd/routing.(*ChannelRouter).fetchFundingTxWrapper.func1()
	/home/cotto/IdeaProjects/lnd/routing/router.go:1774 +0x46
created by github.com/lightningnetwork/lnd/routing.(*ChannelRouter).fetchFundingTxWrapper
	/home/cotto/IdeaProjects/lnd/routing/router.go:1773 +0xf1

```

**Comment by Roasbeef** [comment]
Can be rebased now!

**Comment by rockstardev** [comment]
Excited to push this to everyone using BTCPay Server once ready. Thanks for your work everyone!

**Comment by Roasbeef** [comment]
@rockstardev the dependent PR has been merged. Once this is rebased and passes review+CI, we'll fold it into v0.17.4 rc1.

**Comment by rockstardev** [comment]
Perfect, I have a few merchants waiting for this, so will provide them with rc1 once you tag it and I'll ask them to test.

**Review by saubyk — APPROVED** [review]
Ack

**Review by yyforyongyu — CHANGES_REQUESTED** [review]
Need to fix the linter re go mod on subdirs, otherwise it's good to go ⛵

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Review by yyforyongyu — APPROVED** [review]

**Pull request merged**
