### PR TITLE
Extend ListPayments response by original invoice memo (#2420)

### PR DESCRIPTION
**Pull request by misovan**
Pull request extends grpc ListPayments api by `memo` from the invoice the payment is based on. See [2420](https://github.com/lightningnetwork/lnd/issues/2420) for proposal reasoning and details.

### CODE REVIEW

**Comment by michaelWuensch** [comment]
Can't wait for this feature to be included. This would improve user experience so much.

**Comment by halseth** [comment]
Blocked by #2761

**Comment by misovan** [comment]
> Blocked by #2761

Do you plan to store invoice memo or eventually full payreq data alongside the outgoing payment within #2761?
I'll close this PR then.

**Comment by halseth** [comment]
not necessarily, it is just that there is a code conflict currently. Feel free to keep this open until #2761 is merged :)

**Comment by misovan** [comment]
OK, I believe that this listPayments rpc change would be better applied on top of your PR, as your one targets different concern and is much more complex. At the same time I found https://github.com/lightningnetwork/lnd/pull/2717 that is more recent and aims to implement similar/same thing - just took the option to expose whole payreq in listPayments.

**Comment by misovan** [comment]
Closing, listPayments rpc has been extended by payreq (which includes memo data) in #2717 that is now merged.

**Comment by michaelWuensch** [comment]
Actually I still would like to have this. The payreq is now included, but I now have to decode that payreq in order to get the memo. 
My project is in Java and I can't find a library to do this.
Therefore if I want to show the memo on my payment history page, I will have to make hundreds of additional rpc calls to decode the payment request. This causes unwanted delay, traffic and complexity.

**Comment by halseth** [comment]
@michaelWuensch there's `lnd` RPC to do that

**Comment by michaelWuensch** [comment]
@halseth I know, that is exactly what I am refering to in the second part of my last comment and I already implemented that.
But as I said, if the memo was included in the listPayments rpc I would need exactly one rpc call to display 100 Payments with memos in the history.
When it is not included, I need one call to get the 100 payments without the memo. Then I have to loop through them an make one more decodePayReq request for each of the payments.
This results in a total of 101 rpc calls which cause unwanted traffic and delay.

**Pull request closed without merging**
