### PR TITLE
release: create v0.17.4 rc1 release branch

### PR DESCRIPTION
**Pull request by Roasbeef**
Based on https://github.com/lightningnetwork/lnd/milestone/49

Includes: 
  * https://github.com/lightningnetwork/lnd/pull/8406
  * https://github.com/lightningnetwork/lnd/pull/8401
  * https://github.com/lightningnetwork/lnd/pull/8437
  * https://github.com/lightningnetwork/lnd/pull/8428

While making the branch, I realized that https://github.com/lightningnetwork/lnd/pull/8385 only applies on master. So that bug hadn't made it into an actual release yet. This was kept in with a slight modification. We can confirm if this is needed or not by running those added tests against the branch. 

Similarly, part of the fix for https://github.com/lightningnetwork/lnd/pull/8400 only applies on master, as it relies on the new zombie ressurection logic.

### CODE REVIEW

**Comment by yyforyongyu** [comment]
Weird to see linter fails since we already disabled `paralleltest` in 22600b47f1, which was included in 0.17.1, but couldn't find this commit here.

**Review by guggero — APPROVED** [review]
LGTM :tada: 

> Weird to see linter fails since we already disabled paralleltest in https://github.com/lightningnetwork/lnd/commit/22600b47f131603d298e01a739d062e21539a2a9, which was included in 0.17.1, but couldn't find this commit here.

I can't see that commit in the `lnd-17-1-branch`. In fact, I don't see any changes to the linter config in this branch. So I think the linter breaking is expected and okay at this point.

**Comment by ellemouton** [comment]
can we possibly include https://github.com/lightningnetwork/lnd/pull/8437 as well?

**Comment by guggero** [comment]
And https://github.com/lightningnetwork/lnd/pull/8428 too?

**Pull request merged**
