### PR TITLE
trivial: fix make rpc-format

### PR DESCRIPTION
**Pull request by yyforyongyu**

### CODE REVIEW

**Review by guggero — APPROVED** [review]
LGTM, thanks!

**Review by carlaKC — APPROVED** [review]
Thanks!

**Comment by cfromknecht** [comment]
shouldn't this have been caught by our CI?

**Comment by guggero** [comment]
No, we only check that compiling the protos doesn't result in a diff. But not yet the formatting. I think there was an issue with the version of clang-format, that's why we didn't add the format-rpc command to CI.

**Pull request merged**
