### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by zhiqiangxu**

### CODE REVIEW

**Comment by ellemouton** [comment]
@zhiqiangxu  - please see our [code contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for commit title & body structure. I also think all these changes can be squashed into a single commit

**Comment by zhiqiangxu** [comment]
@ellemouton I just squash them into a single one.

**Comment by ellemouton** [comment]
@zhiqiangxu  - please see the failing linter CI check - there is a line that is too long it seems. Lines should wrap at 80 chars. 

Also, for the commit title: I think you can just name it `lnwallet+input: fix a few typos`. `docs:` implies that the changes are in the `docs` folder, which they are not

**Review by guggero — APPROVED** [review]
Thanks, LGTM (pending the CI run).

**Review by ellemouton — APPROVED** [review]
lgtm!

**Pull request merged**
