### PR TITLE
Add a timestamp_ns field to the ForwardingEvent rpc message

### PR DESCRIPTION
**Pull request by yaslama**
This allows to use FowardingHistory rpc method to receive the data exactly
as it's stored in lnd and to synchronize incrementally the history to an
external database.

### CODE REVIEW

**Review by carlaKC — CHANGES_REQUESTED** [review]
Thanks for the PR @yaslama!

I think it would be cleaner to add a `timestamp_ns` field to the response and populate both fields, and mark the old field as deprecated. We have a similair situation in some other APIs where we have satoshi and millisatoshi values.

**Comment by yaslama** [comment]
> Thanks for the PR @yaslama!
> 
> I think it would be cleaner to add a `timestamp_ns` field to the response and populate both fields, and mark the old field as deprecated. We have a similair situation in some other APIs where we have satoshi and millisatoshi values.

Thanks @carlaKC. I modified the PR to add the `timestamp_ns`.

**Review by carlaKC — APPROVED** [review]
Awesome, thanks for the quick turnaround! 

LGTM 🥇

**Review by Roasbeef — APPROVED** [review]
LGTM 🦅

**Comment by Roasbeef** [comment]
Needs a rebase!

**Comment by Roasbeef** [comment]
Committed as 3f2be8ed656aeb7823915ea43358060907836b61 so we don't have to play the rebase dance. Thanks!

**Pull request closed without merging**
