### PR TITLE
mod: bump miekg/dns to next version

### PR DESCRIPTION
**Pull request by naveensrinivasan**
#### Pull Request Checklist

- [x] All changes are Go version 1.15 compliant
- [ ] Your PR passes all CI checks. If a check cannot be passed for a justifiable reason, that reason must be stated in the commit message and PR description.
- [x] If this is your first time contributing, we recommend you read the [Code Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
   - [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
   - [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
- [ ] For new code: Code is accompanied by tests which exercise both the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: If possible, code is accompanied by new tests which trigger the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and logging level
- [ ] For code and documentation: lines are wrapped at 80 characters (the tab character should be counted as 8 characters, not 4, as some IDEs do per default)
- [ ] A description of your changes [should be added to running the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes) for the milestone your change will land in.

### CODE REVIEW

**Comment by guggero** [comment]
What is the motivation for this change?

**Comment by naveensrinivasan** [comment]
> What is the motivation for this change?

The dns has https://deps.dev/go/github.com%2Fmiekg%2Fdns/v1.1.25 has
GO-2020-0012 https://storage.googleapis.com/go-vulndb/golang.org/x/crypto.json

Updated the dependency with the fix.

**Comment by naveensrinivasan** [comment]
I didn’t update the release notes. I can update once we agree on this. Thanks

**Comment by naveensrinivasan** [comment]
> What is the motivation for this change?

Ping, Thoughts on the motivation

> I didn’t update the release notes. I can update once we agree on this. Thanks



> > What is the motivation for this change?
> 
> The dns has https://deps.dev/go/github.com%2Fmiekg%2Fdns/v1.1.25 has
> GO-2020-0012 https://storage.googleapis.com/go-vulndb/golang.org/x/crypto.json
> 
> Updated the dependency with the fix.

@guggero  Thoughts on this PR for fixing the OSV issue.

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Comment by naveensrinivasan** [comment]
> Sounds good to me. You can add the release notes 👍

Thank you! Updated the release notes 👍

**Review by Roasbeef — APPROVED** [review]
LGTM 🦄

**Comment by Roasbeef** [comment]
Hmm it's failing the build right now, can you try squashing that merge conflict into a single one?

**Comment by naveensrinivasan** [comment]
Closing this for #5738 , the commits are messed up.

**Comment by guggero** [comment]
You can get rid of merge commits by rebasing next time.

**Pull request closed without merging**
