### PR TITLE
multi: bump btcd version.

### PR DESCRIPTION
**Pull request by ziggie1984**
Makes sure LND is compatible with the newest bitcoind 28 release.

Fixes: https://github.com/lightningnetwork/lnd/issues/9053

### CODE REVIEW

**Review by ProofOfKeags — APPROVED** [review]

**Review by Roasbeef — APPROVED** [review]
LGTM 🥕

**Comment by twofaktor** [comment]
Hello, will this fix be applied with LND v18.4 before Bitcoin Core v28 is released?

**Comment by saubyk** [comment]
> Hello, will this fix be applied with LND v18.4 before Bitcoin Core v28 is released?

Given that this change is backwards compatible, I've tagged it for 18.4

**Comment by DerEwige** [comment]
fixes #9163

**Pull request merged**
