### PR TITLE
itest: fix typo [skip ci]

### PR DESCRIPTION
**Pull request by patrickReiis**
Changed "chanenl" to "channel"

### CODE REVIEW

**Comment by patrickReiis** [comment]
Hi @guggero could you take a look at this? Thanks.

**Review by guggero — COMMENTED** [review]
The commit message should contain the package changed. Other than that, looks good, thanks.

**Comment by patrickReiis** [comment]
I didn't know about that. Fixed.

**Comment by guggero** [comment]
I was referring to the commit message, not the GitHub Pull Request title. But I assume you created the PR through the GitHub UI? Then you can't change that easily, so we'll just ignore it for now, since it's such a tiny change.

**Comment by patrickReiis** [comment]
Oh sorry, that's correct, I wrote the commit message using the Github UI. Next time I'll be more aware.

**Review by guggero — APPROVED** [review]

**Review by yyforyongyu — APPROVED** [review]

**Pull request merged**
