### PR TITLE
Add cancelinvoice command - WIP

### PR DESCRIPTION
**Pull request by sangaman**
This adds a `cancelinvoice` rpc command that marks an invoice as `canceled`. Attempting to pay a canceled invoice will fail with an "invoice has been canceled" error message. Protos have been regenerated for the new command and the additional field on `Invoice`.

I'm trying to follow the "Share early, share often" mantra here and get some feedback. I still need to add test cases. Also, currently attempting to pay a canceled invoice from the command line merely hangs, I figure there should be some sort of error message indicating an invoice has been canceled to the person that attempts to pay a canceled invoice.

I think a desirable followup feature would be the ability to "link" invoices such that when one invoice is paid, all linked invoices are automatically canceled. This would be useful when a seller issues multiple invoices for a specific item, where it can only be sold once and the first person to pay gets it.

Any feedback would be appreciated, thanks.

### CODE REVIEW

**Comment by wpaulino** [comment]
Haven't dug into the changes yet, but maybe this would be better to implement as suggested by #1404? I don't see a need for keeping a record of canceled invoices (please enlighten me otherwise) so we could just remove them as well.

**Comment by sangaman** [comment]
I did see #1404 and figured it may be relevant to these changes. My feeling is that it might make sense to keep a record of canceled invoices for some period of time to be able to recognize when there's an attempt to pay a canceled invoice. I'm not sure how much that really matters and maybe it's not worth it, but I figure that if purging old or expired invoices becomes a feature then we could easily extend that to remove canceled invoices as well once some time has passed.

**Comment by orbitalturtle** [comment]
Just chiming in here. I agree it would be nice to have both a cancel invoice and delete invoice options. Canceling invoices might be useful to some. And having something like 1404 as well sounds worthwhile to give in case users want to get rid of extra data they don't need to store.

**Comment by Roasbeef** [comment]
Implemented as part of the new hold invoice system.

**Pull request closed without merging**
