### PR TITLE
funding: remove obsolete todo [skip ci]

### PR DESCRIPTION
**Pull request by hieblmi**
This PR removes an obsolete todo. The missing behavior was introduced here: https://github.com/lightningnetwork/lnd/blob/e2f5374f67a4bb28d5adeae922e5dfe4dd698025/funding/manager.go#L3393

### CODE REVIEW

**Comment by Crypt-iQ** [comment]
todo is still valid, peer could go offline by the time we call sendmessage

**Comment by hieblmi** [comment]
I see, right, I missed that we should block here till the peer comes online!

**Comment by Crypt-iQ** [comment]
I think we already block in waitForPeerOnline, but we should keep trying to send until SendMessage succeeds

**Comment by hieblmi** [comment]
Should there be a timeout after which we return the error?

**Pull request closed without merging**
