### PR TITLE
lncli: allow unlock with password from stdin

### PR DESCRIPTION
**Pull request by guggero**
As discussed with @lispmeister, this is needed to unlock lnd in a containerized environment like Kubernetes. Without this fix, additional unlocking software is needed that performs the unlock call through gRPC.

This could perhaps also be an acceptable compromise to what was suggested in #899.

### CODE REVIEW

**Comment by githorray** [comment]
Trouble building on Windows. go version go1.14 windows/amd64

```
cmd\lncli\commands.go:1810:34: cannot use syscall.Stdin (type syscall.Handle) as
 type int in argument to terminal.ReadPassword
Makefile:91: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by githorray** [comment]
```		pw, err = terminal.ReadPassword(int(syscall.Stdin))```

seems to have fixed it.

**Comment by guggero** [comment]
Thanks for reporting this, @githorray! Fix is up: #4069.

**Comment by githorray** [comment]
working great! thanks.

**Pull request merged**
