### PR TITLE
bug: fix json tag

### PR DESCRIPTION
**Pull request by longhutianjie**
## Change Description

 fix json tag

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ] [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Review by guggero — APPROVED** [review]
Thanks for the fix. Looks like the code isn't actually used for parsing JSON, otherwise this would've failed...

**Review by ellemouton — APPROVED** [review]

**Comment by Sajjon** [comment]
@guggero @ellemouton 
> [!CAUTION]
> GH user `longhutianjie` is performing a supply chain attack!
> 🚫 BLOCK user immediatly and report him to Github 🚫
>
> The first step is getting rid of "first time contributor" status.
>
> The user has manually added the message "Signed-off-by: <USER>" to make the commit 
look more trust worthy. User has opened similar PRs in all these other
> repos in within the same hour:

- https://github.com/c9s/bbgo/pull/1731
- https://github.com/crypto-org-chain/cronos/pull/1566
- https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1579
- https://github.com/stellar/go/pull/5453
- https://github.com/ory/hydra/pull/3831
- https://github.com/dfinity/ic/pull/1309
- https://github.com/lightningnetwork/lnd/pull/9064
- https://github.com/near/nearcore/pull/12036
- https://github.com/stellar/stellar-core/pull/4450
- https://github.com/fetchai/uAgents/pull/525
- https://github.com/vitessio/vitess/pull/16708


Furthermore I'm pretty sure this is the same person or group as github.com/vivoxfold3,
who tried performing the attack against these repos, with the exact same style:
Manually adding the message "Signed-off-by: <USER>" and making trivial contributions
to many crypto libs within the same hour:

- https://github.com/radixdlt/babylon-wallet-ios/pull/1321
- https://github.com/DeFiCh/ain/pull/3031
- https://github.com/beefyfinance/beefy-api/pull/1546
- https://github.com/fluencelabs/cli/pull/1022
- https://github.com/hoprnet/hoprnet/pull/6482
- https://github.com/ResearchHub/researchhub-web/pull/1825
- https://github.com/Taraxa-project/taraxa-node/pull/2846

**Comment by guggero** [comment]
@Sajjon thanks for the warning. We get a lot of these drive-by "contributions", though usually it's because there's a financial incentive somewhere (either they get some form of crypto token as rewards for open source contributions or participate in events like "Google Summer of Code" or similar).
Is there anything specific that makes you classify this as a malicious attack or preparation for one?

@longhutianjie any response to this accusation from your end? And make sure your response doesn't sound like AI generated BS...

**Comment by Sajjon** [comment]
> @Sajjon thanks for the warning. We get a lot of these drive-by "contributions", though usually it's because there's a financial incentive somewhere (either they get some form of crypto token as rewards for open source contributions or participate in events like "Google Summer of Code" or similar). Is there anything specific that makes you classify this as a malicious attack or preparation for one?
> 

@guggero This is the second GH user which:
1. has no sources (only forks)
2. no profile photo
3. no followers
4. no bio
5. forks ~10 crypto libs or repos used by crypto libs / wallets all *within the same hour*
6. makes trivial contributions and **tries to "falsify" a GPG signature** by writing "Signed off by"
7. ignores PR templates

The **exact same behaviour** was done by GH use `vivoxfold3` also last week, which responded using... hmm... interesting phrasing:

https://github.com/hoprnet/hoprnet/pull/6482#issuecomment-2333638612

> "Unreasonable accusations from persecuted delusional patients"

Whatever that means? Obvious bad translation service.

Point 6) is a specifically strong indication - imagine you have not actually setup signing of git commits (GPG or SSH key) - what do you do if you are an honest actor? Well you don't sign right... Here user is trying to make commit look serious by appending the string "Signed Off by" - which I see user did not do in **this PR**, most have forgotten, but did in https://github.com/crypto-org-chain/cronos/pull/1566/commits/00c194166e23c1ef4c50d3adac6724be834ffc35, and in https://github.com/ethereumclassic/ethereumclassic.github.io/pull/1579/commits/0461042bcd1e68c6a570a4a56848c934277ec4f5

**Comment by guggero** [comment]
Thank you for your response. Unfortunately 1-4 and 7 are quite common for those drive-by PRs.
But I agree that 5 and 6 together look quite suspicious.

Though it looks like they updated their behavior? Since the commit in this PR was signed with `62EAB0072D19DF1C`.

Probably a good idea to block those users, I agree.

**Pull request merged**
