### PR TITLE
Missing whitespaces on lncli queryroutes command description

### PR DESCRIPTION
**Pull request by grunch**
Adds whitespaces missing on command description,
without those whitespaces at the end of the line
it showed the words together

### CODE REVIEW

**Comment by halseth** [comment]
Nice! LGTM!

Could you rebase and squash the commits into one?

**Comment by grunch** [comment]
Hi @halseth I'm not sure how to rebase it, I haven't done before, I don't have in my local branch that merge commit, any advice?

**Comment by halseth** [comment]
@grunch Pull latest master locally, then go to your local branch and do `git rebase master`.

You should then be able to update the branch in the PR by `git push --force`.

**Comment by grunch** [comment]
@halseth rebased!

**Pull request merged**
