### PR TITLE
Interceptor additions

### PR DESCRIPTION
**Pull request by yaslama**
This PR adds several features to the interceptor:

1. The ability to change the onion blob, outgoing amount and the outgoing channel when resuming the payment. This feature is used when the interceptor needs to create a channel on the fly.
1. The ability to fail with FailIncorrectDetails in order to let probing work before the new channel is created.

### CODE REVIEW

**Comment by Roasbeef** [comment]
> The ability to change the onion blob

How can you _change_ the onion blob? As you don't know who's beyond your immediate hop, so you'd just cause the route to fail entirely? Do you have a concrete example use-case?

**Comment by yaslama** [comment]
> > The ability to change the onion blob
> 
> How can you _change_ the onion blob? As you don't know who's beyond your immediate hop, so you'd just cause the route to fail entirely? Do you have a concrete example use-case?

We are already use this in production in our LSP when the penultimate node in the route creates a channel on the fly to the payee and pays her using the new channel. The onion is changed because the amount is lower than the amount the LSP received in order to cover the cost of the new channel. Of course the payee agreed to that before the payment and sent the payment_hash and payment_secret and the amounts to the LSP.

**Comment by alexbosworth** [comment]
A forwarding node shouldn't return `INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS`, that should be returned by the final node right?

**Comment by yaslama** [comment]
> A forwarding node shouldn't return `INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS`, that should be returned by the final node right?

This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.

**Comment by alexbosworth** [comment]
> This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.

If this code is interpreted as meaning the details are actually incorrect, this could introduce an attack where an arbitrary node could halt further payment retries by returning a phony incorrect payment details

**Comment by yaslama** [comment]
> > This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.
> 
> If this code is interpreted as meaning the details are actually incorrect, this could introduce an attack where an arbitrary node could halt further payment retries by returning a phony incorrect payment details

I am not sure to understand fully what you mean, but this error is accepted by a payer when coming from a node other than the payee if 1) it's from the penultimate node in the path and 2) it's a "probing" payment with the payer using a "wrong" payment hash.

**Comment by alexbosworth** [comment]
> > > This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.
> > 
> > 
> > If this code is interpreted as meaning the details are actually incorrect, this could introduce an attack where an arbitrary node could halt further payment retries by returning a phony incorrect payment details
> 
> I am not sure to understand fully what you mean, but this error is accepted by a payer when coming from a node other than the payee if 1) it's from the penultimate node in the path and 2) it's a "probing" payment with the payer using a "wrong" payment hash.

To know if a probe is successful, you should check if the payee has signed this error not the penultimate node. Otherwise some other error code should be used since the meaning of the error code is altered when it is not returned by the destination. No channel needs to exist for things to "just work" from the payer perspective, you only need a way to contact the payee and get them to sign the error, and return that error in the failure.

**Comment by yaslama** [comment]
>  it i



> > > > This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.
> > > 
> > > 
> > > If this code is interpreted as meaning the details are actually incorrect, this could introduce an attack where an arbitrary node could halt further payment retries by returning a phony incorrect payment details
> > 
> > 
> > I am not sure to understand fully what you mean, but this error is accepted by a payer when coming from a node other than the payee if 1) it's from the penultimate node in the path and 2) it's a "probing" payment with the payer using a "wrong" payment hash.
> 
> To know if a probe is successful, you should check if the payee has signed this error not the penultimate node. Otherwise some other error code should be used since the meaning of the error code is altered when it is not returned by the destination. No channel needs to exist for things to "just work" from the payer perspective, you only need a way to contact the payee and get them to sign the error, and return that error in the failure.

What do you mean by "the meaning of the error code is altered"? In this case, the payer knows that it's a probe payment, knows that the error comes from the penultimate node and knows that the meaning of this error in this case is that the route and the fees are ok.

**Comment by alexbosworth** [comment]
> > it i
> 
> > > > > This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.
> > > > 
> > > > 
> > > > If this code is interpreted as meaning the details are actually incorrect, this could introduce an attack where an arbitrary node could halt further payment retries by returning a phony incorrect payment details
> > > 
> > > 
> > > I am not sure to understand fully what you mean, but this error is accepted by a payer when coming from a node other than the payee if 1) it's from the penultimate node in the path and 2) it's a "probing" payment with the payer using a "wrong" payment hash.
> > 
> > 
> > To know if a probe is successful, you should check if the payee has signed this error not the penultimate node. Otherwise some other error code should be used since the meaning of the error code is altered when it is not returned by the destination. No channel needs to exist for things to "just work" from the payer perspective, you only need a way to contact the payee and get them to sign the error, and return that error in the failure.
> 
> What do you mean by "the meaning of the error code is altered"? In this case, the payer knows that it's a probe payment, knows that the error comes from the penultimate node and knows that the meaning of this error is that the route and the fees are ok.

The error code that they payment details are incorrect normally comes from the final node, not the penultimate node. Really for privacy reasons, no one should even know what the penultimate node is

**Comment by yaslama** [comment]
> > > it i
> > 
> > 
> > > > > > This error was indeed returned only by the final node, but this error is used for probing before the payment (works only for non-mpp payment). An interceptor which is supposed to create a channel on the fly can now send back this error to the payer to let her know that the payment would be successful.
> > > > > 
> > > > > 
> > > > > If this code is interpreted as meaning the details are actually incorrect, this could introduce an attack where an arbitrary node could halt further payment retries by returning a phony incorrect payment details
> > > > 
> > > > 
> > > > I am not sure to understand fully what you mean, but this error is accepted by a payer when coming from a node other than the payee if 1) it's from the penultimate node in the path and 2) it's a "probing" payment with the payer using a "wrong" payment hash.
> > > 
> > > 
> > > To know if a probe is successful, you should check if the payee has signed this error not the penultimate node. Otherwise some other error code should be used since the meaning of the error code is altered when it is not returned by the destination. No channel needs to exist for things to "just work" from the payer perspective, you only need a way to contact the payee and get them to sign the error, and return that error in the failure.
> > 
> > 
> > What do you mean by "the meaning of the error code is altered"? In this case, the payer knows that it's a probe payment, knows that the error comes from the penultimate node and knows that the meaning of this error is that the route and the fees are ok.
> 
> The error code that they payment details are incorrect normally comes from the final node, not the penultimate node. Really for privacy reasons, no one should even know what the penultimate node is

But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?

**Comment by alexbosworth** [comment]
> But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?

In this scenario maybe the penultimate forwarding node knows they are the penultimate forwarding node and that is the original privacy issue, normally they wouldn't know they were sending to the final destination. It seems incorrect to me to assume knowledge of this specific non-standard scenario but also want to use standard errors that would just confuse normal clients, if it's a custom scenario why not use a custom error?

**Comment by yaslama** [comment]
> > But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?
> 
> In this scenario maybe the penultimate forwarding node knows they are the penultimate forwarding node and that is the original privacy issue, normally they wouldn't know they were sending to the final destination. It seems incorrect to me to assume knowledge of this specific non-standard scenario but also want to use standard errors that would just confuse normal clients, if it's a custom scenario why not use a custom error?

The argument to use this standard error is that the meaning of the error is that the payment is ok but one detail is wrong (in the case of regular probing it's the payment_hash). When probing using the lsp, it's exactly the same meaning. And it cannot confuse any client because right now clients don't accept this error if not coming from the last node. lnd itself blacklists in the mission control any intermediate node sending back this error. So only a specific client which knows the "extended" meaning of the error will use it. See https://github.com/LN-Zap/zap-desktop/pull/3689

**Comment by alexbosworth** [comment]
> > > But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?
> > 
> > 
> > In this scenario maybe the penultimate forwarding node knows they are the penultimate forwarding node and that is the original privacy issue, normally they wouldn't know they were sending to the final destination. It seems incorrect to me to assume knowledge of this specific non-standard scenario but also want to use standard errors that would just confuse normal clients, if it's a custom scenario why not use a custom error?
> 
> The argument to use this standard error is that the meaning of the error is that the payment is ok but one detail is wrong (in the case of regular probing it's the payment_hash). When probing using the lsp, it's exactly the same meaning. And it cannot confuse any client because right now clients don't accept this error if not coming from the last node. lnd itself blacklists in the mission control any intermediate node sending back this error. So only a specific client which knows the "extended" meaning of the error will use it. See [LN-Zap/zap-desktop#3689](https://github.com/LN-Zap/zap-desktop/pull/3689)

The thing that confuses me the most is that why not support probing from any client that isn't custom coded for this specific case by just returning the error from the final hop as normal?

**Comment by yaslama** [comment]
> > > > But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?
> > > 
> > > 
> > > In this scenario maybe the penultimate forwarding node knows they are the penultimate forwarding node and that is the original privacy issue, normally they wouldn't know they were sending to the final destination. It seems incorrect to me to assume knowledge of this specific non-standard scenario but also want to use standard errors that would just confuse normal clients, if it's a custom scenario why not use a custom error?
> > 
> > 
> > The argument to use this standard error is that the meaning of the error is that the payment is ok but one detail is wrong (in the case of regular probing it's the payment_hash). When probing using the lsp, it's exactly the same meaning. And it cannot confuse any client because right now clients don't accept this error if not coming from the last node. lnd itself blacklists in the mission control any intermediate node sending back this error. So only a specific client which knows the "extended" meaning of the error will use it. See [LN-Zap/zap-desktop#3689](https://github.com/LN-Zap/zap-desktop/pull/3689)
> 
> The thing that confuses me the most is that why not support probing from any client that isn't custom coded for this specific case by just returning the error from the final hop as normal?

I agree with you that's it a little bit convoluted and you are right in theory. But that mean that the lsp/interceptor needs to be able to initiate the communication with the payee (which is a mobile phone) and right now the only connection between them are: 1) they are peers from ln point of view and 2) the payee can make api calls to the lsp. If we wanted to be able to do what you propose, we need to use the current connection between them initiated by lnd and to "inject" the new protocol asking to sign the error, or to create a new bidirectional channel to do that. It's a lot more complicated than simply enhancing the meaning of the error which is in fact a true meaning.

**Comment by alexbosworth** [comment]
> > > > > But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?
> > > > 
> > > > 
> > > > In this scenario maybe the penultimate forwarding node knows they are the penultimate forwarding node and that is the original privacy issue, normally they wouldn't know they were sending to the final destination. It seems incorrect to me to assume knowledge of this specific non-standard scenario but also want to use standard errors that would just confuse normal clients, if it's a custom scenario why not use a custom error?
> > > 
> > > 
> > > The argument to use this standard error is that the meaning of the error is that the payment is ok but one detail is wrong (in the case of regular probing it's the payment_hash). When probing using the lsp, it's exactly the same meaning. And it cannot confuse any client because right now clients don't accept this error if not coming from the last node. lnd itself blacklists in the mission control any intermediate node sending back this error. So only a specific client which knows the "extended" meaning of the error will use it. See [LN-Zap/zap-desktop#3689](https://github.com/LN-Zap/zap-desktop/pull/3689)
> > 
> > 
> > The thing that confuses me the most is that why not support probing from any client that isn't custom coded for this specific case by just returning the error from the final hop as normal?
> 
> I agree with you that's it a little bit convoluted and you are right in theory. But that mean that the lsp/interceptor needs to be able to initiate the communication with the payee (which is a mobile phone) and right now the only connection between them are: 1) they are peers from ln point of view and 2) the payee can make api calls to the lsp. If we wanted to be able to do what you propose, we need to use the current connection between them initiated by lnd and to "inject" the new protocol asking to sign the error, or to create a new bidirectional channel to do that. It's a lot more complicated than simply enhancing the meaning of the error which is in fact a true meaning.

I can see that, do you not need to connect to them already to see if they are really around to accept the payment? I can think of one workaround for your scenario which is for the receiver to create a shared key with their forward provider. When they make an invoice, they use this shared key. The forward provider doesn't know the preimage though, so when the real payment comes through they forward an HTLC to the real final node to get the preimage. I'd personally prefer a more generic solution that follows along the standard error case because it would allow for custodial wallets to support this same flow, plus we could extend this to submarine swaps, and it would allow for any payer to do the probe not just a custom client.

**Comment by yaslama** [comment]
> > > > > > But the payer knows the penultimate node because she creates (at least currently) the full path to the payee. And the payee knows also because she registered herself to the LSP in order to "receive" a channel on the fly. This specific payment details are already known by the triplet (payer, lsp, payee), consequently this kind of error is not a privacy leak because there is no new information leaked. Do I miss something here?
> > > > > 
> > > > > 
> > > > > In this scenario maybe the penultimate forwarding node knows they are the penultimate forwarding node and that is the original privacy issue, normally they wouldn't know they were sending to the final destination. It seems incorrect to me to assume knowledge of this specific non-standard scenario but also want to use standard errors that would just confuse normal clients, if it's a custom scenario why not use a custom error?
> > > > 
> > > > 
> > > > The argument to use this standard error is that the meaning of the error is that the payment is ok but one detail is wrong (in the case of regular probing it's the payment_hash). When probing using the lsp, it's exactly the same meaning. And it cannot confuse any client because right now clients don't accept this error if not coming from the last node. lnd itself blacklists in the mission control any intermediate node sending back this error. So only a specific client which knows the "extended" meaning of the error will use it. See [LN-Zap/zap-desktop#3689](https://github.com/LN-Zap/zap-desktop/pull/3689)
> > > 
> > > 
> > > The thing that confuses me the most is that why not support probing from any client that isn't custom coded for this specific case by just returning the error from the final hop as normal?
> > 
> > 
> > I agree with you that's it a little bit convoluted and you are right in theory. But that mean that the lsp/interceptor needs to be able to initiate the communication with the payee (which is a mobile phone) and right now the only connection between them are: 1) they are peers from ln point of view and 2) the payee can make api calls to the lsp. If we wanted to be able to do what you propose, we need to use the current connection between them initiated by lnd and to "inject" the new protocol asking to sign the error, or to create a new bidirectional channel to do that. It's a lot more complicated than simply enhancing the meaning of the error which is in fact a true meaning.
> 
> I can see that, do you not need to connect to them already to see if they are really around to accept the payment? I can think of one workaround for your scenario which is for the receiver to create a shared key with their forward provider. When they make an invoice, they use this shared key. The forward provider doesn't know the preimage though, so when the real payment comes through they forward an HTLC to the real final node to get the preimage. I'd personally prefer a more generic solution that follows along the standard error case because it would allow for custodial wallets to support this same flow, plus we could extend this to submarine swaps, and it would allow for any payer to do the probe not just a custom client.

The lsp checks only that the final payee is currently a connected peer and that means that the lsp is able to create a channel. I quite don't follow your proposition because the lsp needs to know the payment hash that the payee sent to the payer in order to detect the payment and create a channel before paying to the payee the original amount minus a fee for the channel creation. btw, right now probing needs a custom client only because it's not standardized.

**Comment by alexbosworth** [comment]
> The lsp checks only that the final payee is currently a connected peer and that means that the lsp is able to create a channel. I quite don't follow your proposition because the lsp needs to know the payment hash that the payee sent to the payer in order to detect the payment and create a channel before paying to the payee the original amount minus a fee for the channel creation. btw, right now probing needs a custom client only because it's not standardized.

The payee could register the hash with the penultimate forwarder, the idea is that the payer wouldn't realize that there is this extra hop

**Comment by yaslama** [comment]
> > The lsp checks only that the final payee is currently a connected peer and that means that the lsp is able to create a channel. I quite don't follow your proposition because the lsp needs to know the payment hash that the payee sent to the payer in order to detect the payment and create a channel before paying to the payee the original amount minus a fee for the channel creation. btw, right now probing needs a custom client only because it's not standardized.
> 
> The payee could register the hash with the penultimate forwarder, the idea is that the payer wouldn't realize that there is this extra hop

The payer needs to realize that there is an extra hop because the channel between the lsp and the payee is generally private, and the info concerning this channel is in the routing hints.

**Comment by yaslama** [comment]
> custodia



> it would allow for custodial wallets to support this same flow

I don't think that custodial wallets need to be taken into account.

**Comment by Roasbeef** [comment]
Does [this PR](https://github.com/lightningnetwork/lnd/pull/6896) encompass the changes proposed here?

**Pull request closed without merging**
