### PR TITLE
chore: remove repetitive words

### PR DESCRIPTION
**Pull request by cuinix**
## Change Description
Description of change / link to associated issue.
[skip ci]

## Steps to Test
Steps for reviewers to follow to test the change.

### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

[skip ci]

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
Thanks @cuinix for the PR the changes look good to me other than that Please read our contribution guideline regarding how to write commit message.

**Comment by mohamedawnallah** [comment]
Also we please note this requirement we should put `[skip ci]` in the commit message for small changes:

> [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or [skip ci] in the commit message for small changes.

**Comment by mohamedawnallah** [comment]
Also please note this requirement we should put `[skip ci]` in the commit message for small changes:

> [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or [skip ci] in the commit message for small changes.

**Comment by mohamedawnallah** [comment]
@cuinix I mean in the commit message. This could be modified using the `git commit --amend` command e.g. the new commit message would look like `chore: remove repetitive words`.

**Review by guggero — APPROVED** [review]
LGTM :tada: 

> Also please note this requirement we should put `[skip ci]` in the commit message

I think we should keep the CI running for this, since there are changes to the RPC and we want to know that it compiles correctly.

**Review by ellemouton — APPROVED** [review]
lgtm 🙏

**Pull request merged**
