### PR TITLE
itest: extend whitelist

### PR DESCRIPTION
**Pull request by joostjager**
PR to collect missing whitelist lines

Reply in comments with everything that is encountered.

### CODE REVIEW

**Comment by cfromknecht** [comment]
At what point do we ask ourselves if these logs messages should be fixed rather than just added to the whitelist?

**Comment by joostjager** [comment]
I was asking myself the same thing. Especially things like payment errors which really don't classify as errors but rather failures.

I think we can do both things simultaneously. Make the list complete for the next few weeks. Then take a close look at it and fix the most pressing things.

Users see those errors too and won't take them too seriously if they happen all the time.

**Comment by cfromknecht** [comment]
new one:
```
<time> [ERR] CNCT: ChannelArbitrator(<chan_point>): unable to progress *contractcourt.htlcOutgoingContestResolver: chainntnfs: system interrupt while attempting to register for block epoch notification.
```

**Comment by joostjager** [comment]
Added. For your own PRs, you can just cherry-pick this commit

**Comment by joostjager** [comment]
Many of those errors can easily be fixed by downgrading to warning

**Pull request merged**
