### PR TITLE
rpc: add alias info to some rpcs

### PR DESCRIPTION
**Pull request by Crypt-iQ**
- First commit adds a channel's aliases to `listchannels` and `closedchannels`. It also adds zero-conf information to these two calls. This includes the confirmed SCID for zero-conf channels and whether the channel is/was zero-conf.
- Second commit adds a general `listaliases` rpc. It returns an rpc-style map of `<base_scid, []aliases>`. It is a carbon copy of the `aliasMgr.baseToSet` map. It does not surface the confirmed SCID for zero-conf channels since that info isn't persisted with the `aliasMgr` and would instead require iterating through the database to look it up.

The second commit is optional and can be removed. I intentionally did not add a `LookupAlias` RPC since I thought it would be too complicated. I think it is easier at the code-level to require the user to correlate SCIDs. Doing the opposite (`LookupAlias`) would require us to add slow database-heavy RPCs or require us to change the `aliasMgr` functionality to store the zero-conf confirmed SCID data.

### CODE REVIEW

**Review by Roasbeef — APPROVED** [review]
LGTM 🐙

**Review by ellemouton — APPROVED** [review]
tACK 🔥 

quick question while testing this: I see the aliases we assign are incremented by a counter. Is this not a bit of a leak? I guess no one can really do anything with this info though 🤷‍♀️ am assuming it was done just to ensure that we never reuse an alias

**Comment by Crypt-iQ** [comment]
> I see the aliases we assign are incremented by a counter. Is this not a bit of a leak?

Yes it leaks how many aliases have been assigned which is currently 1:1 with num channels. The alternative is to store every alias ever assigned and ensure no collision. We can do this, but the change should be done before release

**Comment by Roasbeef** [comment]
> quick question while testing this: I see the aliases we assign are incremented by a counter. Is this not a bit of a leak? 

The alternative would be to use random values in the range, but then we'd need to handle the eventual collision. Ultimately we should be able to swap things out pretty easily as well: if we want to go w/ random values, we can mark the last created scid, then do random assignment from there.

**Comment by Roasbeef** [comment]
This just needs release notes then it can land.

**Pull request merged**
