### PR TITLE
Add value_sat and value_msat to Payment

### PR DESCRIPTION
**Pull request by roeierez**
This PR is following PR https://github.com/lightningnetwork/lnd/pull/1855
In addition to that change in invoice response I believe the same convention is needed in outgoing payments to remove confusion and for consistency.
This PR also maintains backward compatibility by leaving and deprecating the current "Value" field.

### CODE REVIEW

**Comment by roeierez** [comment]
Done!

**Comment by halseth** [comment]
The two proto changes should be squashed together (and regenerated), otherwise LGTM!

**Comment by roeierez** [comment]
Squashed.

**Comment by halseth** [comment]
Needs a rebase to remove the `merge branch master` commit.

**Comment by roeierez** [comment]
Removed

**Comment by halseth** [comment]
Needs a rebase to fix the proto conflict.

**Comment by cfromknecht** [comment]
Yep changes look good to me, rebase should be the last step

**Comment by roeierez** [comment]
Rebased

**Comment by roeierez** [comment]
fixed typo

**Pull request merged**
