### PR TITLE
docs: unify code block formatting

### PR DESCRIPTION
**Pull request by guggero**
I noticed that when using the `shell script` markdown hint, the code blocks are broken on GitBook (example: https://docs.lightning.engineering/advanced-best-practices/lnd-docs/psbt).
This PR fixes all code blocks.

We also use @Roasbeef's favorite unicode character ⛰ as a the representation of the shell prompt.

Finally, a commit fixes up the contribution guide by using state of the art markdown syntax for intra document links.

### CODE REVIEW

**Review by carlaKC — APPROVED** [review]
🙏

**Review by ryanthegentry — APPROVED** [review]
🙏

**Review by halseth — APPROVED** [review]

**Comment by harding** [comment]
> We also use @Roasbeef's favorite unicode character mountain as a the representation of the shell prompt.

When reviewing this commit, I found this quite confusing.  The reason documentation uses `$` as the shell prompt character is to distinguish commands run as an ordinary user account from those run as the root administrative user account, which are prefixed with `#`.  As an experienced Unix user looking at the updated documentation (or the older documents where @Roasbeef used this prefix previously), `⛰` looks to me like the name of a command or a shell alias or some sort of rendering artifact.  It does not give me the impression of being a shell prompt.

For any Unix newbies, I think this is worse.  They may not be aware of the `$` convention, but if they search for or ask for help, they should soon get an answer.  Or, if they look closely at their default shell prompt, they may figure it out on their own.  But their confusion will be prolonged, perhaps by a significant amount, if they have to figure out why there's a mountain emoji in all their examples.

I believe y'alls goal in publishing this documentation is to help your users setup and use their software with a minimum amount of confusion.  I could just be a curmudgeon who doesn't like change, but it seems to me that using an alternative prompt character takes you further way from that goal.

**Comment by halseth** [comment]
I tend to agree with Harding here, it is more common in docs indeed. What
do you think, @guggero @roasbeef?

**Comment by guggero** [comment]
I don't have a strong preference either way, my main concern is to use the same character everywhere.
It's an easy search/replace now, so whatever we end up choosing can be switched out quickly.

**Pull request merged**
