### PR TITLE
itest: fix previously known test flakes

### PR DESCRIPTION
**Pull request by yyforyongyu**
This is the final PR(4-4) where we aggressively fix issues found in `itest` to always see ✅ in our build, it depends on the following PRs,

- in #6052 we prepare the large itest fix
- the base PR #5939 where we refactored every test case so it's easier to be maintained
- in #6191 we clean up unused code
- in #6192 we start tracking node's states
- in #6193 we perform a cleanup after each test finishes

Aside from fixing `itest`, we need to have the following bug fixes to be merged to get the builds pass,

- #6053
- #6054
- #6082
- #6186
- #6214

In this final PR, previously seen test flakes such as tx not found, balance not updated, channel not open, edge not disabled, etc have all been fixed with an understanding of their cause. Unfortunately, not every flake has a perfect solution. The flake as a connection not happening within a timeout is caused by two nodes canceling each other's connection attempt(see the commit for more details), which has no trivial fix at the moment. Such flakes have been provided workarounds and marked with `TODO`s to allow more time to be spent in the future to refactor the relevant subsystems and fix the issues.

Q:
- ~~6 confs is needed to announce a public channel otherwise the channel edge won’t be heard. Is this 6-conf configurable?~~ No we cannot.
- ~~We can only create 8 running nodes at the same time, otherwise the BuildChainControl in config_builder.go won't succeed. Does anyone know why?~~ Turns out the --rpcmaxwebsockets is the cause.

### CODE REVIEW

**Comment by guggero** [comment]
Cool, I think it makes a lot of sense to look into the amount of blocks we mine. Especially since we now explicitly wait 200ms (or was it 500?) after each mined block to give every lnd subsystem time to catch up.

> 6 confs is needed to announce a public channel otherwise the channel edge won’t be heard. Is this 6-conf configurable?

That sounds like a spec thing, but I can't find it. Looks pretty hard coded though: https://github.com/lightningnetwork/lnd/blob/master/funding/manager.go#L2626

> We can only create 8 running nodes at the same time, otherwise the BuildChainControl in config_builder.go won't succeed. Does anyone know why?

Hmm..., very weird. Do you get a specific error?

**Comment by yyforyongyu** [comment]
> Cool, I think it makes a lot of sense to look into the amount of blocks we mine. Especially since we now explicitly wait 200ms (or was it 500?) after each mined block to give every lnd subsystem time to catch up.

Yeah I think we have to manage this otherwise we may get to a point that it takes minutes to spin up a new node.

> > 6 confs is needed to announce a public channel otherwise the channel edge won’t be heard. Is this 6-conf configurable?
> 
> That sounds like a spec thing, but I can't find it. Looks pretty hard coded though: https://github.com/lightningnetwork/lnd/blob/master/funding/manager.go#L2626

Got it. Thanks for the link! Looks like it VERY hardcoded😂

> > We can only create 8 running nodes at the same time, otherwise the BuildChainControl in config_builder.go won't succeed. Does anyone know why?
> 
> Hmm..., very weird. Do you get a specific error?

No, it will hang there. I tried to trace it, what I found is, when creating a 9th node, the `BuildChainControl` in `config_builder.go` won't succeed. In particular, the `NewChainControl` will stop at `lnWallet.Startup()`, which calls the `Start()` inside `btcwallet.go`. 

Now inside the `btcwallet.Start`, it will be stuck at `b.chain.Start()`. In the end, the `b.chain.Start()` calls the `ChainSource` created in `chainreg/chainregistry.go`, at `chain.NewRPCClient`. 

Have to say it's not easy to track...

**Comment by guggero** [comment]
Hmm, this sounds like the number of concurrent RPC connections to `btcd` might be too low. It looks like the default value for `-rpcmaxclients=` is 10, so if we also have the miner and the harness connected, that would explain the block (just waiting for a thread that never becomes available).

**Comment by yyforyongyu** [comment]
> Hmm, this sounds like the number of concurrent RPC connections to `btcd` might be too low. It looks like the default value for `-rpcmaxclients=` is 10, so if we also have the miner and the harness connected, that would explain the block (just waiting for a thread that never becomes available).

I also suspect it's a conf thing. Tested with `--rpcmaxclients=20` by changing the config inside `lntest/btcd.go` and got no luck. Also this only happens with `btcd` backend, other two are fine.

**Comment by yyforyongyu** [comment]
> Hmm, this sounds like the number of concurrent RPC connections to `btcd` might be too low. It looks like the default value for `-rpcmaxclients=` is 10, so if we also have the miner and the harness connected, that would explain the block (just waiting for a thread that never becomes available).

Turns out the `--rpcmaxwebsockets` is the cause. For chainbackend, we use 1 for the miner, and each new node requires 3, 3 * 8 + 1 = 25, which is the default value of `rpcmaxwebsockets`.

**Comment by guggero** [comment]
Can be rebased now.

**Comment by yyforyongyu** [comment]
!lightninglabs-deploy mute 2022-May-15

**Comment by yyforyongyu** [comment]
Replaced by #6825

**Pull request closed without merging**
